---
- name: "18.10.6.1 | L1 | Ensure 'Allow Microsoft accounts to be optional' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_10_6_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
    name: MSAOptional
    data: 1
    type: dword
