---
- name: "18.10.16.1 | L1 | Ensure 'Allow Diagnostic Data' is set to 'Enabled: Diagnostic data off (not recommended)' or 'Enabled: Send required diagnostic data'"
  when:
    - w2025cis_rule_18_10_16_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
    name: AllowTelemetry
    data: "{{ _w2025cis_telemetry_level_value }}"
    type: dword

- name: "18.10.16.2 | L2 | Ensure 'Configure Authenticated Proxy usage for the Connected User Experience and Telemetry service' is set to 'Enabled: Disable Authenticated Proxy usage'"
  when:
    - w2025cis_rule_18_10_16_2_enabled
    - w2025cis_rule_18_10_16_2_force or _w2025cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
    name: DisableEnterpriseAuthProxy
    data: 1
    type: dword

- name: "18.10.16.3 | L1 | Ensure 'Disable OneSettings Downloads' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_10_16_3_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
    name: DisableOneSettingsDownloads
    data: 1
    type: dword

- name: "18.10.16.4 | L1 | Ensure 'Do not show feedback notifications' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_10_16_4_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
    name: DoNotShowFeedbackNotifications
    data: 1
    type: dword

- name: "18.10.16.5 | L1 | Ensure 'Enable OneSettings Auditing' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_10_16_5_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
    name: EnableOneSettingsAuditing
    data: 1
    type: dword

- name: "18.10.16.6 | L1 | Ensure 'Limit Diagnostic Log Collection' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_10_16_6_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
    name: LimitDiagnosticLogCollection
    data: 1
    type: dword

- name: "18.10.16.7 | L1 | Ensure 'Limit Dump Collection' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_10_16_7_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
    name: LimitDumpCollection
    data: 1
    type: dword

- name: "18.10.16.8 | L1 | Ensure 'Toggle user control over Insider builds' is set to 'Disabled'"
  when:
    - w2025cis_rule_18_10_16_8_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PreviewBuilds
    name: AllowBuildPreview
    data: 0
    type: dword
