---
- name: Execute the 18.10.4.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.4.x.yml

- name: Execute the 18.10.6.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.6.x.yml

- name: Execute the 18.10.8.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.8.x.yml

- name: Execute the 18.10.9.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.9.x.yml

- name: Execute the 18.10.11.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.11.x.yml

- name: Execute the 18.10.13.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.13.x.yml

- name: Execute the 18.10.14.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.14.x.yml

- name: Execute the 18.10.15.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.15.x.yml

- name: Execute the 18.10.16.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.16.x.yml

- name: Execute the 18.10.18.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.18.x.yml

- name: Execute the 18.10.26.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.26.x.yml

- name: Execute the 18.10.29.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.29.x.yml

- name: Execute the 18.10.37.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.37.x.yml

- name: Execute the 18.10.41.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.41.x.yml

- name: Execute the 18.10.42.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.42.x.yml

- name: Execute the 18.10.43.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.43.x.yml

- name: Execute the 18.10.51.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.51.x.yml

- name: Execute the 18.10.56.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.56.x.yml

- name: Execute the 18.10.57.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.57.x.yml

- name: Execute the 18.10.58.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.58.x.yml

- name: Execute the 18.10.59.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.59.x.yml

- name: Execute the 18.10.63.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.63.x.yml

- name: Execute the 18.10.76.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.76.x.yml

- name: Execute the 18.10.80.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.80.x.yml

- name: Execute the 18.10.81.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.81.x.yml

- name: Execute the 18.10.82.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.82.x.yml

- name: Execute the 18.10.87.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.87.x.yml

- name: Execute the 18.10.89.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.89.x.yml

- name: Execute the 18.10.90.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.90.x.yml

- name: Execute the 18.10.92.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.92.x.yml

- name: Execute the 18.10.93.x tasks
  ansible.builtin.import_tasks: section18/18.10/18.10.93.x.yml
