---
_w2025cis_standalone: "{{ ansible_windows_domain_role == 'Stand-alone server' and not w2025cis_is_template }}"
_w2025cis_domain_controller: >-
  {{ ansible_windows_domain_role | regex_search('(domain controller)') and not w2025cis_is_template }}
_w2025cis_member_server: "{{ ansible_windows_domain_role == 'Member server' and not w2025cis_is_template }}"

_w2025cis_level2_domain_controller: "{{ _w2025cis_domain_controller and _w2025cis_level2 }}"
_w2025cis_level2_member_server: "{{ _w2025cis_member_server and _w2025cis_level2 }}"

_w2025cis_level2: "{{ w2025cis_level | int > 1 }}"
_w2025cis_ngws: "{{ w2025cis_level | int > 2 }}"

_w2025cis_standalone_or_member_server: "{{ _w2025cis_standalone or _w2025cis_member_server }}"
_w2025cis_domain_controller_or_member_server: "{{ _w2025cis_domain_controller or _w2025cis_member_server }}"

_w2025cis_access_this_computer_from_the_network_default_users: >-
  {{ ["Administrators", "Authenticated Users", "ENTERPRISE DOMAIN CONTROLLERS"] if _w2025cis_domain_controller else ["Administrators", "Authenticated Users"] }}

_w2025cis_adjust_memory_quotas_for_a_process_default_users:
  - Administrators
  - LOCAL SERVICE
  - NETWORK SERVICE

_w2025cis_create_global_objects_default_users:
  - Administrators
  - LOCAL SERVICE
  - NETWORK SERVICE
  - SERVICE

_w2025cis_debug_programs_default_users:
  - Administrators

_w2025cis_generate_security_audits_default_users:
  - LOCAL SERVICE
  - NETWORK SERVICE

_w2025cis_impersonate_a_client_after_authentication_default_users:
  - Administrators
  - LOCAL SERVICE
  - NETWORK SERVICE
  - SERVICE

_w2025cis_manage_auditing_and_security_log_default_users:
  - Administrators

_w2025cis_perform_volume_maintenance_tasks_default_users:
  - Administrators

_w2025cis_replace_a_process_level_token_default_users:
  - LOCAL SERVICE
  - NETWORK SERVICE

_w2025cis_access_this_computer_from_the_network_users: >-
  {{ w2025cis_access_this_computer_from_the_network_additional_users + _w2025cis_access_this_computer_from_the_network_default_users }}
_w2025cis_adjust_memory_quotas_for_a_process_users: >-
  {{ w2025cis_adjust_memory_quotas_for_a_process_additional_users + _w2025cis_adjust_memory_quotas_for_a_process_default_users }}
_w2025cis_create_global_objects_users: >-
  {{ w2025cis_create_global_objects_additional_users + _w2025cis_create_global_objects_default_users }}
_w2025cis_debug_programs_users: >-
  {{ w2025cis_debug_programs_additional_users + _w2025cis_debug_programs_default_users }}
_w2025cis_generate_security_audits_users: >-
  {{ w2025cis_generate_security_audits_additional_users + _w2025cis_generate_security_audits_default_users }}
_w2025cis_impersonate_a_client_after_authentication_users: >-
  {{ w2025cis_impersonate_a_client_after_authentication_additional_users + _w2025cis_impersonate_a_client_after_authentication_default_users }}
_w2025cis_manage_auditing_and_security_log_users: >-
  {{ w2025cis_manage_auditing_and_security_log_additional_users + _w2025cis_manage_auditing_and_security_log_default_users }}
_w2025cis_perform_volume_maintenance_tasks_users: >-
  {{ w2025cis_perform_volume_maintenance_tasks_additional_users + _w2025cis_perform_volume_maintenance_tasks_default_users }}
_w2025cis_replace_a_process_level_token_users: >-
  {{ w2025cis_replace_a_process_level_token_additional_users + _w2025cis_replace_a_process_level_token_default_users }}

_w2025cis_increase_scheduling_priority_users: '{{ ["Administrators"] if _windows_installation_type == "Server Core" else ["Administrators", "Window Manager\Window Manager Group"] }}'

_w2025cis_smart_card_removal_behavior_map:
  lock: 1
  logoff: 2
  disconnect: 3

_w2025cis_smb_spn_target_name_validation_level_map:
  accept: 1
  required: 2

_w2025cis_ldap_client_encryption_requirements_map:
  negotiate: 1
  require: 2

_w2025cis_ldap_client_signing_requirements_map:
  negotiate: 1
  require: 2

_w2025cis_outgoing_ntlm_traffic_requirement_map:
  audit_all: 1
  deny_all: 2

_w2025cis_admin_uac_elevation_behavior_map:
  prompt_for_credentials: 1
  prompt_for_consent: 2

_w2025cis_laps_directory_map:
  azure_ad: 1
  ad: 2

_w2025cis_laps_post_authentication_actions_map:
  reset_password_and_logoff: 3
  reset_password_and_reboot: 5

_w2025cis_doh_policy_map:
  require: 3
  allow: 2
  prohibit: 1

_w2025cis_netbios_dns_resolution_behavior_map:
  disabled: 0
  disabled_on_public_networks: 2

_w2025cis_rpc_listener_authentication_protocol_map:
  negotiate: 0
  kerberos: 1

_w2025cis_vbs_platform_security_level_map:
  secure_boot_and_dma_protection: 3
  secure_boot: 1

_w2025cis_whfb_roca_mitigation_map:
  block: 2
  audit: 1

_w2025cis_windows_connect_pin_requirement_map:
  always: 2
  first_time: 1

_w2025cis_telemetry_level_map:
  required: 1
  'off': 0

_w2025cis_brute_force_protection_aggressiveness_map:
  medium: 1
  high: 2

_w2025cis_brute_force_protection_configured_state_map:
  block: 1
  audit: 2

_w2025cis_remote_encryption_protection_aggressiveness_map:
  medium: 1
  high: 2

_w2025cis_windows_ink_workspace_access_map:
  disallow_above_lock: 1
  disabled: 0

_w2025cis_smart_card_removal_behavior_value: >-
  {{ _w2025cis_smart_card_removal_behavior_map[w2025cis_smart_card_removal_behavior] }}
_w2025cis_smb_spn_target_name_validation_level_value: >-
  {{ _w2025cis_smb_spn_target_name_validation_level_map[w2025cis_smb_spn_target_name_validation_level] }}
_w2025cis_ldap_client_encryption_requirements_value: >-
  {{ _w2025cis_ldap_client_encryption_requirements_map[w2025cis_ldap_client_encryption_requirements] }}
_w2025cis_ldap_client_signing_requirements_value: >-
  {{ _w2025cis_ldap_client_signing_requirements_map[w2025cis_ldap_client_signing_requirements] }}
_w2025cis_outgoing_ntlm_traffic_requirement_value: >-
  {{ _w2025cis_outgoing_ntlm_traffic_requirement_map[w2025cis_outgoing_ntlm_traffic_requirement] }}
_w2025cis_admin_uac_elevation_behavior_value: >-
  {{ _w2025cis_admin_uac_elevation_behavior_map[w2025cis_admin_uac_elevation_behavior] }}
_w2025cis_laps_directory_value: >-
  {{ _w2025cis_laps_directory_map[w2025cis_laps_directory] }}
_w2025cis_laps_post_authentication_actions_value: >-
  {{ _w2025cis_laps_post_authentication_actions_map[w2025cis_laps_post_authentication_actions] }}
_w2025cis_doh_policy_value: >-
  {{ _w2025cis_doh_policy_map[w2025cis_doh_policy] }}
_w2025cis_netbios_dns_resolution_behavior_value: >-
  {{ _w2025cis_netbios_dns_resolution_behavior_map[w2025cis_netbios_dns_resolution_behavior] }}
_w2025cis_rpc_listener_authentication_protocol_value: >-
  {{ _w2025cis_rpc_listener_authentication_protocol_map[w2025cis_rpc_listener_authentication_protocol] }}
_w2025cis_vbs_platform_security_level_value: >-
  {{ _w2025cis_vbs_platform_security_level_map[w2025cis_vbs_platform_security_level] }}
_w2025cis_whfb_roca_mitigation_value: >-
  {{ _w2025cis_whfb_roca_mitigation_map[w2025cis_whfb_roca_mitigation] }}
_w2025cis_windows_connect_pin_requirement_value: >-
  {{ _w2025cis_windows_connect_pin_requirement_map[w2025cis_windows_connect_pin_requirement] }}
_w2025cis_telemetry_level_value: >-
  {{ _w2025cis_telemetry_level_map[w2025cis_telemetry_level] }}
_w2025cis_brute_force_protection_aggressiveness_value: >-
  {{ _w2025cis_brute_force_protection_aggressiveness_map[w2025cis_brute_force_protection_aggressiveness] }}
_w2025cis_brute_force_protection_configured_state_value: >-
  {{ _w2025cis_brute_force_protection_configured_state_map[w2025cis_brute_force_protection_configured_state] }}
_w2025cis_remote_encryption_protection_aggressiveness_value: >-
  {{ _w2025cis_remote_encryption_protection_aggressiveness_map[w2025cis_remote_encryption_protection_aggressiveness] }}
_w2025cis_windows_ink_workspace_access_value: >-
  {{ _w2025cis_windows_ink_workspace_access_map[w2025cis_windows_ink_workspace_access] }}
