---
- name: Execute the 4.1.x tasks
  ansible.builtin.import_tasks: section4/4.1.x.yml

- name: Execute the 4.2.x tasks
  ansible.builtin.import_tasks: section4/4.2.x.yml

- name: Execute the 4.3.x tasks
  ansible.builtin.import_tasks: section4/4.3.x.yml

- name: Execute the 4.4.x tasks
  ansible.builtin.import_tasks: section4/4.4.x.yml

- name: Execute the 4.5.x tasks
  ansible.builtin.import_tasks: section4/4.5.x.yml
