---
- name: "18.9.25.1 | L1 | Ensure 'Configure password backup directory' is set to 'Enabled: Active Directory' or 'Enabled: Azure Active Directory'"
  when:
    - w2025cis_rule_18_9_25_1_enabled
    - _w2025cis_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS
    name: BackupDirectory
    data: "{{ _w2025cis_laps_directory_value }}"
    type: dword

- name: "18.9.25.2 | L1 | Ensure 'Do not allow password expiration time longer than required by policy' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_9_25_2_enabled
    - _w2025cis_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS
    name: PwdExpirationProtectionEnabled
    data: 1
    type: dword

- name: "18.9.25.3 | L1 | Ensure 'Enable password encryption' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_9_25_3_enabled
    - _w2025cis_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS
    name: ADPasswordEncryptionEnabled
    data: 1
    type: dword

- name: "18.9.25.4 | L1 | Ensure 'Password Settings: Password Complexity' is set to 'Enabled: Large letters + small letters + numbers + special characters'"
  when:
    - w2025cis_rule_18_9_25_4_enabled
    - _w2025cis_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS
    name: PasswordComplexity
    data: 4
    type: dword

- name: "18.9.25.5 | L1 | Ensure 'Password Settings: Password Length' is set to 'Enabled: 15 or more'"
  when:
    - w2025cis_rule_18_9_25_5_enabled
    - _w2025cis_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS
    name: PasswordLength
    data: "{{ w2025cis_laps_password_length }}"
    type: dword

- name: "18.9.25.6 | L1 | Ensure 'Password Settings: Password Age (Days)' is set to 'Enabled: 30 or fewer'"
  when:
    - w2025cis_rule_18_9_25_6_enabled
    - _w2025cis_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS
    name: PasswordAgeDays
    data: "{{ w2025cis_laps_password_age_in_days }}"
    type: dword

- name: "18.9.25.7 | L1 | Ensure 'Post-authentication actions: Grace period (hours)' is set to 'Enabled: 8 or fewer hours, but not 0'"
  when:
    - w2025cis_rule_18_9_25_7_enabled
    - _w2025cis_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS
    name: PostAuthenticationResetDelay
    data: "{{ w2025cis_laps_post_authentication_grace_period_in_hours }}"
    type: dword

- name: "18.9.25.8 | L1 | Ensure 'Post-authentication actions: Actions' is set to 'Enabled: Reset the password and logoff the managed account' or higher"
  when:
    - w2025cis_rule_18_9_25_8_enabled
    - _w2025cis_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS
    name: PostAuthenticationActions
    data: "{{ _w2025cis_laps_post_authentication_actions_value }}"
    type: dword
