---
- name: "18.9.47.5.1 | L2 | Ensure 'Microsoft Support Diagnostic Tool: Turn on MSDT interactive communication with support provider' is set to 'Disabled'"
  when:
    - w2025cis_rule_18_9_47_5_1_enabled
    - w2025cis_rule_18_9_47_5_1_force or _w2025cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Scripteddiagnosticsprovider\Policy
    name: DisableQueryRemoteServer
    data: 0
    type: dword

- name: "18.9.47.11.1 | L2 | Ensure 'Enable/Disable PerfTrack' is set to 'Disabled'"
  when:
    - w2025cis_rule_18_9_47_11_1_enabled
    - w2025cis_rule_18_9_47_11_1_force or _w2025cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Wdi\{9C5A40Da-B965-4Fc3-8781-88Dd50A6299D}
    name: ScenarioExecutionEnabled
    data: 0
    type: dword
