---
- name: "18.9.5.1 | NG | Ensure 'Turn On Virtualization Based Security' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_9_5_1_enabled
    - w2025cis_rule_18_9_5_1_force or _w2025cis_ngws
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
    name: EnableVirtualizationBasedSecurity
    data: 1
    type: dword

- name: "18.9.5.2 | NG | Ensure 'Turn On Virtualization Based Security: Select Platform Security Level' is set to 'Secure Boot' or higher"
  when:
    - w2025cis_rule_18_9_5_2_enabled
    - w2025cis_rule_18_9_5_2_force or _w2025cis_ngws
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
    name: RequirePlatformSecurityFeatures
    data: "{{ _w2025cis_vbs_platform_security_level_value }}"
    type: dword

- name: "18.9.5.3 | NG | Ensure 'Turn On Virtualization Based Security: Virtualization Based Protection of Code Integrity' is set to 'Enabled with UEFI lock'"
  when:
    - w2025cis_rule_18_9_5_3_enabled
    - w2025cis_rule_18_9_5_3_force or _w2025cis_ngws
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
    name: HypervisorEnforcedCodeIntegrity
    data: 1
    type: dword

- name: "18.9.5.4 | NG | Ensure 'Turn On Virtualization Based Security: Require UEFI Memory Attributes Table' is set to 'True (checked)'"
  when:
    - w2025cis_rule_18_9_5_4_enabled
    - w2025cis_rule_18_9_5_4_force or _w2025cis_ngws
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
    name: HVCIMATRequired
    data: 1
    type: dword

- name: "18.9.5.5 | NG | Ensure 'Turn On Virtualization Based Security: Credential Guard Configuration' is set to 'Enabled with UEFI lock' | MS only"
  when:
    - w2025cis_rule_18_9_5_5_enabled
    - _w2025cis_standalone_or_member_server
    - w2025cis_rule_18_9_5_5_force or _w2025cis_ngws
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
    name: LsaCfgFlags
    data: 1
    type: dword

- name: "18.9.5.6 | NG | Ensure 'Turn On Virtualization Based Security: Credential Guard Configuration' is set to 'Disabled' | DC only"
  when:
    - w2025cis_rule_18_9_5_6_enabled
    - _w2025cis_domain_controller
    - w2025cis_rule_18_9_5_6_force or _w2025cis_ngws
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
    name: LsaCfgFlags
    data: 0
    type: dword

- name: "18.9.5.7 | NG | Ensure 'Turn On Virtualization Based Security: Secure Launch Configuration' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_9_5_7_enabled
    - w2025cis_rule_18_9_5_7_force or _w2025cis_ngws
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
    name: ConfigureSystemGuardLaunch
    data: 1
    type: dword
