---
- name: "18.9.39.1 | L1 | Ensure 'Configure validation of ROCA-vulnerable WHfB keys during authentication' is set to 'Enabled: Audit' or higher | DC only"
  when:
    - w2025cis_rule_18_9_39_1_enabled
    - _w2025cis_domain_controller
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\SAM
    name: SamNGCKeyROCAValidation
    data: "{{ _w2025cis_whfb_roca_mitigation_value }}"
    type: dword

- name: "18.9.39.2 | L1 | Ensure 'Configure SAM change password RPC methods policy' is set to 'Enabled: Allow strong encryption change password RPC method only' | DC only"
  when:
    - w2025cis_rule_18_9_39_2_enabled
    - _w2025cis_domain_controller
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\SAM
    name: SamrChangeUserPasswordApiPolicy
    data: 2
    type: dword

- name: "18.9.39.3 | L1 | Ensure 'Configure SAM change password RPC methods policy' is set to 'Enabled: Block all change password RPC methods' | MS only"
  when:
    - w2025cis_rule_18_9_39_3_enabled
    - _w2025cis_member_server
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\SAM
    name: SamrChangeUserPasswordApiPolicy
    data: 1
    type: dword
