---
- name: "18.9.30.1.1 | L1 | Ensure 'Block NetBIOS-based discovery for domain controller location' is set to 'Enabled'"
  when:
    - w2025cis_rule_18_9_30_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Netlogon\Parameters
    name: BlockNetbiosDiscovery
    data: 1
    type: dword
