---
_rhel8cis_level2: "{{ rhel8cis_level > 1 }}"

_rhel8cis_server: "{{ rhel8cis_machine_type == 'server' }}"
_rhel8cis_workstation: "{{ rhel8cis_machine_type == 'workstation' }}"

_rhel8cis_warning_count: 0
_rhel8cis_warning_list: []

_rhel8cis_no_sha1_crypto_subpolicies: >-
  [
  {% if rhel8cis_rule_1_6_2_enabled %}
    "NO-SHA1"
  {% endif %}
  ]

_rhel8cis_no_sshcbc_crypto_subpolicies: >-
  [
  {% if rhel8cis_rule_1_6_3_enabled %}
    "NO-SSHCBC"
  {% endif %}
  ]

_rhel8cis_no_weakmac_crypto_subpolicies: >-
  [
  {% if rhel8cis_rule_1_6_4_enabled %}
    "NO-WEAKMAC"
  {% endif %}
  ]

_rhel8cis_crypto_subpolicies: >-
  {{ _rhel8cis_no_sha1_crypto_subpolicies +
      _rhel8cis_no_sshcbc_crypto_subpolicies +
      _rhel8cis_no_weakmac_crypto_subpolicies +
      rhel8cis_additional_crypto_subpolicies | unique | list }}

_rhel8cis_expected_crypto_policy: >-
  {{ rhel8cis_crypto_policy }}{% if _rhel8cis_crypto_subpolicies | length > 0 %}:{{ _rhel8cis_crypto_subpolicies | join(':') }}{% endif %}

_rhel8cis_default_bluez_package_needed: "{{ _rhel8cis_workstation or rhel8cis_xorg_needed }}"
_rhel8cis_bluez_package_needed: "{{ rhel8cis_bluez_package_needed | default(_rhel8cis_default_bluez_package_needed) }}"
