---
- name: 2.2.1 | Ensure ftp client is not installed
  when:
    - rhel9cis_rule_2_2_1_enabled
  become: true
  ansible.builtin.dnf:
    name:
      - ftp
    state: absent

- name: 2.2.2 | Ensure ldap client is not installed
  when:
    - rhel9cis_rule_2_2_2_enabled
    - rhel9cis_rule_2_2_2_force or _rhel9cis_level2
  become: true
  ansible.builtin.dnf:
    name:
      - openldap-clients
    state: absent

- name: 2.2.3 | Ensure nis client is not installed
  when:
    - rhel9cis_rule_2_2_3_enabled
  become: true
  ansible.builtin.dnf:
    name:
      - ypbind
    state: absent

- name: 2.2.4 | Ensure telnet client is not installed
  when:
    - rhel9cis_rule_2_2_4_enabled
  become: true
  ansible.builtin.dnf:
    name:
      - telnet
    state: absent

- name: 2.2.5 | Ensure tftp client is not installed
  when:
    - rhel9cis_rule_2_2_5_enabled
  become: true
  ansible.builtin.dnf:
    name:
      - tftp
    state: absent
