---
- name: 2.3.1 | Ensure time synchronization is in use
  when:
    - rhel9cis_rule_2_3_1_enabled
  become: true
  ansible.builtin.dnf:
    name: chrony
    state: present

- name: 2.3.2 | Ensure chrony is configured
  when:
    - rhel9cis_rule_2_3_2_enabled
  become: true
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - _rhel9cis_restart_chronyd

- name: 2.3.3 | Ensure chrony is not run as the root user
  when:
    - rhel9cis_rule_2_3_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/chronyd
    regexp: '^OPTIONS='
    line: 'OPTIONS="-u chrony"'
  notify:
    - _rhel9cis_restart_chronyd
