---
- name: 4.1.1 | Ensure nftables is installed
  when:
    - rhel9cis_rule_4_1_1_enabled
  become: true
  ansible.builtin.dnf:
    name:
      - nftables
    state: present

- name: 4.1.2 | Ensure a single firewall configuration utility is in use
  when:
    - rhel9cis_rule_4_1_2_enabled
  become: true
  block:
    - name: 4.1.2 | Ensure a single firewall configuration utility is in use | firewalld
      when:
        - rhel9cis_firewall == 'firewalld'
      block:
        - name: 4.1.2 | Ensure a single firewall configuration utility is in use | firewalld package
          ansible.builtin.dnf:
            name:
              - firewalld
            state: present

        - name: 4.1.2 | Ensure a single firewall configuration utility is in use | firewalld.service
          ansible.builtin.systemd_service:
            name: firewalld.service
            state: started
            enabled: true
            masked: false

        - name: 4.1.2 | Ensure a single firewall configuration utility is in use | nftables service
          ansible.builtin.systemd_service:
            name: nftables.service
            state: stopped
            enabled: false
            masked: true

    # NFTables is not implemented yet
