---
- name: 4.2.1.1 | Ensure rsyslog is installed
  when:
    - rhel9cis_rule_4_2_1_1_enabled
  become: true
  ansible.builtin.dnf:
    name:
      - rsyslog
    state: "{{ _rhel9cis_rsyslog_state }}"

- name: 4.2.1.2 | Ensure rsyslog service is enabled
  when:
    - rhel9cis_rule_4_2_1_2_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.systemd_service:
    name: rsyslog.service
    enabled: true

- name: 4.2.1.3 | Ensure journald is configured to send logs to rsyslog
  when:
    - rhel9cis_rule_4_2_1_3_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?\s?ForwardToSyslog='
    line: 'ForwardToSyslog=yes'
    state: present
  notify:
    - _rhel9cis_restart_systemd-journald

- name: 4.2.1.4 | Ensure rsyslog default file permissions are configured
  when:
    - rhel9cis_rule_4_2_1_4_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^#?\s?\$FileCreateMode'
    line: '$FileCreateMode 0640'
    owner: root
    group: root
    mode: '0644'
  notify:
    - _rhel9cis_restart_rsyslog

- name: 4.2.1.5 | Ensure logging is configured
  when:
    - rhel9cis_rule_4_2_1_5_enabled
  ansible.builtin.include_tasks: ../add-warning.yml
  vars:
    _rhel9cis_warning_rule: '4.2.1.5'
    _rhel9cis_warning_description: This cannot be automated. Please ensure the logging is configured as required.

- name: 4.2.1.6 | Ensure rsyslog is configured to send logs to a remote log host
  when:
    - rhel9cis_rule_4_2_1_6_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.blockinfile:
    path: /etc/rsyslog.conf
    state: present
    block: |
      *.* @@{{ rhel9cis_remote_log_server }}
    insertafter: EOF
  notify:
    - _rhel9cis_restart_rsyslog

- name: 4.2.1.7 | Ensure rsyslog is not configured to receive logs from a remote client
  loop:
    - '^(\$ModLoad imtcp)'
    - '^(\$InputTCPServerRun)'
    - '^(module\(load="imtcp"\))'
    - '^(input\(type="imtcp")'
  when:
    - rhel9cis_rule_4_2_1_7_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.replace:
    path: /etc/rsyslog.conf
    regexp: '({{ item }})'
    replace: '#\1'
  notify:
    - _rhel9cis_restart_rsyslog

- name: 4.2.2.1.1 | Ensure systemd-journal-remote is installed
  when:
    - rhel9cis_rule_4_2_2_1_1_enabled
  become: true
  ansible.builtin.dnf:
    name:
      - systemd-journal-remote
    state: "{{ _rhel9cis_systemd_journal_remote_state }}"

- name: 4.2.2.1.2 | Ensure systemd-journal-remote is configured
  loop:
    - regexp: '^#?\s?URL='
      line: 'URL={{ rhel9cis_remote_log_server }}'
    - regexp: '^#?\s?ServerKeyFile='
      line: 'ServerKeyFile={{ rhel9cis_journal_server_key_file }}'
    - regexp: '^#?\s?ServerCertificateFile='
      line: 'ServerCertificateFile={{ rhel9cis_journal_server_cert_file }}'
    - regexp: '^#?\s?TrustedCertificateFile='
      line: 'TrustedCertificateFile={{ rhel9cis_journal_server_trusted_cert_file }}'
  when:
    - rhel9cis_rule_4_2_2_1_2_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journal-upload.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  notify:
    - _rhel9cis_restart_systemd-journal-remote

- name: 4.2.2.1.3 | Ensure systemd-journal-remote is enabled
  when:
    - rhel9cis_rule_4_2_2_1_3_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.systemd_service:
    name: systemd-journal-remote.service
    enabled: true
    state: started

- name: 4.2.2.1.4 | Ensure journald is not configured to receive logs from a remote client
  when:
    - rhel9cis_rule_4_2_2_1_4_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.systemd_service:
    name: systemd-journal-remote.socket
    enabled: false
    masked: true
    state: stopped

- name: 4.2.2.2 | Ensure journald service is enabled
  when:
    - rhel9cis_rule_4_2_2_2_enabled
  become: true
  ansible.builtin.systemd_service:
    name: systemd-journald.service
    enabled: true
    state: started

- name: 4.2.2.3 | Ensure journald is configured to compress large log files
  when:
    - rhel9cis_rule_4_2_2_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?\s?Compress='
    line: 'Compress=yes'
  notify:
    - _rhel9cis_restart_systemd-journald

- name: 4.2.2.4 | Ensure journald is configured to write logfiles to persistent disk
  when:
    - rhel9cis_rule_4_2_2_4_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?\s?Storage='
    line: 'Storage=persistent'
  notify:
    - _rhel9cis_restart_systemd-journald

- name: 4.2.2.5 | Ensure journald is not configured to send logs to rsyslog
  when:
    - rhel9cis_rule_4_2_2_5_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/journald.conf
    regexp: '^#?\s?ForwardToSyslog='
    replace: 'ForwardToSyslog=no'

- name: 4.2.2.6 | Ensure journald log rotation is configured per site policy
  loop:
    - regexp: '^#?\s?SystemMaxUse='
      line: 'SystemMaxUse={{ rhel9cis_journald_systemmaxuse }}'
    - regexp: '^#?\s?SystemKeepFree='
      line: 'SystemKeepFree={{ rhel9cis_journald_systemkeepfree }}'
    - regexp: '^#?\s?RuntimeMaxUse='
      line: 'RuntimeMaxUse={{ rhel9cis_journald_runtimemaxuse }}'
    - regexp: '^#?\s?RuntimeKeepFree='
      line: 'RuntimeKeepFree={{ rhel9cis_journald_runtimekeepfree }}'
    - regexp: '^#?\s?MaxFileSec='
      line: 'MaxFileSec={{ rhel9cis_journald_maxfilesec }}'
  when:
    - rhel9cis_rule_4_2_2_6_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  notify:
    - _rhel9cis_restart_systemd-journald
