---
- name: Execute the 4.1.x tasks
  ansible.builtin.import_tasks: 4.1.x.yml

- name: Execute the 4.2.x tasks
  ansible.builtin.import_tasks: 4.2.x.yml

- name: 4.3 | Ensure logrotate is configured
  when:
    - rhel9cis_rule_4_3_enabled
  block:
    - name: 4.3 | Ensure logrotate is configured | Get /etc/logrotate.d/* files
      become: true
      ansible.builtin.find:
        paths: 
          - /etc/logrotate.d
        file_type: file
        recurse: true
      register: _rhel9cis_logrotate_d

    - name: 4.3 | Ensure logrotate is configured | /etc/logrotate.conf
      become: true
      ansible.builtin.replace:
        path: /etc/logrotate.conf
        regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
        replace: "\\1{{ rhel9cis_logrotate_frequency }}"
    
    - name: 4.3 | Ensure logrotate is configured | /etc/logrotate.d/*
      loop: "{{ _rhel9cis_logrotate_d.files }}"
      become: true
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
        replace: "\\1{{ rhel9cis_logrotate_frequency }}"
      loop_control:
        label: "{{ item.path }}"

    - name: 4.3 | Ensure logrotate is configured | Add warning
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '4.3'
        _rhel9cis_warning_description: This cannot be fully automated. Please ensure logrotate is configured as required for all log types.
