---
- name: "18.10.55.1 | L2 | Ensure 'Turn off Push To Install service' is set to 'Enabled'"
  when:
    - w2019cis_rule_18_10_55_1_enabled
    - w2019cis_rule_18_10_55_1_force or _w2019cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\PushToInstall
    name: DisablePushToInstall
    data: 1
    type: dword
