---
- name: Gather distribution info
  when:
    - ansible_distribution is not defined or
      ansible_distribution_major_version is not defined or
      ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - distribution_major_version
      - os_family

- name: Validate OS version and family
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'
      - ansible_distribution_major_version is version_compare('9', '==')
    fail_msg: "This role can only be run against supported Linux distributions.  {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
    success_msg: "This role is running against a supported Linux distribution {{ ansible_distribution }} {{ ansible_distribution_major_version }}."

- name: Validate CIS level
  ansible.builtin.assert:
    that:
      - rhel9cis_level > 0
      - rhel9cis_level < 3
    fail_msg: The 'rhel9cis_level' must be 1 or 2.
    success_msg: The 'rhel9cis_level' is set to {{ rhel9cis_level }}.

- name: Validate machine type
  ansible.builtin.assert:
    that:
      - rhel9cis_machine_type == 'server' or rhel9cis_machine_type == 'workstation'
    fail_msg: The 'rhel9cis_machine_type' variable must be set to 'server' or 'workstation'.
    success_msg: The 'rhel9cis_machine_type' is set to {{ rhel9cis_machine_type }}.

- name: Validate | 1.1.2.2 | Ensure nodev option set on /tmp partition
  when:
    - rhel9cis_rule_1_1_2_2_enabled
  ansible.builtin.assert:
    that:
      - '"nodev" in rhel9cis_tmp_mount_opts'
    fail_msg: /tmp mount options are not configured to use 'nodev' option.
    success_msg: /tmp mount options are configured to use 'nodev' option.

- name: Validate | 1.1.2.3 | Ensure noexec option set on /tmp partition
  when:
    - rhel9cis_rule_1_1_2_3_enabled
  ansible.builtin.assert:
    that:
      - '"noexec" in rhel9cis_tmp_mount_opts'
    fail_msg: /tmp mount options are not configured to use 'noexec' option.
    success_msg: /tmp mount options are configured to use 'noexec' option.

- name: Validate | 1.1.2.4 | Ensure nosuid option set on /tmp partition
  when:
    - rhel9cis_rule_1_1_2_4_enabled
  ansible.builtin.assert:
    that:
      - '"nosuid" in rhel9cis_tmp_mount_opts'
    fail_msg: /tmp mount options are not configured to use 'nosuid' option.
    success_msg: /tmp mount options are configured to use 'nosuid' option.

- name: Validate | 1.1.3.2 | Ensure nodev option set on /var partition
  when:
    - rhel9cis_rule_1_1_3_2_enabled
  ansible.builtin.assert:
    that:
      - '"nodev" in rhel9cis_var_mount_opts'
    fail_msg: /var mount options are not configured to use 'nodev' option.
    success_msg: /var mount options are configured to use 'nodev' option.

- name: Validate | 1.1.3.3 | Ensure nosuid option set on /var partition
  when:
    - rhel9cis_rule_1_1_3_3_enabled
  ansible.builtin.assert:
    that:
      - '"nosuid" in rhel9cis_var_mount_opts'
    fail_msg: /var mount options are not configured to use 'nosuid' option.
    success_msg: /var mount options are configured to use 'nosuid' option.

- name: Validate | 1.1.4.2 | Ensure nodev option set on /var/tmp partition
  when:
    - rhel9cis_rule_1_1_4_2_enabled
  ansible.builtin.assert:
    that:
      - '"nodev" in rhel9cis_var_tmp_mount_opts'
    fail_msg: /var/tmp mount options are not configured to use 'nodev' option.
    success_msg: /var/tmp mount options are configured to use 'nodev' option.

- name: Validate | 1.1.4.3 | Ensure noexec option set on /var/tmp partition
  when:
    - rhel9cis_rule_1_1_4_3_enabled
  ansible.builtin.assert:
    that:
      - '"noexec" in rhel9cis_var_tmp_mount_opts'
    fail_msg: /var/tmp mount options are not configured to use 'noexec' option.
    success_msg: /var/tmp mount options are configured to use 'noexec' option.

- name: Validate | 1.1.4.4 | Ensure nosuid option set on /var/tmp partition
  when:
    - rhel9cis_rule_1_1_4_4_enabled
  ansible.builtin.assert:
    that:
      - '"nosuid" in rhel9cis_var_tmp_mount_opts'
    fail_msg: /var/tmp mount options are not configured to use 'nosuid' option.
    success_msg: /var/tmp mount options are configured to use 'nosuid' option.

- name: Validate | 1.1.5.2 | Ensure nodev option set on /var/log partition
  when:
    - rhel9cis_rule_1_1_5_2_enabled
  ansible.builtin.assert:
    that:
      - '"nodev" in rhel9cis_var_log_mount_opts'
    fail_msg: /var/log mount options are not configured to use 'nodev' option.
    success_msg: /var/log mount options are configured to use 'nodev' option.

- name: Validate | 1.1.5.3 | Ensure noexec option set on /var/log partition
  when:
    - rhel9cis_rule_1_1_5_3_enabled
  ansible.builtin.assert:
    that:
      - '"noexec" in rhel9cis_var_log_mount_opts'
    fail_msg: /var/log mount options are not configured to use 'noexec' option.
    success_msg: /var/log mount options are configured to use 'noexec' option.

- name: Validate | 1.1.5.4 | Ensure nosuid option set on /var/log partition
  when:
    - rhel9cis_rule_1_1_5_4_enabled
  ansible.builtin.assert:
    that:
      - '"nosuid" in rhel9cis_var_log_mount_opts'
    fail_msg: /var/log mount options are not configured to use 'nosuid' option.
    success_msg: /var/log mount options are configured to use 'nosuid' option.

- name: Validate | 1.1.6.2 | Ensure nodev option set on /var/log/audit partition
  when:
    - rhel9cis_rule_1_1_6_2_enabled
  ansible.builtin.assert:
    that:
      - '"nodev" in rhel9cis_var_log_audit_mount_opts'
    fail_msg: /var/log/audit mount options are not configured to use 'nodev' option.
    success_msg: /var/log/audit mount options are configured to use 'nodev' option.

- name: Validate | 1.1.6.3 | Ensure noexec option set on /var/log/audit partition
  when:
    - rhel9cis_rule_1_1_6_3_enabled
  ansible.builtin.assert:
    that:
      - '"noexec" in rhel9cis_var_log_audit_mount_opts'
    fail_msg: /var/log/audit mount options are not configured to use 'noexec' option.
    success_msg: /var/log/audit mount options are configured to use 'noexec' option.

- name: Validate | 1.1.6.4 | Ensure nosuid option set on /var/log/audit partition
  when:
    - rhel9cis_rule_1_1_6_4_enabled
  ansible.builtin.assert:
    that:
      - '"nosuid" in rhel9cis_var_log_audit_mount_opts'
    fail_msg: /var/log/audit mount options are not configured to use 'nosuid' option.
    success_msg: /var/log/audit mount options are configured to use 'nosuid' option.

- name: Validate | 1.1.7.2 | Ensure nodev option set on /home partition
  when:
    - rhel9cis_rule_1_1_7_2_enabled
  ansible.builtin.assert:
    that:
      - '"nodev" in rhel9cis_home_mount_opts'
    fail_msg: /home mount options are not configured to use 'nodev' option.
    success_msg: /home mount options are configured to use 'nodev' option.

- name: Validate | 1.1.7.3 | Ensure nosuid option set on /home partition
  when:
    - rhel9cis_rule_1_1_7_3_enabled
  ansible.builtin.assert:
    that:
      - '"nosuid" in rhel9cis_home_mount_opts'
    fail_msg: /home mount options are not configured to use 'nosuid' option.
    success_msg: /home mount options are configured to use 'nosuid' option.

- name: Validate | 1.1.8.2 | Ensure nodev option set on /dev/shm partition
  when:
    - rhel9cis_rule_1_1_8_2_enabled
  ansible.builtin.assert:
    that:
      - '"nodev" in rhel9cis_dev_shm_mount_opts'
    fail_msg: /dev/shm mount options are not configured to use 'nodev' option.
    success_msg: /dev/shm mount options are configured to use 'nodev' option.

- name: Validate | 1.1.8.3 | Ensure noexec option set on /dev/shm partition
  when:
    - rhel9cis_rule_1_1_8_3_enabled
  ansible.builtin.assert:
    that:
      - '"noexec" in rhel9cis_dev_shm_mount_opts'
    fail_msg: /dev/shm mount options are not configured to use 'noexec' option.
    success_msg: /dev/shm mount options are configured to use 'noexec' option.

- name: Validate | 1.1.8.4 | Ensure nosuid option set on /dev/shm partition
  when:
    - rhel9cis_rule_1_1_8_4_enabled
  ansible.builtin.assert:
    that:
      - '"nosuid" in rhel9cis_dev_shm_mount_opts'
    fail_msg: /dev/shm mount options are not configured to use 'nosuid' option.
    success_msg: /dev/shm mount options are configured to use 'nosuid' option.

- name: Validate | 1.4.1 | Ensure bootloader password is set
  when:
    - rhel9cis_rule_1_4_1_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_bootloader_password is defined
    fail_msg: "The 'rhel9cis_bootloader_password' is not defined."
    success_msg: "The 'rhel9cis_bootloader_password' is defined."

- name: Validate | 1.6.1.5 | Ensure the SELinux mode is enforcing
  when:
    - rhel9cis_rule_1_6_1_5_enabled
    - _rhel9cis_level2 or rhel9cis_rule_1_6_1_5_force
  ansible.builtin.assert:
    that:
      - rhel9cis_selinux_mode in ['enforcing']
    fail_msg: "The 'rhel9cis_selinux_mode' must be set to 'enforcing'."
    success_msg: "The 'rhel9cis_selinux_mode' is set to {{ rhel9cis_selinux_mode }}."

- name: Validate | 4.1.1.3 | Ensure audit_backlog_limit is sufficient
  when:
    - rhel9cis_rule_4_1_1_3_enabled
    - _rhel9cis_level2 or rhel9cis_rule_4_1_1_3_force
  ansible.builtin.assert:
    that:
      - rhel9cis_auditd_backlog_limit >= 8192
    fail_msg: "The 'rhel9cis_auditd_backlog_limit' must be set to a minimum of 8192."
    success_msg: "The 'rhel9cis_auditd_backlog_limit' is set to {{ rhel9cis_auditd_backlog_limit }}."

- name: Validate | 4.2.1.6 | Ensure rsyslog is configured to send logs to a remote log host
  when:
    - rhel9cis_rule_4_2_1_6_enabled
    - rhel9cis_syslog == 'rsyslog'
  ansible.builtin.assert:
    that:
      - rhel9cis_remote_log_server is defined
    fail_msg: "The 'rhel9cis_remote_log_server' is not defined."
    success_msg: "The 'rhel9cis_remote_log_server' is defined."

- name: Validate | 4.2.2.1.2 | Ensure systemd-journal-remote is configured
  when:
    - rhel9cis_rule_4_2_2_1_2_enabled
    - rhel9cis_syslog == 'journald'
  block:
    - name: Validate | 4.2.2.1.2 | Ensure systemd-journal-remote is configured | Remote server
      ansible.builtin.assert:
        that:
          - rhel9cis_remote_log_server is defined
        fail_msg: "The 'rhel9cis_remote_log_server' is not defined."
        success_msg: "The 'rhel9cis_remote_log_server' is defined."

    - name: Validate | 4.2.2.1.2 | Ensure systemd-journal-remote is configured | Server key file
      ansible.builtin.assert:
        that:
          - rhel9cis_journal_server_key_file is defined
        fail_msg: "The 'rhel9cis_journal_server_key_file' is not defined."
        success_msg: "The 'rhel9cis_journal_server_key_file' is defined."

    - name: Validate | 4.2.2.1.2 | Ensure systemd-journal-remote is configured | Server cert file
      ansible.builtin.assert:
        that:
          - rhel9cis_journal_server_cert_file is defined
        fail_msg: "The 'rhel9cis_journal_server_cert_file' is not defined."
        success_msg: "The 'rhel9cis_journal_server_cert_file' is defined."

    - name: Validate | 4.2.2.1.2 | Ensure systemd-journal-remote is configured | Server CA file
      ansible.builtin.assert:
        that:
          - rhel9cis_journal_server_trusted_cert_file is defined
        fail_msg: "The 'rhel9cis_journal_server_trusted_cert_file' is not defined."
        success_msg: "The 'rhel9cis_journal_server_trusted_cert_file' is defined."

- name: Validate | 5.2.16 | Ensure SSH MaxAuthTries is set to 4 or less
  when:
    - rhel9cis_rule_5_2_16_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_sshd_max_auth_tries > 0
      - rhel9cis_sshd_max_auth_tries <= 4
    fail_msg: "The 'rhel9cis_sshd_max_auth_tries' variable must be greater than 0 and less than or equal to 4."
    success_msg: "The 'rhel9cis_sshd_max_auth_tries' variable is set to {{ rhel9cis_sshd_max_auth_tries }}."

- name: Validate | 5.2.17 | Ensure sshd MaxStartups is configured
  when:
    - rhel9cis_rule_5_2_17_enabled
  block:
    - name: Validate | 5.2.17 | Ensure SSH MaxStartups is configured | Validate startups before dropping
      ansible.builtin.assert:
        that:
          - rhel9cis_sshd_max_startups_before_dropping > 0
          - rhel9cis_sshd_max_startups_before_dropping <= 10
        fail_msg: "The 'rhel9cis_sshd_max_startups_before_dropping' variable must be greater than 0 and less than or equal to 10."
        success_msg: "The 'rhel9cis_sshd_max_startups_before_dropping' variable is set to {{ rhel9cis_sshd_max_startups_before_dropping }}."

    - name: Validate | 5.2.17 | Ensure SSH MaxStartups is configured | Validate startup drop percentage
      ansible.builtin.assert:
        that:
          - rhel9cis_sshd_max_startups_drop_percentage <= 30
          - rhel9cis_sshd_max_startups_drop_percentage >= 0
        fail_msg: "The 'rhel9cis_sshd_max_startups_drop_percentage' variable must be a percentage less than or equal to 30."
        success_msg: "The 'rhel9cis_sshd_max_startups_drop_percentage' variable is set to {{ rhel9cis_sshd_max_startups_drop_percentage }}."

    - name: Validate | 5.2.17 | Ensure SSH MaxStartups is configured | Validate startup absolute maximum
      ansible.builtin.assert:
        that:
          - rhel9cis_sshd_max_startups_absolute_maximum >= rhel9cis_sshd_max_startups_before_dropping
          - rhel9cis_sshd_max_startups_absolute_maximum <= 60
        fail_msg: "The 'rhel9cis_sshd_max_startups_absolute_maximum' variable must be greater than or equal to the 'rhel9cis_sshd_max_startups_before_dropping' variable and less than or equal to 60."
        success_msg: "The 'rhel9cis_sshd_max_startups_absolute_maximum' variable is set to {{ rhel9cis_sshd_max_startups_absolute_maximum }}."

- name: Validate | 5.2.18 | Ensure SSH MaxSessions is set to 10 or less
  when:
    - rhel9cis_rule_5_2_18_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_sshd_max_sessions > 0
      - rhel9cis_sshd_max_sessions <= 10
    fail_msg: "The 'rhel9cis_sshd_max_sessions' variable must be greater than 0 and less than or equal to 10."
    success_msg: "The 'rhel9cis_sshd_max_sessions' variable is set to {{ rhel9cis_sshd_max_sessions }}."

- name: Validate | 5.2.19 | Ensure SSH LoginGraceTime is set to one minute or less
  when:
    - rhel9cis_rule_5_2_19_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_sshd_login_grace_time > 0
      - rhel9cis_sshd_login_grace_time <= 60
    fail_msg: "The 'rhel9cis_sshd_login_grace_time' variable must be greater than 0 and less than or equal to 60."
    success_msg: "The 'rhel9cis_sshd_login_grace_time' variable is set to {{ rhel9cis_sshd_login_grace_time }}."

- name: Validate | 5.2.20 | Ensure SSH Idle Timeout Interval is configured
  when:
    - rhel9cis_rule_5_2_20_enabled
  block:
    - name: Validate | 5.2.20 | Ensure SSH Idle Timeout Interval is configured | ClientAliveInterval
      ansible.builtin.assert:
        that:
          - rhel9cis_sshd_client_alive_interval > 0
        fail_msg: "The 'rhel9cis_sshd_client_alive_interval' variable must be greater than 0."
        success_msg: "The 'rhel9cis_sshd_client_alive_interval' variable is set to {{ rhel9cis_sshd_client_alive_interval }}."

    - name: Validate | 5.2.20 | Ensure SSH Idle Timeout Interval is configured | ClientAliveCountMax
      ansible.builtin.assert:
        that:
          - rhel9cis_sshd_client_alive_count_max > 0
        fail_msg: "The 'rhel9cis_sshd_client_alive_count_max' variable must be greater than 0."
        success_msg: "The 'rhel9cis_sshd_client_alive_count_max' variable is set to {{ rhel9cis_sshd_client_alive_count_max }}."

- name: Validate | 5.3.6 | Ensure sudo authentication timeout is configured correctly
  when:
    - rhel9cis_rule_5_3_6_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_sudo_authentication_timeout >= 0
      - rhel9cis_sudo_authentication_timeout <= 15
    fail_msg: "The 'rhel9cis_sudo_authentication_timeout' must be greater than or equal to 0 and be less than or equal to 15."
    success_msg: "The 'rhel9cis_sudo_authentication_timeout' is set to {{ rhel9cis_sudo_authentication_timeout }}."

- name: Validate | 5.5.1 | Ensure password creation requirements are configured
  when:
    - rhel9cis_rule_5_5_1_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_password_min_length >= 14
    fail_msg: "The 'rhel9cis_password_min_length' variable must be greater than or equal to 14."
    success_msg: "The 'rhel9cis_password_min_length' variable is set to {{ rhel9cis_password_min_length }}."

- name: Validate | 5.5.2 | Ensure lockout for failed password attempts is configured
  when:
    - rhel9cis_rule_5_5_2_enabled
  block:
    - name: Validate | 5.5.2 | Ensure lockout for failed password attempts is configured | Failed attempts
      ansible.builtin.assert:
        that:
          - rhel9cis_lockout_failed_attempts > 0
          - rhel9cis_lockout_failed_attempts <= 5
        fail_msg: "The 'rhel9cis_lockout_failed_attempts' variable must be greater than 0 and less than or equal to 5."
        success_msg: "The 'rhel9cis_lockout_failed_attempts' variable is set to {{ rhel9cis_lockout_failed_attempts }}."

    - name: Validate | 5.5.2 | Ensure lockout for failed password attempts is configured | Unlock time
      ansible.builtin.assert:
        that:
          - rhel9cis_lockout_unlock_time >= 900
        fail_msg: "The 'rhel9cis_lockout_unlock_time' variable must be greater than or equal to 900."
        success_msg: "The 'rhel9cis_lockout_unlock_time' variable is set to {{ rhel9cis_lockout_unlock_time }}."

- name: Validate | 5.5.3 | Ensure password reuse is limited
  when:
    - rhel9cis_rule_5_5_3_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_passwords_remembered >= 24
    fail_msg: "The 'rhel9cis_passwords_remembered' variable must be greater than or equal to 24."
    success_msg: "The 'rhel9cis_passwords_remembered' variable is set to {{ rhel9cis_passwords_remembered }}."

- name: Validate | 5.6.1.1 | Ensure password expiration is 365 days or less
  when:
    - rhel9cis_rule_5_6_1_1_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_password_expiration_days <= 365
      - rhel9cis_password_expiration_days > 0
    fail_msg: "The 'rhel9cis_password_expiration_days' variable must be less than or equal to 365 but not 0."
    success_msg: "The 'rhel9cis_password_expiration_days' variable is set to {{ rhel9cis_password_expiration_days }}."

- name: Validate | 5.6.1.2 | Ensure minimum days between password changes is configured
  when:
    - rhel9cis_rule_5_6_1_2_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_min_password_age <= rhel9cis_password_expiration_days
      - rhel9cis_min_password_age > 0
    fail_msg: "The 'rhel9cis_min_password_age' variable must be greater than 0."
    success_msg: "The 'rhel9cis_min_password_age' variable is set to {{ rhel9cis_min_password_age }}."

- name: Validate | 5.6.1.3 | Ensure password expiration warning days is 7 or more
  when:
    - rhel9cis_rule_5_6_1_3_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_password_expiration_warning_days >= 7
    fail_msg: "The 'rhel9cis_password_expiration_warning_days' variable must be greater than or equal to 7."
    success_msg: "The 'rhel9cis_password_expiration_warning_days' variable is set to {{ rhel9cis_password_expiration_warning_days }}."

- name: Validate | 5.6.1.4 | Ensure inactive password lock is 30 days or less
  when:
    - rhel9cis_rule_5_6_1_4_enabled
  ansible.builtin.assert:
    that:
      - rhel9cis_inactive_password_lock_days <= 30
      - rhel9cis_inactive_password_lock_days > 0
    fail_msg: "The 'rhel9cis_inactive_password_lock_days' variable must be less than or equal to 30 but not 0."
    success_msg: "The 'rhel9cis_inactive_password_lock_days' variable is set to {{ rhel9cis_inactive_password_lock_days }}."
