---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: rhel8
  description: This role applies the CIS Benchmark hardening steps on RHEL8-based machines.  It is based on the CIS Benchmark for RHEL 8, v2.0.0.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: EL
      versions:
        - '8'

collections:
  - ansible.posix
  - community.general

dependencies: []
