---
- name: 1.1.2.6.x | Configure /var/log
  when:
    - '"/var/log" not in _rhel8cis_mount_names'
  block:
    - name: 1.1.2.6.1 | Ensure /var/log is a separate partition
      when:
        - rhel8cis_rule_1_1_2_6_1_enabled
        - rhel8cis_rule_1_1_2_6_1_force or _rhel8cis_level2
      ansible.builtin.include_tasks: ../../add-warning.yml
      vars:
        _rhel8cis_warning_rule: '1.1.2.6.1'
        _rhel8cis_warning_description: >-
          /var/log is not a separate partition.

    - name: 1.1.2.6.2 | Ensure nodev option set on /var/log partition
      when:
        - rhel8cis_rule_1_1_2_6_2_enabled
      ansible.builtin.include_tasks: ../../add-warning.yml
      vars:
        _rhel8cis_warning_rule: '1.1.2.6.2'
        _rhel8cis_warning_description: >-
          /var/log is not a separate partition.
    
    - name: 1.1.2.6.3 | Ensure nosuid option set on /var/log partition
      when:
        - rhel8cis_rule_1_1_2_6_3_enabled
      ansible.builtin.include_tasks: ../../add-warning.yml
      vars:
        _rhel8cis_warning_rule: '1.1.2.6.3'
        _rhel8cis_warning_description: >-
          /var/log is not a separate partition.
    
    - name: 1.1.2.6.4 | Ensure noexec option set on /var/log partition
      when:
        - rhel8cis_rule_1_1_2_6_4_enabled
      ansible.builtin.include_tasks: ../../add-warning.yml
      vars:
        _rhel8cis_warning_rule: '1.1.2.6.4'
        _rhel8cis_warning_description: >-
          /var/log is not a separate partition.

- name: 1.1.2.6.x | Configure /var/log
  when:
    - '"/var/log" in _rhel8cis_mount_names'
    - (rhel8cis_rule_1_1_2_6_1_enabled and
      (rhel8cis_rule_1_1_2_6_1_force or _rhel8cis_level2)) or
      rhel8cis_rule_1_1_2_6_2_enabled or
      rhel8cis_rule_1_1_2_6_3_enabled or
      rhel8cis_rule_1_1_2_6_4_enabled
  block:
    - name: 1.1.2.6.x | Set existing /var/log mount configuration fact
      ansible.builtin.set_fact:
        _rhel8cis_existing_var_log_mount: >-
          {{ ansible_mounts | selectattr('mount', 'equalto', '/var/log') | list | first }}

    - name: 1.1.2.6.x | Get UUID of /var/log partition
      when:
        - rhel8cis_var_log_mount_with_uuid
      block:
        - name: 1.1.2.6.x | Get UUID of /var/log partition
          become: true
          ansible.builtin.command: "lsblk -no UUID {{ _rhel8cis_existing_var_log_mount.device }}"
          changed_when: false
          register: _rhel8cis_var_log_uuid

        - name: 1.1.2.6.x | Set /var/log UUID to source variable
          ansible.builtin.set_fact:
            _rhel8cis_var_log_source: "UUID={{ _rhel8cis_var_log_uuid.stdout }}"

    - name: 1.1.2.6.x | Set /var/log device path to source variable
      when:
        - not rhel8cis_var_log_mount_with_uuid
      ansible.builtin.set_fact:
        _rhel8cis_var_log_source: "{{ _rhel8cis_existing_var_log_mount.device }}"

    - name: |
        1.1.2.6.1 | Ensure /var/log is a separate partition
        1.1.2.6.2 | Ensure nodev option set on /var/log partition
        1.1.2.6.3 | Ensure nosuid option set on /var/log partition
        1.1.2.6.4 | Ensure noexec option set on /var/log partition
      become: true
      ansible.posix.mount:
        src: "{{ _rhel8cis_var_log_source }}"
        name: /var/log
        fstype: "{{ _rhel8cis_existing_var_log_mount.fstype }}"
        opts: "{{ rhel8cis_var_log_mount_opts | join(',') }}"
        state: present
      notify:
        - _rhel8cis_reboot
