---
- name: "17.4.1 | L1 | Ensure 'Audit Directory Service Access' is set to include 'Failure' | DC only"
  when:
    - w2025cis_rule_17_4_1_enabled
    - _w2025cis_domain_controller
  block:
    - name: "17.4.1 | L1 | Ensure 'Audit Directory Service Access' is set to include 'Failure' | DC only"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce923b-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2025cis_rule_17_4_1_audit

    - name: "17.4.1 | L1 | Ensure 'Audit Directory Service Access' is set to include 'Failure' | DC only"
      when:
        - "'Success' not in _w2025cis_rule_17_4_1_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce923b-69ae-11d9-bed3-505054503030}" /success:enable

- name: "17.4.2 | L1 | Ensure 'Audit Directory Service Changes' is set to include 'Success' | DC only"
  when:
    - w2025cis_rule_17_4_2_enabled
    - _w2025cis_domain_controller
  block:
    - name: "17.4.2 | L1 | Ensure 'Audit Directory Service Changes' is set to include 'Success' | DC only"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce923c-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2025cis_rule_17_4_2_audit

    - name: "17.4.2 | L1 | Ensure 'Audit Directory Service Changes' is set to include 'Success' | DC only"
      when:
        - "'Success' not in _w2025cis_rule_17_4_2_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce923c-69ae-11d9-bed3-505054503030}" /success:enable
