---
- name: "17.7.1 | L1 | Ensure 'Audit Audit Policy Change' is set to include 'Success'"
  when:
    - w2025cis_rule_17_7_1_enabled
  block:
    - name: "17.7.1 | L1 | Ensure 'Audit Audit Policy Change' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce922f-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2025cis_rule_17_7_1_audit

    - name: "17.7.1 | L1 | Ensure 'Audit Audit Policy Change' is set to include 'Success'"
      when:
        - "'Success' not in _w2025cis_rule_17_7_1_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce922f-69ae-11d9-bed3-505054503030}" /success:enable

- name: "17.7.2 | L1 | Ensure 'Audit Authentication Policy Change' is set to include 'Success'"
  when:
    - w2025cis_rule_17_7_2_enabled
  block:
    - name: "17.7.2 | L1 | Ensure 'Audit Authentication Policy Change' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9230-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2025cis_rule_17_7_2_audit

    - name: "17.7.2 | L1 | Ensure 'Audit Authentication Policy Change' is set to include 'Success'"
      when:
        - "'Success' not in _w2025cis_rule_17_7_2_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9230-69ae-11d9-bed3-505054503030}" /success:enable

- name: "17.7.3 | L1 | Ensure 'Audit Authorization Policy Change' is set to include 'Success'"
  when:
    - w2025cis_rule_17_7_3_enabled
  block:
    - name: "17.7.3 | L1 | Ensure 'Audit Authorization Policy Change' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9231-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2025cis_rule_17_7_3_audit

    - name: "17.7.3 | L1 | Ensure 'Audit Authorization Policy Change' is set to include 'Success'"
      when:
        - "'Success' not in _w2025cis_rule_17_7_3_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9231-69ae-11d9-bed3-505054503030}" /success:enable

- name: "17.7.4 | L1 | Ensure 'Audit MPSSVC Rule-Level Policy Change' is set to 'Success and Failure'"
  when:
    - w2025cis_rule_17_7_4_enabled
  block:
    - name: "17.7.4 | L1 | Ensure 'Audit MPSSVC Rule-Level Policy Change' is set to 'Success and Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9232-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2025cis_rule_17_7_4_audit

    - name: "17.7.4 | L1 | Ensure 'Audit MPSSVC Rule-Level Policy Change' is set to 'Success and Failure' | Success"
      when:
        - "'Success' not in _w2025cis_rule_17_7_4_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9232-69ae-11d9-bed3-505054503030}" /success:enable

    - name: "17.7.4 | L1 | Ensure 'Audit MPSSVC Rule-Level Policy Change' is set to 'Success and Failure' | Failure"
      when:
        - "'Failure' not in _w2025cis_rule_17_7_4_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9232-69ae-11d9-bed3-505054503030}" /failure:enable

- name: "17.7.5 | L1 | Ensure 'Audit Other Policy Change Events' is set to include 'Failure'"
  when:
    - w2025cis_rule_17_7_5_enabled
  block:
    - name: "17.7.5 | L1 | Ensure 'Audit Other Policy Change Events' is set to include 'Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9232-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2025cis_rule_17_7_5_audit

    - name: "17.7.5 | L1 | Ensure 'Audit Other Policy Change Events' is set to include 'Failure'"
      when:
        - "'Failure' not in _w2025cis_rule_17_7_5_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9232-69ae-11d9-bed3-505054503030}" /failure:enable
