---
- name: Gather distribution info
  when:
    - ansible_distribution is not defined or
      ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution

- name: Get Windows installation type
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    name: InstallationType
  register: _get_windows_installation_type

- name: Set Windows installation type
  ansible.builtin.set_fact:
    _windows_installation_type: "{{ _get_windows_installation_type.value | default('') }}"

- name: Run PowerShell to check if Hyper-V is installed.
  ansible.windows.win_powershell:
    script: |
      try {
        $Ansible.Result = Get-WindowsFeature Hyper-V | Select-Object -ExpandProperty Installed
      } catch {
        $Ansible.Result = $false
      }
      $Ansible.Changed = $false
  register: _w2019cis_hyperv_installed

- name: Set the Hyper-V variable
  ansible.builtin.set_fact:
    _w2019cis_hyperv: "{{ _w2019cis_hyperv_installed.result }}"

- name: Check OS version and family
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'Windows'
      - ansible_distribution | regex_search('(Microsoft Windows Server 2019)')
    fail_msg: "This role can only be run against Windows Server 2019.  {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
    success_msg: "This role is running against {{ ansible_distribution }} {{ ansible_distribution_major_version }}."

- name: Check CIS level
  ansible.builtin.assert:
    that:
      - w2019cis_level | int > 0
      - w2019cis_level | int < 4
    fail_msg: "The CIS level should be 1, 2, or 3 (NG).  Value: {{ w2019cis_level }}"
    success_msg: "The CIS level is {{ w2019cis_level }}."

- name: "Validate | 1.1.1 | L1 | Ensure 'Enforce password history' is set to '24 or more password(s)'"
  when:
    - w2019cis_rule_1_1_1_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_password_history_size | int >= 24
    fail_msg: "The variable 'w2019cis_password_history_size' must be set to than 24.  Value: {{ w2019cis_password_history_size }}"
    success_msg: "The variable 'w2019cis_password_history_size' is set to 24 or more.  Value: {{ w2019cis_password_history_size }}"

- name: "Validate | 1.1.2 | L1 | Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'"
  when:
    - w2019cis_rule_1_1_2_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_maximum_password_age | int <= 365
      - w2019cis_maximum_password_age | int > 0
    fail_msg: "The variable 'w2019cis_maximum_password_age' must be set to between 1 and 365.  Value: {{ w2019cis_maximum_password_age }}"
    success_msg: "The variable 'w2019cis_maximum_password_age' is set to between 1 and 365.  Value: {{ w2019cis_maximum_password_age }}"

- name: "Validate | 1.1.3 | L1 | Ensure 'Minimum password age' is set to '1 or more day(s)'"
  when:
    - w2019cis_rule_1_1_3_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_minimum_password_age | int >= 1
    fail_msg: "The variable 'w2019cis_minimum_password_age' must be set to 1 or more.  Value: {{ w2019cis_minimum_password_age }}"
    success_msg: "The variable 'w2019cis_minimum_password_age' is set to 1 or more.  Value: {{ w2019cis_minimum_password_age }}"

- name: "Validate | 1.1.4 | L1 | Ensure 'Minimum password length' is set to '14 or more character(s)'"
  when:
    - w2019cis_rule_1_1_4_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_minimum_password_length | int >= 14
    fail_msg: "The variable 'w2019cis_minimum_password_length' must be set to 14 or more.  Value: {{ w2019cis_minimum_password_length }}"
    success_msg: "The variable 'w2019cis_minimum_password_length' is set to 14 or more.  Value: {{ w2019cis_minimum_password_length }}"

- name: "Validate | 1.2.1 | L1 | Ensure 'Account lockout duration' is set to '15 or more minute(s)'"
  when:
    - w2019cis_rule_1_2_1_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_lockout_duration_in_minutes | int >= 15
    fail_msg: "The variable 'w2019cis_lockout_duration_in_minutes' must be set to 15 or more.  Value: {{ w2019cis_lockout_duration_in_minutes }}"
    success_msg: "The variable 'w2019cis_lockout_duration_in_minutes' is set to 15 or more.  Value: {{ w2019cis_lockout_duration_in_minutes }}"

- name: "Validate | 1.2.2 | L1 | Ensure 'Account lockout threshold' is set to '5 or fewer invalid logon attempt(s), but not 0'"
  when:
    - w2019cis_rule_1_2_2_enabled
  ansible.builtin.assert:
    that: 
      - w2019cis_lockout_bad_logon_count | int <= 5
      - w2019cis_lockout_bad_logon_count | int > 0
    fail_msg: "The variable 'w2019cis_minimum_password_length' must be set to between 1 and 5.  Value: {{ w2019cis_lockout_bad_logon_count }}"
    success_msg: "The variable 'w2019cis_minimum_password_length' is set to between 1 and 5.  Value: {{ w2019cis_lockout_bad_logon_count }}"

- name: "Validate | 1.2.4 | L1 | Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'"
  when:
    - w2019cis_rule_1_2_4_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_lockout_reset_time_in_minutes | int >= 15
    fail_msg: "The variable 'w2019cis_lockout_reset_time_in_minutes' must be set to 15 or more.  Value: {{ w2019cis_lockout_reset_time_in_minutes }}"
    success_msg: "The variable 'w2019cis_lockout_reset_time_in_minutes' is set to 15 or more.  Value: {{ w2019cis_lockout_reset_time_in_minutes }}"

- name: "Validate | 2.3.6.5 | L1 | Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0'"
  when:
    - w2019cis_rule_2_3_6_5_enabled
    - _w2019cis_domain_controller_or_member_server
  ansible.builtin.assert:
    that: 
      - w2019cis_maximum_machine_account_password_age_in_days | int <= 30
      - w2019cis_maximum_machine_account_password_age_in_days | int > 0
    fail_msg: "The variable 'w2019cis_maximum_machine_account_password_age_in_days' must be set to between 1 and 30.  Value: {{ w2019cis_maximum_machine_account_password_age_in_days }}"
    success_msg: "The variable 'w2019cis_maximum_machine_account_password_age_in_days' is set to between 1 and 30.  Value: {{ w2019cis_maximum_machine_account_password_age_in_days }}"

- name: "Validate | 2.3.7.3 | L1 | Ensure 'Interactive logon: Machine inactivity limit' is set to '900 or fewer second(s), but not 0'"
  when:
    - w2019cis_rule_2_3_7_3_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_inactivity_timeout_in_seconds | int <= 900
      - w2019cis_inactivity_timeout_in_seconds | int > 0
    fail_msg: "The variable 'w2019cis_inactivity_timeout_in_seconds' must be set to between 1 and 900.  Value: {{ w2019cis_inactivity_timeout_in_seconds }}"
    success_msg: "The variable 'w2019cis_inactivity_timeout_in_seconds' is set to between 1 and 900.  Value: {{ w2019cis_inactivity_timeout_in_seconds }}"

- name: "Validate | 2.3.7.4 | L1 | Configure 'Interactive logon: Message text for users attempting to log on'"
  when:
    - w2019cis_rule_2_3_7_4_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_login_message_text is defined
    fail_msg: "The variable 'w2019cis_login_message_text' must be defined."
    success_msg: The variable 'w2019cis_login_message_text' is defined.

- name: "2.3.7.5 | L1 | Configure 'Interactive logon: Message title for users attempting to log on'"
  when:
    - w2019cis_rule_2_3_7_5_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_login_message_title is defined
    fail_msg: "The variable 'w2019cis_login_message_title' must be defined."
    success_msg: The variable 'w2019cis_login_message_title' is defined.

- name: "Validate | 2.3.7.6 | L2 | Ensure 'Interactive logon: Number of previous logons to cache (in case domain controller is not available)' is set to '4 or fewer logon(s)' | MS only"
  when:
    - w2019cis_rule_2_3_7_6_enabled
    - _w2019cis_member_server
    - w2019cis_rule_2_3_7_6_force or _w2019cis_level2_member_server
  ansible.builtin.assert:
    that:
      - w2019cis_cached_logons_count | int <= 4
      - w2019cis_cached_logons_count | int >= 0
    fail_msg: "The variable 'w2019cis_cached_logons_count' must be set to between 1 and 4.  Value: {{ w2019cis_cached_logons_count }}"
    success_msg: "The variable 'w2019cis_cached_logons_count' is set to between 1 and 4.  Value: {{ w2019cis_cached_logons_count }}"

- name: "Validate | 2.3.7.7 | L1 | Ensure 'Interactive logon: Prompt user to change password before expiration' is set to 'between 5 and 14 days'"
  when:
    - w2019cis_rule_2_3_7_7_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_password_expiry_warning_in_days | int <= 14
      - w2019cis_password_expiry_warning_in_days | int >= 5
    fail_msg: "The variable 'w2019cis_password_expiry_warning_in_days' must be set to between 5 than 14.  Value: {{ w2019cis_password_expiry_warning_in_days }}"
    success_msg: "The variable 'w2019cis_password_expiry_warning_in_days' is set to between 5 and 14.  Value: {{ w2019cis_password_expiry_warning_in_days }}"

- name: "Validate | 2.3.9.1 | L1 | Ensure 'Microsoft network server: Amount of idle time required before suspending session' is set to '15 or fewer minute(s)'"
  when:
    - w2019cis_rule_2_3_9_1_enabled
  ansible.builtin.assert:
    that:
      - w2019_idle_smb_timeout_in_minutes | int <= 15
      - w2019_idle_smb_timeout_in_minutes | int >= 0
    fail_msg: "The variable 'w2019_idle_smb_timeout_in_minutes' must be set to between 0 and 15.  Value: {{ w2019_idle_smb_timeout_in_minutes }}"
    success_msg: "The variable 'w2019_idle_smb_timeout_in_minutes' is set to between 0 and 15.  Value: {{ w2019_idle_smb_timeout_in_minutes }}"

- name: "Validate | 9.1.6 | L1 | Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  when:
    - w2019cis_rule_9_1_6_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_domain_firewall_log_size_in_kb | int >= 16384
    fail_msg: "The variable 'w2019cis_domain_firewall_log_size_in_kb' must be set to 16384 or more.  Value: {{ w2019cis_domain_firewall_log_size_in_kb }}"
    success_msg: "The variable 'w2019cis_domain_firewall_log_size_in_kb' is set to 16384 or more.  Value: {{ w2019cis_domain_firewall_log_size_in_kb }}"

- name: "Validate | 9.2.6 | L1 | Ensure 'Windows Firewall: Private: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  when:
    - w2019cis_rule_9_2_6_enabled
  ansible.builtin.assert:
    that: 
      - w2019cis_private_firewall_log_size_in_kb | int >= 16384
    fail_msg: "The variable 'w2019cis_private_firewall_log_size_in_kb' is set to 16384 or more.  Value: {{ w2019cis_private_firewall_log_size_in_kb }}"
    success_msg: "The variable 'w2019cis_private_firewall_log_size_in_kb' is set to 16384 or more.  Value: {{ w2019cis_private_firewall_log_size_in_kb }}"

- name: "Validate | 9.3.8 | L1 | Ensure 'Windows Firewall: Public: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  when:
    - w2019cis_rule_9_3_8_enabled
  ansible.builtin.assert:
    that: 
      - w2019cis_public_firewall_log_size_in_kb | int >= 16384
    fail_msg: "The variable 'w2019cis_public_firewall_log_size_in_kb' must be set to 16384 or more.  Value: {{ w2019cis_public_firewall_log_size_in_kb }}"
    success_msg: "The variable 'w2019cis_public_firewall_log_size_in_kb' is set to 16384 or more.  Value: {{ w2019cis_public_firewall_log_size_in_kb }}"

- name: "Validate | 18.5.9 | L1 | Ensure 'MSS: (ScreenSaverGracePeriod) The time in seconds before the screen saver grace period expires (0 recommended)' is set to 'Enabled: 5 or fewer seconds'"
  when:
    - w2019cis_rule_18_5_9_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_screensaver_grace_period_in_seconds | int <= 5
      - w2019cis_screensaver_grace_period_in_seconds | int >= 0
    fail_msg: "The variable 'w2019cis_screensaver_grace_period_in_seconds' must be set to between 0 and 5.  Value: {{ w2019cis_screensaver_grace_period_in_seconds }}"
    success_msg: "The variable 'w2019cis_screensaver_grace_period_in_seconds' is set to between 0 and 5.  Value: {{ w2019cis_screensaver_grace_period_in_seconds }}"

- name: "Validate | 18.9.25.5 | L1 | Ensure 'Password Settings: Password Length' is set to 'Enabled: 15 or more'"
  when:
    - w2019cis_rule_18_9_25_5_enabled
    - _w2019cis_member_server
  ansible.builtin.assert:
    that:
      - w2019cis_laps_password_length | int >= 15
    fail_msg: "The variable 'w2019cis_laps_password_length' must be set to 15 or more.  Value: {{ w2019cis_laps_password_length }}"
    success_msg: "The variable 'w2019cis_laps_password_length' is set to 15 or more.  Value: {{ w2019cis_laps_password_length }}"

- name: "Validate | 18.9.25.6 | L1 | Ensure 'Password Settings: Password Age (Days)' is set to 'Enabled: 30 or fewer'"
  when:
    - w2019cis_rule_18_9_25_6_enabled
    - _w2019cis_member_server
  ansible.builtin.assert:
    that:
      - w2019cis_laps_password_age_in_days | int <= 30
      - w2019cis_laps_password_age_in_days | int >= 0
    fail_msg: "The variable 'w2019cis_laps_password_age_in_days' must be set to between 0 and 30.  Value: {{ w2019cis_laps_password_age_in_days }}"
    success_msg: "The variable 'w2019cis_laps_password_age_in_days' is set to between 0 and 30.  Value: {{ w2019cis_laps_password_age_in_days }}"

- name: "Validate | 18.9.25.7 | L1 | Ensure 'Post-authentication actions: Grace period (hours)' is set to 'Enabled: 8 or fewer hours, but not 0'"
  when:
    - w2019cis_rule_18_9_25_7_enabled
    - _w2019cis_member_server
  ansible.builtin.assert:
    that:
      - w2019cis_laps_post_authentication_grace_period_in_hours | int <= 8
      - w2019cis_laps_post_authentication_grace_period_in_hours | int >= 0
    fail_msg: "The variable 'w2019cis_laps_post_authentication_grace_period_in_hours' must be set to between 0 and 8.  Value: {{ w2019cis_laps_post_authentication_grace_period_in_hours }}"
    success_msg: "The variable 'w2019cis_laps_post_authentication_grace_period_in_hours' is set to between 0 and 8.  Value: {{ w2019cis_laps_post_authentication_grace_period_in_hours }}"

- name: "Validate | 18.10.25.1.2 | L1 | Ensure 'Application: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater'"
  when:
    - w2019cis_rule_18_10_25_1_2_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_application_log_max_size_in_kb | int >= 32768
    fail_msg: "The variable 'w2019cis_application_log_max_size_in_kb' must be set to 32768 or more.  Value: {{ w2019cis_application_log_max_size_in_kb }}"
    success_msg: "The variable 'w2019cis_application_log_max_size_in_kb' is set to 32768 or more.  Value: {{ w2019cis_application_log_max_size_in_kb }}"

- name: "Validate | 18.10.25.2.2 | L1 | Ensure 'Security: Specify the maximum log file size (KB)' is set to 'Enabled: 196,608 or greater'"
  when:
    - w2019cis_rule_18_10_25_2_2_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_security_log_max_size_in_kb | int >= 196608
    fail_msg: "The variable 'w2019cis_security_log_max_size_in_kb' must be set to 196608 or more.  Value: {{ w2019cis_security_log_max_size_in_kb }}"
    success_msg: "The variable 'w2019cis_security_log_max_size_in_kb' is set to 196608 or more.  Value: {{ w2019cis_security_log_max_size_in_kb }}"

- name: "Validate | 18.10.25.3.2 | L1 | Ensure 'Setup: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater'"
  when:
    - w2019cis_rule_18_10_25_3_2_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_setup_log_max_size_in_kb | int >= 32768
    fail_msg: "The variable 'w2019cis_setup_log_max_size_in_kb' must be set to 32768 or more.  Value: {{ w2019cis_setup_log_max_size_in_kb }}"
    success_msg: "The variable 'w2019cis_setup_log_max_size_in_kb' is set to 32768 or more.  Value: {{ w2019cis_setup_log_max_size_in_kb }}"

- name: "Validate | 18.10.25.4.2 | L1 | Ensure 'System: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater'"
  when:
    - w2019cis_rule_18_10_25_4_2_enabled
  ansible.builtin.assert:
    that:
      - w2019cis_system_log_max_size_in_kb | int >= 32768
    fail_msg: "The variable 'w2019cis_system_log_max_size_in_kb' set to 32768 or more.  Value: {{ w2019cis_system_log_max_size_in_kb }}"
    success_msg: "The variable 'w2019cis_system_log_max_size_in_kb' set to 32768 or more.  Value: {{ w2019cis_system_log_max_size_in_kb }}"
