---
_w2019cis_standalone: "{{ ansible_windows_domain_role == 'Stand-alone server' and not w2019cis_is_template }}"
_w2019cis_domain_controller: >-
  {{ ansible_windows_domain_role | regex_search('(domain controller)') and not w2019cis_is_template }}
_w2019cis_member_server: "{{ ansible_windows_domain_role == 'Member server' and not w2019cis_is_template }}"

_w2019cis_level2_domain_controller: "{{ _w2019cis_domain_controller and w2019cis_level > 1 }}"
_w2019cis_level2_member_server: "{{ _w2019cis_member_server and w2019cis_level > 1 }}"

_w2019cis_level2: "{{ w2019cis_level > 1 }}"
_w2019cis_ngws: "{{ w2019cis_level > 2 }}"

_w2019cis_standalone_or_member_server: "{{ _w2019cis_standalone or _w2019cis_member_server }}"
_w2019cis_domain_controller_or_member_server: "{{ _w2019cis_domain_controller or _w2019cis_member_server }}"

_w2019cis_access_this_computer_from_the_network_default_users: >-
  {{ ["Administrators", "Authenticated Users", "ENTERPRISE DOMAIN CONTROLLERS"] if _w2019cis_domain_controller else ["Administrators", "Authenticated Users"] }}

_w2019cis_adjust_memory_quotas_for_a_process_default_users:
  - Administrators
  - LOCAL SERVICE
  - NETWORK SERVICE

_w2019cis_create_global_objects_default_users:
  - Administrators
  - LOCAL SERVICE
  - NETWORK SERVICE
  - SERVICE

_w2019cis_debug_programs_default_users:
  - Administrators

_w2019cis_generate_security_audits_default_users:
  - LOCAL SERVICE
  - NETWORK SERVICE

_w2019cis_impersonate_a_client_after_authentication_default_users:
  - Administrators
  - LOCAL SERVICE
  - NETWORK SERVICE
  - SERVICE

_w2019cis_manage_auditing_and_security_log_default_users:
  - Administrators

_w2019cis_perform_volume_maintenance_tasks_default_users:
  - Administrators

_w2019cis_replace_a_process_level_token_default_users:
  - LOCAL SERVICE
  - NETWORK SERVICE

_w2019cis_access_this_computer_from_the_network_users: >-
  {{ w2019cis_access_this_computer_from_the_network_additional_users + _w2019cis_access_this_computer_from_the_network_default_users }}
_w2019cis_adjust_memory_quotas_for_a_process_users: >-
  {{ w2019cis_adjust_memory_quotas_for_a_process_additional_users + _w2019cis_adjust_memory_quotas_for_a_process_default_users }}
_w2019cis_create_global_objects_users: >-
  {{ w2019cis_create_global_objects_additional_users + _w2019cis_create_global_objects_default_users }}
_w2019cis_debug_programs_users: >-
  {{ w2019cis_debug_programs_additional_users + _w2019cis_debug_programs_default_users }}
_w2019cis_generate_security_audits_users: >-
  {{ w2019cis_generate_security_audits_additional_users + _w2019cis_generate_security_audits_default_users }}
_w2019cis_impersonate_a_client_after_authentication_users: >-
  {{ w2019cis_impersonate_a_client_after_authentication_additional_users + _w2019cis_impersonate_a_client_after_authentication_default_users }}
_w2019cis_manage_auditing_and_security_log_users: >-
  {{ w2019cis_manage_auditing_and_security_log_additional_users + _w2019cis_manage_auditing_and_security_log_default_users }}
_w2019cis_perform_volume_maintenance_tasks_users: >-
  {{ w2019cis_perform_volume_maintenance_tasks_additional_users + _w2019cis_perform_volume_maintenance_tasks_default_users }}
_w2019cis_replace_a_process_level_token_users: >-
  {{ w2019cis_replace_a_process_level_token_additional_users + _w2019cis_replace_a_process_level_token_default_users }}

_w2019cis_increase_scheduling_priority_users: '{{ ["Administrators"] if _windows_installation_type == "Server Core" else ["Administrators", "Window Manager\Window Manager Group"] }}'

_w2019cis_smart_card_removal_behavior_map:
  lock: 1
  logoff: 2
  disconnect: 3

_w2019cis_smb_spn_target_name_validation_level_map:
  accept: 1
  required: 2

_w2019cis_ldap_client_signing_requirements_map:
  require: 2
  negotiate: 1

_w2019cis_outgoing_ntlm_traffic_requirement_map:
  audit_all: 1
  deny_all: 2

_w2019cis_admin_uac_elevation_behavior_map:
  prompt_for_credentials: 1
  prompt_for_consent: 2

_w2019cis_laps_directory_map:
  azure_ad: 1
  ad: 2

_w2019cis_laps_post_authentication_actions_map:
  reset_password_and_logoff: 3
  reset_password_and_reboot: 5

_w2019cis_netbios_dns_resolution_behavior_map:
  disabled: 0
  disabled_on_public_networks: 2

_w2019cis_rpc_listener_authentication_protocol_map:
  negotiate: 0
  kerberos: 1

_w2019cis_vbs_platform_security_level_map:
  secure_boot: 1
  secure_boot_and_dma_protection: 3

_w2019cis_whfb_roca_mitigation_map:
  audit: 1
  block: 2

_w2019cis_windows_connect_pin_requirement_map:
  first_time: 1
  always: 2

_w2019cis_allow_telemetry_map:
  'off': 0
  required: 1

_w2019cis_windows_ink_workspace_access_map:
  disabled: 0
  disallow_above_lock: 1

_w2019cis_smart_card_removal_behavior_value: >-
  {{ _w2019cis_smart_card_removal_behavior_map[w2019cis_smart_card_removal_behavior] }}
_w2019cis_smb_spn_target_name_validation_level_value: >-
  {{ _w2019cis_smb_spn_target_name_validation_level_map[w2019cis_smb_spn_target_name_validation_level] }}
_w2019cis_ldap_client_signing_requirements_value: >-
  {{ _w2019cis_ldap_client_signing_requirements_map[w2019cis_ldap_client_signing_requirements] }}
_w2019cis_outgoing_ntlm_traffic_requirement_value: >-
  {{ _w2019cis_outgoing_ntlm_traffic_requirement_map[w2019cis_outgoing_ntlm_traffic_requirement] }}
_w2019cis_admin_uac_elevation_behavior_value: >-
  {{ _w2019cis_admin_uac_elevation_behavior_map[w2019cis_admin_uac_elevation_behavior] }}
_w2019cis_laps_directory_value: >-
  {{ _w2019cis_laps_directory_map[w2019cis_laps_directory] }}
_w2019cis_laps_post_authentication_actions_value: >-
  {{ _w2019cis_laps_post_authentication_actions_map[w2019cis_laps_post_authentication_actions] }}
_w2019cis_netbios_dns_resolution_behavior_value: >-
  {{ _w2019cis_netbios_dns_resolution_behavior_map[w2019cis_netbios_dns_resolution_behavior] }}
_w2019cis_rpc_listener_authentication_protocol_value: >-
  {{ _w2019cis_rpc_listener_authentication_protocol_map[w2019cis_rpc_listener_authentication_protocol] }}
_w2019cis_vbs_platform_security_level_value: >-
  {{ _w2019cis_vbs_platform_security_level_map[w2019cis_vbs_platform_security_level] }}
_w2019cis_whfb_roca_mitigation_value: >-
  {{ _w2019cis_whfb_roca_mitigation_map[w2019cis_whfb_roca_mitigation] }}
_w2019cis_windows_connect_pin_requirement_value: >-
  {{ _w2019cis_windows_connect_pin_requirement_map[w2019cis_windows_connect_pin_requirement] }}
_w2019cis_allow_telemetry_value: >-
  {{ _w2019cis_allow_telemetry_map[w2019cis_allow_telemetry] }}
_w2019cis_windows_ink_workspace_access_value: >-
  {{ _w2019cis_windows_ink_workspace_access_map[w2019cis_windows_ink_workspace_access] }}
