---
- name: "18.9.39.1 | L1 | Ensure 'Configure validation of ROCA-vulnerable WHfB keys during authentication' is set to 'Enabled: Audit' or higher | DC only"
  when:
    - w2022cis_rule_18_9_39_1_enabled
    - _w2022cis_domain_controller
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\SAM
    name: SamNGCKeyROCAValidation
    data: "{{ _w2022cis_whfb_roca_mitigation_value }}"
    type: dword
