---

- name: "18.9.20.1.1 | L1 | Ensure 'Turn off downloading of print drivers over HTTP' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Printers
    name: DisableWebPnPDownload
    data: 1
    type: dword

- name: "18.9.20.1.2 | L2 | Ensure 'Turn off handwriting personalization data sharing' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_2_enabled
    - w2022cis_rule_18_9_20_1_2_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Tabletpc
    name: PreventHandwritingDataSharing
    data: 1
    type: dword

- name: "18.9.20.1.3 | L2 | Ensure 'Turn off handwriting recognition error reporting' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_3_enabled
    - w2022cis_rule_18_9_20_1_3_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Handwritingerrorreports
    name: PreventHandwritingErrorReports
    data: 1
    type: dword

- name: "18.9.20.1.4 | L2 | Ensure 'Turn off Internet Connection Wizard if URL connection is referring to Microsoft.com' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_4_enabled
    - w2022cis_rule_18_9_20_1_4_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Internet Connection Wizard
    name: ExitOnMSICW
    data: 1
    type: dword

- name: "18.9.20.1.5 | L1 | Ensure 'Turn off Internet download for Web publishing and online ordering wizards' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_5_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
    name: NoWebServices
    data: 1
    type: dword

- name: "18.9.20.1.6 | L2 | Ensure 'Turn off printing over HTTP' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_6_enabled
    - w2022cis_rule_18_9_20_1_6_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Printers
    name: DisableHTTPPrinting
    data: 1
    type: dword

- name: "18.9.20.1.7 | L2 | Ensure 'Turn off Registration if URL connection is referring to Microsoft.com' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_7_enabled
    - w2022cis_rule_18_9_20_1_7_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Registration Wizard Control
    name: NoRegistration
    data: 1
    type: dword

- name: "18.9.20.1.8 | L2 | Ensure 'Turn off Search Companion content file updates' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_8_enabled
    - w2022cis_rule_18_9_20_1_8_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Searchcompanion
    name: DisableContentFileUpdates
    data: 1
    type: dword

- name: "18.9.20.1.9 | L2 | Ensure 'Turn off the \"Order Prints\" picture task' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_9_enabled
    - w2022cis_rule_18_9_20_1_9_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
    name: NoOnlinePrintsWizard
    data: 1
    type: dword

- name: "18.9.20.1.10 | L2 | Ensure 'Turn off the \"Publish to Web\" task for files and folders' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_10_enabled
    - w2022cis_rule_18_9_20_1_10_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
    name: NoPublishingWizard
    data: 1
    type: dword

- name: "18.9.20.1.11 | L2 | Ensure 'Turn off the Windows Messenger Customer Experience Improvement Program' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_11_enabled
    - w2022cis_rule_18_9_20_1_11_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Messenger\Client
    name: CEIP
    data: 2
    type: dword

- name: "18.9.20.1.12 | L2 | Ensure 'Turn off Windows Customer Experience Improvement Program' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_12_enabled
    - w2022cis_rule_18_9_20_1_12_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Sqmclient\Windows
    name: CEIPEnable
    data: 0
    type: dword

- name: "18.9.20.1.13 | L2 | Ensure 'Turn off Windows Error Reporting' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_20_1_13_enabled
    - w2022cis_rule_18_9_20_1_13_force or _w2022cis_level2
  block:
    - name: "18.9.20.1.13 | L2 | Ensure 'Turn off Windows Error Reporting' is set to 'Enabled' | Windows Error Reporting"
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\Windows Error Reporting
        name: Disabled
        data: 1
        type: dword

    - name: "18.9.20.1.13 | L2 | Ensure 'Turn off Windows Error Reporting' is set to 'Enabled' | ErrorReporting"
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\PCHealth\ErrorReporting
        name: DoReport
        data: 0
        type: dword
