---
- name: "18.9.35.1 | L1 | Ensure 'Configure Offer Remote Assistance' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_9_35_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: fAllowUnsolicited
    data: 0
    type: dword

- name: "18.9.35.2 | L1 | Ensure 'Configure Solicited Remote Assistance' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_9_35_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
    name: fAllowToGetHelp
    data: 0
    type: dword
