---
- name: "18.9.49.1 | L2 | Ensure 'Turn off the advertising ID' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_49_1_enabled
    - w2022cis_rule_18_9_49_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Advertisinginfo
    name: DisabledByGroupPolicy
    data: 1
    type: dword
