---
- name: "18.9.26.1 | L1 | Ensure 'Allow Custom SSPs and APs to be loaded into LSASS' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_9_26_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\System
    name: AllowCustomSSPsAPs
    data: 0
    type: dword

- name: "18.9.26.2 | NG | Ensure 'Configures LSASS to run as a protected process' is set to 'Enabled: Enabled with UEFI Lock'"
  when:
    - w2022cis_rule_18_9_26_2_enabled
    - w2022cis_rule_18_9_26_2_force or _w2022cis_ngws
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: RunAsPPL
    data: 1
    type: dword
