---
- name: "18.9.31.1 | L2 | Ensure 'Allow Clipboard synchronization across devices' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_9_31_1_enabled
    - w2022cis_rule_18_9_31_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\System
    name: AllowCrossDeviceClipboard
    data: 0
    type: dword

- name: "18.9.31.2 | L2 | Ensure 'Allow upload of User Activities' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_9_31_2_enabled
    - w2022cis_rule_18_9_31_2_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\System
    name: UploadUserActivities
    data: 0
    type: dword
