---
- name: "18.9.4.1 | L1 | Ensure 'Encryption Oracle Remediation' is set to 'Enabled: Force Updated Clients'"
  when:
    - w2022cis_rule_18_9_4_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters
    name: AllowEncryptionOracle
    data: 0
    type: dword

- name: "18.9.4.2 | L1 | Ensure 'Remote host allows delegation of non-exportable credentials' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_4_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation
    name: AllowProtectedCreds
    data: 1
    type: dword
