---
- name: 2.2.1 | Ensure autofs services are not in use
  when:
    - rhel8cis_rule_2_2_1_enabled
    - rhel8cis_rule_2_2_1_force or _rhel8cis_level2 or _rhel8cis_server
  become: true
  block:
    - name: 2.2.1 | Ensure autofs services are not in use | autofs package
      when:
        - not rhel8cis_autofs_package_needed
      ansible.builtin.dnf:
        name:
          - autofs
        state: absent

    - name: 2.2.1 | Ensure autofs services are not in use | autofs.service
      ansible.builtin.systemd_service:
        name: autofs.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_autofs_service
      failed_when:
        - _rhel8cis_autofs_service is failed
        - ("Could not find the requested service" not in _rhel8cis_autofs_service.msg)

- name: 2.2.2 | Ensure avahi daemon services are not in use
  when:
    - rhel8cis_rule_2_2_2_enabled
    - rhel8cis_rule_2_2_2_force or _rhel8cis_level2 or _rhel8cis_server
  become: true
  block:
    - name: 2.2.2 | Ensure avahi daemon services are not in use | avahi package
      when:
        - not rhel8cis_avahi_package_needed
      ansible.builtin.dnf:
        name:
          - avahi
        state: absent

    - name: 2.2.2 | Ensure avahi daemon services are not in use | avahi-daemon.service
      ansible.builtin.systemd_service:
        name: avahi-daemon.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_avahi_daemon_service
      failed_when:
        - _rhel8cis_avahi_daemon_service is failed
        - ("Could not find the requested service" not in _rhel8cis_avahi_daemon_service.msg)

    - name: 2.2.2 | Ensure avahi daemon services are not in use | avahi-daemon.socket
      ansible.builtin.systemd_service:
        name: avahi-daemon.socket
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_avahi_daemon_socket
      failed_when:
        - _rhel8cis_avahi_daemon_socket is failed
        - ("Could not find the requested service" not in _rhel8cis_avahi_daemon_socket.msg)

- name: 2.2.3 | Ensure dhcp server services are not in use
  when:
    - rhel8cis_rule_2_2_3_enabled
  become: true
  block:
    - name: 2.2.3 | Ensure dhcp server services are not in use | dhcp-server package
      when:
        - not rhel8cis_dhcp_server_package_needed
      ansible.builtin.dnf:
        name:
          - dhcp-server
        state: absent

    - name: 2.2.3 | Ensure dhcp server services are not in use | dhcpd.service
      ansible.builtin.systemd_service:
        name: dhcpd.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_dhcpd_service
      failed_when:
        - _rhel8cis_dhcpd_service is failed
        - ("Could not find the requested service" not in _rhel8cis_dhcpd_service.msg)

    - name: 2.2.3 | Ensure dhcp server services are not in use | dhcpd6.service
      ansible.builtin.systemd_service:
        name: dhcpd6.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_dhcpd6_service
      failed_when:
        - _rhel8cis_dhcpd6_service is failed
        - ("Could not find the requested service" not in _rhel8cis_dhcpd6_service.msg)

- name: 2.2.4 | Ensure dns server services are not in use
  when:
    - rhel8cis_rule_2_2_4_enabled
  become: true
  block:
    - name: 2.2.4 | Ensure dns server services are not in use | bind package
      when:
        - not rhel8cis_bind_package_needed
      ansible.builtin.dnf:
        name:
          - bind
        state: absent

    - name: 2.2.4 | Ensure dns server services are not in use | named.service
      ansible.builtin.systemd_service:
        name: named.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_named_service
      failed_when:
        - _rhel8cis_named_service is failed
        - ("Could not find the requested service" not in _rhel8cis_named_service.msg)

- name: 2.2.5 | Ensure dnsmasq services are not in use
  when:
    - rhel8cis_rule_2_2_5_enabled
  become: true
  block:
    - name: 2.2.5 | Ensure dnsmasq services are not in use | dnsmasq package
      when:
        - not rhel8cis_dnsmasq_package_needed
      ansible.builtin.dnf:
        name:
          - dnsmasq
        state: absent

    - name: 2.2.5 | Ensure dnsmasq services are not in use | dnsmasq.service
      ansible.builtin.systemd_service:
        name: dnsmasq.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_dnsmasq_service
      failed_when:
        - _rhel8cis_dnsmasq_service is failed
        - ("Could not find the requested service" not in _rhel8cis_dnsmasq_service.msg)

- name: 2.2.6 | Ensure samba file server services are not in use
  when:
    - rhel8cis_rule_2_2_6_enabled
  become: true
  block:
    - name: 2.2.6 | Ensure samba file server services are not in use | samba package
      when:
        - not rhel8cis_samba_package_needed
      ansible.builtin.dnf:
        name:
          - samba
        state: absent

    - name: 2.2.6 | Ensure samba file server services are not in use | smb.service
      ansible.builtin.systemd_service:
        name: smb.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_smb_service
      failed_when:
        - _rhel8cis_smb_service is failed
        - ("Could not find the requested service" not in _rhel8cis_smb_service.msg)

- name: 2.2.7 | Ensure ftp server services are not in use
  when:
    - rhel8cis_rule_2_2_7_enabled
  become: true
  block:
    - name: 2.2.7 | Ensure ftp server services are not in use | vsftpd package
      when:
        - not rhel8cis_vsftpd_package_needed
      ansible.builtin.dnf:
        name:
          - vsftpd
        state: absent

    - name: 2.2.7 | Ensure ftp server services are not in use | vsftpd.service
      ansible.builtin.systemd_service:
        name: vsftpd.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_vsftpd_service
      failed_when:
        - _rhel8cis_vsftpd_service is failed
        - ("Could not find the requested service" not in _rhel8cis_vsftpd_service.msg)

- name: 2.2.8 | Ensure message access server services are not in use
  when:
    - rhel8cis_rule_2_2_8_enabled
  become: true
  block:
    - name: 2.2.8 | Ensure message access server services are not in use | dovecot package
      when:
        - not rhel8cis_dovecot_package_needed
      ansible.builtin.dnf:
        name:
          - dovecot
        state: absent

    - name: 2.2.8 | Ensure message access server services are not in use | cyrus-imapd package
      when:
        - not rhel8cis_cyrus_imapd_package_needed
      ansible.builtin.dnf:
        name:
          - cyrus-imapd
        state: absent

    - name: 2.2.8 | Ensure message access server services are not in use | dovecot.service
      ansible.builtin.systemd_service:
        name: dovecot.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_dovecot_service
      failed_when:
        - _rhel8cis_dovecot_service is failed
        - ("Could not find the requested service" not in _rhel8cis_dovecot_service.msg)

    - name: 2.2.8 | Ensure message access server services are not in use | dovecot.socket
      ansible.builtin.systemd_service:
        name: dovecot.socket
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_dovecot_socket
      failed_when:
        - _rhel8cis_dovecot_socket is failed
        - ("Could not find the requested service" not in _rhel8cis_dovecot_socket.msg)

    - name: 2.2.8 | Ensure message access server services are not in use | cyrus-imapd.service
      ansible.builtin.systemd_service:
        name: cyrus-imapd.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_cyrus_imapd_service
      failed_when:
        - _rhel8cis_cyrus_imapd_service is failed
        - ("Could not find the requested service" not in _rhel8cis_cyrus_imapd_service.msg)

- name: 2.2.9 | Ensure network file system services are not in use
  when:
    - rhel8cis_rule_2_2_9_enabled
  become: true
  block:
    - name: 2.2.9 | Ensure network file system services are not in use | nfs-utils package
      when:
        - not rhel8cis_nfs_utils_package_needed
      ansible.builtin.dnf:
        name:
          - nfs-utils
        state: absent

    - name: 2.2.9 | Ensure network file system services are not in use | nfs-server.service
      ansible.builtin.systemd_service:
        name: nfs-server.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_nfs_server_service
      failed_when:
        - _rhel8cis_nfs_server_service is failed
        - ("Could not find the requested service" not in _rhel8cis_nfs_server_service.msg)

- name: 2.2.10 | Ensure nis server services are not in use
  when:
    - rhel8cis_rule_2_2_10_enabled
  become: true
  block:
    - name: 2.2.10 | Ensure nis server services are not in use | ypserv package
      when:
        - not rhel8cis_ypserv_package_needed
      ansible.builtin.dnf:
        name:
          - ypserv
        state: absent

    - name: 2.2.10 | Ensure nis server services are not in use | ypserv.service
      ansible.builtin.systemd_service:
        name: ypserv.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_ypserv_service
      failed_when:
        - _rhel8cis_ypserv_service is failed
        - ("Could not find the requested service" not in _rhel8cis_ypserv_service.msg)

- name: 2.2.11 | Ensure print server services are not in use
  when:
    - rhel8cis_rule_2_2_11_enabled
    - _rhel8cis_server
  become: true
  block:
    - name: 2.2.11 | Ensure print server services are not in use | cups package
      when:
        - not rhel8cis_cups_package_needed
      ansible.builtin.dnf:
        name:
          - cups
        state: absent

    - name: 2.2.11 | Ensure print server services are not in use | cups.service
      ansible.builtin.systemd_service:
        name: cups.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_cups_service
      failed_when:
        - _rhel8cis_cups_service is failed
        - ("Could not find the requested service" not in _rhel8cis_cups_service.msg)

    - name: 2.2.11 | Ensure print server services are not in use | cups.socket
      ansible.builtin.systemd_service:
        name: cups.socket
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_cups_socket
      failed_when:
        - _rhel8cis_cups_socket is failed
        - ("Could not find the requested service" not in _rhel8cis_cups_socket.msg)

- name: 2.2.12 | Ensure rpcbind services are not in use
  when:
    - rhel8cis_rule_2_2_12_enabled
  become: true
  block:
    - name: 2.2.12 | Ensure rpcbind services are not in use | rpcbind package
      when:
        - not rhel8cis_rpcbind_package_needed
      ansible.builtin.dnf:
        name:
          - rpcbind
        state: absent

    - name: 2.2.12 | Ensure rpcbind services are not in use | rpcbind.service
      ansible.builtin.systemd_service:
        name: rpcbind.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_rpcbind_service
      failed_when:
        - _rhel8cis_rpcbind_service is failed
        - ("Could not find the requested service" not in _rhel8cis_rpcbind_service.msg)

- name: 2.2.13 | Ensure rsync services are not in use
  when:
    - rhel8cis_rule_2_2_13_enabled
  become: true
  block:
    - name: 2.2.13 | Ensure rsync services are not in use | rsync-daemon package
      when:
        - not rhel8cis_rsync_daemon_package_needed
      ansible.builtin.dnf:
        name:
          - rsync-daemon
        state: absent

    - name: 2.2.13 | Ensure rsync services are not in use | rsyncd.service
      ansible.builtin.systemd_service:
        name: rsyncd.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_rsyncd_service
      failed_when:
        - _rhel8cis_rsyncd_service is failed
        - ("Could not find the requested service" not in _rhel8cis_rsyncd_service.msg)

    - name: 2.2.13 | Ensure rsync services are not in use | rsyncd.socket
      ansible.builtin.systemd_service:
        name: rsyncd.socket
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_rsyncd_socket
      failed_when:
        - _rhel8cis_rsyncd_socket is failed
        - ("Could not find the requested service" not in _rhel8cis_rsyncd_socket.msg)

- name: 2.2.14 | Ensure snmp services are not in use
  when:
    - rhel8cis_rule_2_2_14_enabled
  become: true
  block:
    - name: 2.2.14 | Ensure snmp services are not in use | net-snmp package
      when:
        - not rhel8cis_net_snmp_package_needed
      ansible.builtin.dnf:
        name:
          - net-snmp
        state: absent

    - name: 2.2.14 | Ensure snmp services are not in use | snmpd.service
      ansible.builtin.systemd_service:
        name: snmpd.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_snmpd_service
      failed_when:
        - _rhel8cis_snmpd_service is failed
        - ("Could not find the requested service" not in _rhel8cis_snmpd_service.msg)

- name: 2.2.15 | Ensure telnet server services are not in use
  when:
    - rhel8cis_rule_2_2_15_enabled
  become: true
  block:
    - name: 2.2.15 | Ensure telnet server services are not in use | telnet-server package
      when:
        - not rhel8cis_telnet_server_package_needed
      ansible.builtin.dnf:
        name:
          - telnet-server
        state: absent

    - name: 2.2.15 | Ensure telnet server services are not in use | telnet.socket
      ansible.builtin.systemd_service:
        name: telnet.socket
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_telnet_socket
      failed_when:
        - _rhel8cis_telnet_socket is failed
        - ("Could not find the requested service" not in _rhel8cis_telnet_socket.msg)

- name: 2.2.16 | Ensure tftp server services are not in use
  when:
    - rhel8cis_rule_2_2_16_enabled
  become: true
  block:
    - name: 2.2.16 | Ensure tftp server services are not in use | tftp-server package
      when:
        - not rhel8cis_tftp_server_package_needed
      ansible.builtin.dnf:
        name:
          - tftp-server
        state: absent

    - name: 2.2.16 | Ensure tftp server services are not in use | tftp.service
      ansible.builtin.systemd_service:
        name: tftp.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_tftp_service
      failed_when:
        - _rhel8cis_tftp_service is failed
        - ("Could not find the requested service" not in _rhel8cis_tftp_service.msg)

    - name: 2.2.16 | Ensure tftp server services are not in use | tftp.socket
      ansible.builtin.systemd_service:
        name: tftp.socket
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_tftp_socket
      failed_when:
        - _rhel8cis_tftp_socket is failed
        - ("Could not find the requested service" not in _rhel8cis_tftp_socket.msg)

- name: 2.2.17 | Ensure web proxy server services are not in use
  when:
    - rhel8cis_rule_2_2_17_enabled
  become: true
  block:
    - name: 2.2.17 | Ensure web proxy server services are not in use | squid package
      when:
        - not rhel8cis_squid_package_needed
      ansible.builtin.dnf:
        name:
          - squid
        state: absent

    - name: 2.2.17 | Ensure web proxy server services are not in use | squid.service
      ansible.builtin.systemd_service:
        name: squid.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_squid_service
      failed_when:
        - _rhel8cis_squid_service is failed
        - ("Could not find the requested service" not in _rhel8cis_squid_service.msg)

- name: 2.2.18 | Ensure web server services are not in use
  when:
    - rhel8cis_rule_2_2_18_enabled
  become: true
  block:
    - name: 2.2.18 | Ensure web server services are not in use | httpd package
      when:
        - not rhel8cis_httpd_needed
      ansible.builtin.dnf:
        name:
          - httpd
        state: absent

    - name: 2.2.18 | Ensure web server services are not in use | nginx package
      when:
        - not rhel8cis_nginx_needed
      ansible.builtin.dnf:
        name:
          - nginx
        state: absent

- name: 2.2.19 | Ensure xinetd services are not in use
  when:
    - rhel8cis_rule_2_2_19_enabled
  become: true
  block:
    - name: 2.2.19 | Ensure xinetd services are not in use | xinetd package
      when:
        - not rhel8cis_xinetd_package_needed
      ansible.builtin.dnf:
        name:
          - xinetd
        state: absent

    - name: 2.2.19 | Ensure xinetd services are not in use | xinetd.service
      ansible.builtin.systemd_service:
        name: xinetd.service
        enabled: false
        state: stopped
        masked: true
      register: _rhel8cis_xinetd_service
      failed_when:
        - _rhel8cis_xinetd_service is failed
        - ("Could not find the requested service" not in _rhel8cis_xinetd_service.msg)

- name: 2.2.20 | Ensure X window server services are not in use
  when:
    - rhel8cis_rule_2_2_20_enabled
    - _rhel8cis_server
    - rhel8cis_rule_2_2_20_force or _rhel8cis_level2
    - not rhel8cis_xorg_needed
  become: true
  ansible.builtin.dnf:
    name:
      - xorg-x11-server-Xorg
    state: absent

- name: 2.2.21 | Ensure mail transfer agents are configured for local-only mode
  when:
    - rhel8cis_rule_2_2_21_enabled
  become: true
  block:
    - name: 2.2.21 | Ensure mail transfer agents are configured for local-only mode | postfix installed
      ansible.builtin.stat:
        path: /etc/postfix/main.cf
      register: _rhel8cis_postfix_main_cf

    - name: 2.2.21 | Ensure mail transfer agents are configured for local-only mode | Configure
      when:
        - _rhel8cis_postfix_main_cf.stat.exists
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^inet_interfaces ='
        line: inet_interfaces = loopback-only
      notify:
        - _rhel8cis_restart_postfix

- name: 2.2.22 | Ensure only approved services are listening on a network interface
  when:
    - rhel8cis_rule_2_2_22_enabled
  block:
    - name: 2.2.22 | Ensure only approved services are listening on a network interface | ss
      ansible.builtin.command: ss -plntu
      changed_when: false
      register: _rhel8cis_listening_services

    - name: 2.2.22 | Ensure only approved services are listening on a network interface | Add warning
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel8cis_warning_rule: '2.2.22'
        _rhel8cis_warning_description: 
          - Remediation cannot be automated. Please review the output below for listening services on network interfaces.
          - ''
          - "{{ _rhel8cis_listening_services.stdout_lines }}"
