---
- name: |
    1.1.8.1 | Ensure /dev/shm is a separate partition
    1.1.8.2 | Ensure nodev option set on /dev/shm partition
    1.1.8.3 | Ensure nosuid option set on /dev/shm partition
    1.1.8.4 | Ensure noexec option set on /dev/shm partition
  when:
    - rhel9cis_rule_1_1_8_1_enabled or
      rhel9cis_rule_1_1_8_2_enabled or
      rhel9cis_rule_1_1_8_3_enabled or
      rhel9cis_rule_1_1_8_4_enabled
  become: true
  ansible.posix.mount:
    src: tmpfs
    name: /dev/shm
    fstype: tmpfs
    opts: "{{ rhel9cis_dev_shm_mount_opts | join(',') }}"
    state: present
  notify:
    - _rhel9cis_reboot
