---
- name: 1.1.2.4.x | Configure /var
  when:
    - '"/var" not in _rhel9cis_mount_names'
  block:
    - name: 1.1.2.4.1 | Ensure /var is a separate partition
      when:
        - rhel9cis_rule_1_1_2_4_1_enabled
        - _rhel9cis_level2 or rhel9cis_rule_1_1_2_4_1_force
      ansible.builtin.include_tasks: ../../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '1.1.2.4.1'
        _rhel9cis_warning_description: /var is not a separate partition.

    - name: 1.1.2.4.2 | Ensure nodev option set on /var partition
      when:
        - rhel9cis_rule_1_1_2_4_2_enabled
      ansible.builtin.include_tasks: ../../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '1.1.2.4.2'
        _rhel9cis_warning_description: /var is not a separate partition.
    
    - name: 1.1.2.4.3 | Ensure nosuid option set on /var partition'
      when:
        - rhel9cis_rule_1_1_2_4_3_enabled
      ansible.builtin.include_tasks: ../../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '1.1.2.4.3'
        _rhel9cis_warning_description: /var is not a separate partition.

- name: 1.1.2.4.x | Configure /var
  when:
    - '"/var" in _rhel9cis_mount_names'
    - rhel9cis_rule_1_1_2_4_1_enabled or
      rhel9cis_rule_1_1_2_4_2_enabled or
      rhel9cis_rule_1_1_2_4_3_enabled
  block:
    - name: '1.1.2.4.x | Set existing /var mount configuration fact'
      ansible.builtin.set_fact:
        _rhel9cis_existing_var_mount: >-
          {{ ansible_mounts |
              selectattr('mount', 'equalto', '/var') |
              list |
              first }}

    - name: 1.1.2.4.x | Get UUID of /var partition
      when:
        - rhel9cis_var_mount_with_uuid
      block:
        - name: 1.1.2.4.x | Get UUID of /var partition
          become: true
          ansible.builtin.command: "lsblk -no UUID {{ _rhel9cis_existing_var_mount.device }}"
          changed_when: false
          register: _rhel9cis_var_uuid

        - name: 1.1.2.4.x | Set /var UUID to source variable
          ansible.builtin.set_fact:
            _rhel9cis_var_source: "UUID={{ _rhel9cis_var_uuid.stdout }}"

    - name: 1.1.2.4.x | Set /var device path to source variable
      when:
        - not rhel9cis_var_mount_with_uuid
      ansible.builtin.set_fact:
        _rhel9cis_var_source: "{{ _rhel9cis_existing_var_mount.device }}"

    - name: |
        1.1.2.4.1 | Ensure /var is a separate partition
        1.1.2.4.2 | Ensure nodev option set on /var partition
        1.1.2.4.3 | Ensure nosuid option set on /var partition
      become: true
      ansible.posix.mount:
        src: "{{ _rhel9cis_var_source }}"
        name: /var
        fstype: "{{ _rhel9cis_existing_var_mount.fstype }}"
        opts: "{{ rhel9cis_var_mount_opts | join(',') }}"
        state: present
      notify:
        - _rhel9cis_reboot
