---
- name: 5.1.1 | Ensure permissions on /etc/ssh/sshd_config are configured
  when:
    - rhel9cis_rule_5_1_1_enabled
  become: true
  block:
    - name: 5.1.1 | Ensure permissions on /etc/ssh/sshd_config are configured | /etc/ssh/sshd_config
      ansible.builtin.file:
        path: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'
    
    - name: 5.1.1 | Ensure permissions on /etc/ssh/sshd_config are configured | Get /etc/ssh/sshd_config.d/*
      ansible.builtin.find:
        paths: /etc/ssh/sshd_config.d
        patterns: '*.conf'
        file_type: file
      register: _rhel9cis_sshd_config_d_files

    - name: 5.1.1 | Ensure permissions on /etc/ssh/sshd_config are configured | /etc/ssh/sshd_config.d/*
      loop: "{{ _rhel9cis_sshd_config_d_files.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: root
        group: root
        mode: '0600'
      loop_control:
        label: "{{ item.path }}"

- name: 5.1.2 | Ensure permissions on SSH private host key files are configured
  when:
    - rhel9cis_rule_5_1_2_enabled
  become: true
  block:
    - name: 5.1.2 | Ensure permissions on SSH private host key files are configured | Get /etc/ssh/ssh_host_*_key
      ansible.builtin.find:
        paths: 
          - /etc/ssh
        patterns:
          - 'ssh_host_*_key'
        recurse: true
        file_type: file
      register: _rhel9cis_ssh_host_private_keys
    
    - name: 5.1.2 | Ensure permissions on SSH private host key files are configured | /etc/ssh/ssh_host_*_key
      loop: "{{ _rhel9cis_ssh_host_private_keys.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: root
        group: ssh_keys
        mode: 'u=rw,g-wx,o-rwx'
      loop_control:
        label: "{{ item.path }}"

- name: 5.1.3 | Ensure permissions on SSH public host key files are configured
  when:
    - rhel9cis_rule_5_1_3_enabled
  become: true
  block:
    - name: 5.1.3 | Ensure permissions on SSH public host key files are configured | Get /etc/ssh/ssh_host_*_key.pub
      ansible.builtin.find:
        paths: 
          - /etc/ssh
        patterns:
          - 'ssh_host_*_key.pub'
        recurse: true
        file_type: file
      register: _rhel9cis_ssh_host_public_keys
    
    - name: 5.1.3 | Ensure permissions on SSH public host key files are configured | /etc/ssh/ssh_host_*_key.pub
      loop: "{{ _rhel9cis_ssh_host_public_keys.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: root
        group: root
        mode: 'u=rw,g-wx,o-wx'
      loop_control:
        label: "{{ item.path }}"

- name: 5.1.4 | Ensure sshd Ciphers are configured
  when:
    - rhel9cis_rule_5_1_4_enabled
  ansible.builtin.debug:
    msg: Rule 5.1.4 is implemented through the system-wide crypto policy.

- name: 5.1.5 | Ensure sshd KexAlgorithms is configured
  when:
    - rhel9cis_rule_5_1_5_enabled
  ansible.builtin.debug:
    msg: Rule 5.1.5 is implemented through the system-wide crypto policy.

- name: 5.1.6 | Ensure sshd MACs are configured
  when:
    - rhel9cis_rule_5_1_6_enabled
  ansible.builtin.debug:
    msg: Rule 5.1.6 is implemented through the system-wide crypto policy.

- name: 5.1.7 | Ensure sshd access is configured
  when:
    - rhel9cis_rule_5_1_7_enabled
  become: true
  block:
    - name: 5.1.7 | Ensure sshd access is configured | No AllowUsers
      when:
        - rhel9cis_sshd_allow_users | length == 0
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?AllowUsers'
        line: '#AllowUsers'
      notify:
        - _rhel9cis_restart_sshd

    - name: 5.1.7 | Ensure sshd access is configured | AllowUsers
      when:
        - rhel9cis_sshd_allow_users | length > 0
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?AllowUsers'
        line: 'AllowUsers {{ rhel9cis_sshd_allow_users | join(" ") }}'
      notify:
        - _rhel9cis_restart_sshd

    - name: 5.1.7 | Ensure sshd access is configured | No AllowGroups
      when:
        - rhel9cis_sshd_allow_groups | length == 0
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?AllowGroups'
        line: '#AllowGroups'
      notify:
        - _rhel9cis_restart_sshd

    - name: 5.1.7 | Ensure sshd access is configured | AllowGroups
      when:
        - rhel9cis_sshd_allow_groups | length > 0
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?AllowGroups'
        line: 'AllowGroups {{ rhel9cis_sshd_allow_groups | join(" ") }}'
      notify:
        - _rhel9cis_restart_sshd

    - name: 5.1.7 | Ensure sshd access is configured | No DenyUsers
      when:
        - rhel9cis_sshd_deny_users | length == 0
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?DenyUsers'
        line: '#DenyUsers'
      notify:
        - _rhel9cis_restart_sshd

    - name: 5.1.7 | Ensure sshd access is configured | DenyUsers
      when:
        - rhel9cis_sshd_deny_users | length > 0
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?DenyUsers'
        line: 'DenyUsers {{ rhel9cis_sshd_deny_users | join(" ") }}'
      notify:
        - _rhel9cis_restart_sshd

    - name: 5.1.7 | Ensure sshd access is configured | No DenyGroups
      when:
        - rhel9cis_sshd_deny_groups | length == 0
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?DenyGroups'
        line: '#DenyGroups'
      notify:
        - _rhel9cis_restart_sshd

    - name: 5.1.7 | Ensure sshd access is configured | DenyGroups
      when:
        - rhel9cis_sshd_deny_groups | length > 0
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?DenyGroups'
        line: 'DenyGroups {{ rhel9cis_sshd_deny_groups | join(" ") }}'
      notify:
        - _rhel9cis_restart_sshd

- name: 5.1.8 | Ensure sshd Banner is configured
  when:
    - rhel9cis_rule_5_1_5_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Banner'
    line: 'Banner /etc/issue.net'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.9 | Ensure sshd ClientAliveInterval and ClientAliveCountMax are configured
  when:
    - rhel9cis_rule_5_1_9_enabled
  block:
    - name: 5.1.9 | Ensure sshd ClientAliveInterval and ClientAliveCountMax are configured | ClientAliveInterval
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ClientAliveInterval'
        line: 'ClientAliveInterval {{ rhel9cis_sshd_client_alive_interval }}'
      notify:
        - _rhel9cis_restart_sshd

    - name: 5.1.9 | Ensure sshd ClientAliveInterval and ClientAliveCountMax are configured | ClientAliveCountMax
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ClientAliveCountMax'
        line: 'ClientAliveCountMax {{ rhel9cis_sshd_client_alive_count_max }}'
      notify:
        - _rhel9cis_restart_sshd

- name: 5.1.10 | Ensure sshd DisableForwarding is enabled
  when:
    - rhel9cis_rule_5_1_10_enabled
    - rhel9cis_rule_5_1_10_force or _rhel9cis_workstation or _rhel9cis_level2
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?DisableForwarding'
    line: 'DisableForwarding yes'

- name: 5.1.11 | Ensure sshd GSSAPIAuthentication is disabled
  when:
    - rhel9cis_rule_5_1_11_enabled
    - rhel9cis_rule_5_1_11_force or _rhel9cis_workstation or _rhel9cis_level2
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?GSSAPIAuthentication'
    line: 'GSSAPIAuthentication no'

- name: 5.1.12 | Ensure sshd HostbasedAuthentication is disabled
  when:
    - rhel9cis_rule_5_1_12_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?HostbasedAuthentication'
    line: 'HostbasedAuthentication no'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.13 | Ensure sshd IgnoreRhosts is enabled
  when:
    - rhel9cis_rule_5_1_13_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?IgnoreRhosts'
    line: 'IgnoreRhosts yes'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.14 | Ensure sshd LoginGraceTime is configured
  when:
    - rhel9cis_rule_5_1_14_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?LoginGraceTime'
    line: 'LoginGraceTime {{ rhel9cis_sshd_login_grace_time }}'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.15 | Ensure sshd LogLevel is configured
  when:
    - rhel9cis_rule_5_1_15_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?LogLevel'
    line: 'LogLevel {{ rhel9cis_sshd_log_level }}'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.16 | Ensure sshd MaxAuthTries is configured
  when:
    - rhel9cis_rule_5_1_16_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MaxAuthTries'
    line: 'MaxAuthTries {{ rhel9cis_sshd_max_auth_tries }}'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.17 | Ensure sshd MaxStartups is configured
  when:
    - rhel9cis_rule_5_1_17_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MaxStartups'
    line: 'MaxStartups {{ rhel9cis_sshd_max_startups_before_dropping }}:{{ rhel9cis_sshd_max_startups_drop_percentage }}:{{ rhel9cis_sshd_max_startups_absolute_maximum }}'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.18 | Ensure sshd MaxSessions is configured
  when:
    - rhel9cis_rule_5_1_18_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MaxSessions'
    line: 'MaxSessions {{ rhel9cis_sshd_max_sessions }}'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.19 | Ensure sshd PermitEmptyPasswords is disabled
  when:
    - rhel9cis_rule_5_1_19_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.20 | Ensure sshd PermitRootLogin is disabled
  when:
    - rhel9cis_rule_5_1_20_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.21 | Ensure sshd PermitUserEnvironment is disabled
  when:
    - rhel9cis_rule_5_1_21_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitUserEnvironment'
    line: 'PermitUserEnvironment no'
  notify:
    - _rhel9cis_restart_sshd

- name: 5.1.22 | Ensure sshd UsePAM is enabled
  when:
    - rhel9cis_rule_5_1_22_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?UsePAM'
    line: 'UsePAM yes'
  notify:
    - _rhel9cis_restart_sshd
