---
- name: 5.4.1.1 | Ensure password expiration is configured
  when:
    - rhel9cis_rule_5_4_1_1_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^#?\s?PASS_MAX_DAYS'
    line: "PASS_MAX_DAYS {{ rhel9cis_password_expiration_days }}"

- name: 5.4.1.2 | Ensure minimum password days is configured
  when:
    - rhel9cis_rule_5_4_1_2_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^#?\s?PASS_MIN_DAYS'
    line: "PASS_MIN_DAYS {{ rhel9cis_minimum_password_age }}"

- name: 5.4.1.3 | Ensure password expiration warning days is configured
  when:
    - rhel9cis_rule_5_4_1_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^#?\s?PASS_WARN_AGE'
    line: "PASS_WARN_AGE {{ rhel9cis_password_expiration_warning_days }}"

- name: 5.4.1.4 | Ensure strong password hashing algorithm is configured
  loop:
    - path: /etc/libuser.conf
      regexp: '^#?\s?crypt_style ='
      line: "crypt_style = {{ rhel9cis_password_encryption_algorithm | lower }}"
    - path: /etc/login.defs
      regexp: '^#?\s?ENCRYPT_METHOD'
      line: "ENCRYPT_METHOD {{ rhel9cis_password_encryption_algorithm }}"
  when:
    - rhel9cis_rule_5_4_1_4_enabled
  become: true
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"

- name: 5.4.1.5 | Ensure inactive password lock is configured
  when:
    - rhel9cis_rule_5_4_1_5_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/useradd
    regexp: '^INACTIVE'
    line: 'INACTIVE={{ rhel9cis_inactive_password_lock_days }}'

- name: 5.4.1.6 | Ensure all users last password change date is in the past
  when:
    - rhel9cis_rule_5_4_1_6_enabled
  become: true
  block:
    - name: 5.4.1.6 | Ensure all users last password change date is in the past | Get current date/time
      ansible.builtin.shell: echo $(($(date --utc --date "$1" +%s)/86400))
      changed_when: false
      failed_when: false
      register: _rhel9cis_current_date_time

    - name: 5.4.1.6 | Ensure all users last password change date is in the past | Get users with future password date # noqa risky-shell-pipe
      ansible.builtin.shell: |
        cat /etc/shadow | awk -F: '{if($3>{{ _rhel9cis_current_date_time.stdout }})print$1}'
      changed_when: false
      failed_when: false
      register: _rhel9cis_future_password_users
      
    - name: 5.4.1.6 | Ensure all users last password change date is in the past | Warn
      when:
        - _rhel9cis_future_password_users.stdout_lines | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.4.1.6'
        _rhel9cis_warning_description: >-
          '{{ _rhel9cis_future_password_users.stdout_lines | join(",") }} have invalid password dates.'

- name: 5.4.2.1 | Ensure root is the only UID 0 account
  when:
    - rhel9cis_rule_5_4_2_1_enabled
  block:
    - name: 5.4.2.1 | Ensure root is the only UID 0 account | No UID 0 accounts
      when:
        - _rhel9cis_passwd | selectattr('uid', 'eq', 0) | list | length == 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.4.2.1'
        _rhel9cis_warning_description: No accounts with UID 0 were found. This must be manually remediated.

    - name: 5.4.2.1 | Ensure root is the only UID 0 account | More than 1 UID 0 account
      when:
        - _rhel9cis_passwd | selectattr('uid', 'eq', 0) | list | length > 1
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.4.2.1'
        _rhel9cis_warning_description: More than one account has UID 0. This must be manually remediated.

    - name: 5.4.2.1 | Ensure root is the only UID 0 account | Non-root UID 0 account
      when:
        - _rhel9cis_passwd | selectattr('uid', 'eq', 0) | list | length == 1
        - (_rhel9cis_passwd | selectattr('uid', 'eq', 0) | list | first).id != 'root'
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.4.2.1'
        _rhel9cis_warning_description: >-
          '{{ (_rhel9cis_passwd | selectattr('uid', 'eq', 0) | list | first).id }}' has UID 0 and is not root. This must be manually remediated.

- name: 5.4.2.2 | Ensure root is the only GID 0 account
  when:
    - rhel9cis_rule_5_4_2_2_enabled
  block:
    - name: 5.4.2.2 | Ensure root is the only GID 0 account | No GID 0 accounts
      when:
        - _rhel9cis_passwd | selectattr('gid', 'eq', 0) | list | length == 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.4.2.2'
        _rhel9cis_warning_description: No accounts with GID 0 were found. This must be manually remediated.

    - name: 5.4.2.2 | Ensure root is the only GID 0 account | More than 1 GID 0 account
      when:
        - _rhel9cis_passwd | selectattr('gid', 'eq', 0) | list | length > 1
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.4.2.2'
        _rhel9cis_warning_description: More than one account has GID 0. This must be manually remediated.

    - name: 5.4.2.2 | Ensure root is the only GID 0 account | Non-root GID 0 account
      when:
        - _rhel9cis_passwd | selectattr('gid', 'eq', 0) | list | length == 1
        - (_rhel9cis_passwd | selectattr('gid', 'eq', 0) | list | first).id != 'root'
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.4.2.2'
        _rhel9cis_warning_description: >-
          '{{ (_rhel9cis_passwd | selectattr('gid', 'eq', 0) | list | first).id }}' has GID 0 and is not root. This must be manually remediated.

- name: 5.4.2.3 | Ensure group root is the only GID 0 group
  when:
    - rhel9cis_rule_5_4_2_3_enabled
  block:
    - name: 5.4.2.3 | Ensure group root is the only GID 0 group | No GID 0 groups
      when:
        - _rhel9cis_group | selectattr('gid', 'eq', 0) | list | length == 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.4.2.3'
        _rhel9cis_warning_description: No groups with GID 0 were found. This must be manually remediated.

    - name: 5.4.2.3 | Ensure group root is the only GID 0 group | More than 1 GID 0 group
      when:
        - _rhel9cis_group | selectattr('gid', 'eq', 0) | list | length > 1
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.4.2.3'
        _rhel9cis_warning_description: More than one group has GID 0. This must be manually remediated.

    - name: 5.4.2.3 | Ensure group root is the only GID 0 group | Non-root GID 0 group
      when:
        - _rhel9cis_group | selectattr('gid', 'eq', 0) | list | length == 1
        - (_rhel9cis_group | selectattr('gid', 'eq', 0) | list | first).id != 'root'
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.4.2.3'
        _rhel9cis_warning_description: >-
          '{{ (_rhel9cis_group | selectattr('gid', 'eq', 0) | list | first).id }}' has GID 0 and is not root. This must be manually remediated.

- name: 5.4.2.4 | Ensure root account access is controlled
  when:
    - rhel9cis_rule_5_4_2_4_enabled
  ansible.builtin.include_tasks: ../add-warning.yml
  vars:
    _rhel9cis_warning_rule: '5.4.2.4'
    _rhel9cis_warning_description: The root password will not be set by this role. Please set it or lock it manually.

- name: 5.4.2.5 | Ensure root path integrity
  when:
    - rhel9cis_rule_5_4_2_5_enabled
  ansible.builtin.include_tasks: ../add-warning.yml
  vars:
    _rhel9cis_warning_rule: '5.4.2.5'
    _rhel9cis_warning_description: The root PATH will not be set by this role. Please set it manually.

- name: 5.4.2.6 | Ensure root user umask is configured
  when:
    - rhel9cis_rule_5_4_2_6_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /root/.bash_profile
    regexp: '^#?\s?umask'
    line: 'umask 0027'

- name: 5.4.2.7 | Ensure system accounts do not have a valid login shell
  loop: "{{ _rhel9cis_passwd }}"
  when:
    - rhel9cis_rule_5_4_2_7_enabled
    - item.id != "halt"
    - item.id != "shutdown"
    - item.id != "sync"
    - item.id != "root"
    - item.id != "nfsnobody"
    - item.id != "pipewire"
    - item.uid < 1000
    - item.shell != "/bin/false"
    - item.shell != "/sbin/nologin"
  become: true
  ansible.builtin.user:
    name: "{{ item.id }}"
    shell: /usr/sbin/nologin
  loop_control:
    label: "{{ item.id }}"

- name: 5.4.2.8 | Ensure accounts without a valid login shell are locked
  loop: "{{ _rhel9cis_passwd }}"
  when:
    - rhel9cis_rule_5_4_2_8_enabled
    - item.id != "halt"
    - item.id != "shutdown"
    - item.id != "sync"
    - item.id != "root"
    - item.id != "nfsnobody"
    - item.id != "pipewire"
    - item.id != "pulse"
    - item.id != "gnome-initial-setup"
    - item.id != "avahi"
    - item.uid < 1000
  become: true
  ansible.builtin.user:
    name: "{{ item.id }}"
    password: "*"
    password_lock: true
  loop_control:
    label: "{{ item.id }}"

- name: 5.4.3.1 | Ensure nologin is not listed in /etc/shells
  when:
    - rhel9cis_rule_5_4_3_1_enabled
    - rhel9cis_rule_5_4_3_1_force or _rhel9cis_level2
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    regexp: '/nologin\b'
    state: absent

- name: 5.4.3.2 | Ensure default user shell timeout is configured
  when:
    - rhel9cis_rule_5_4_3_2_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/profile.d/timeout.sh
    create: true
    line: 'TMOUT=600'
    owner: root
    group: root
    mode: '0755'

- name: 5.4.3.3 | Ensure default user umask is configured
  when:
    - rhel9cis_rule_5_4_3_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/profile.d/umask.sh
    create: true
    line: 'umask 0027'
    owner: root
    group: root
    mode: '0755'
