---
- name: 5.6.1.1 | Ensure password expiration is 365 days or less
  when:
    - rhel9cis_rule_5_6_1_1_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^#?\s?PASS_MAX_DAYS'
    line: 'PASS_MAX_DAYS {{ rhel9cis_password_expiration_days }}'

- name: 5.6.1.2 | Ensure minimum days between password changes is configured
  when:
    - rhel9cis_rule_5_6_1_2_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^#?\s?PASS_MIN_DAYS'
    line: 'PASS_MIN_DAYS {{ rhel9cis_min_password_age }}'

- name: 5.6.1.3 | Ensure password expiration warning days is 7 or more
  when:
    - rhel9cis_rule_5_6_1_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^#?\s?PASS_WARN_AGE'
    line: 'PASS_WARN_AGE {{ rhel9cis_password_expiration_warning_days }}'

- name: 5.6.1.4 | Ensure inactive password lock is 30 days or less
  when:
    - rhel9cis_rule_5_6_1_4_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/useradd
    regexp: '^INACTIVE'
    line: 'INACTIVE={{ rhel9cis_inactive_password_lock_days }}'

- name: 5.6.1.5 | Ensure all users last password change date is in the past
  when:
    - rhel9cis_rule_5_6_1_5_enabled
  become: true
  block:
    - name: 5.6.1.5 | Ensure all users last password change date is in the past | Get current date/time
      ansible.builtin.shell: echo $(($(date --utc --date "$1" +%s)/86400))
      changed_when: false
      failed_when: false
      register: _rhel9cis_current_date_time

    - name: 5.6.1.5 | Ensure all users last password change date is in the past | Get users with future password date
      ansible.builtin.shell: |
        cat /etc/shadow | awk -F: '{if($3>{{ _rhel9cis_current_date_time.stdout }})print$1}'
      changed_when: false
      failed_when: false
      register: _rhel9cis_future_password_users
      tags:
        - always
        - skip_ansible_lint
      
    - name: 5.6.1.5 | Ensure all users last password change date is in the past | Warn
      when:
        - _rhel9cis_future_password_users.stdout_lines | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '5.6.1.5'
        _rhel9cis_warning_description: >-
          '{{ _rhel9cis_future_password_users.stdout_lines | join(",") }} have invalid password dates.'


- name: "Parse /etc/passwd to variable"
  block:
    - name: Get /etc/passwd contents
      check_mode: false
      ansible.builtin.command: cat /etc/passwd
      changed_when: false
      register: _rhel9cis_passwd_file_audit

    - name: "Parse contents to variable"
      ansible.builtin.set_fact:
        _rhel9cis_passwd: "{{ _rhel9cis_passwd_file_audit.stdout_lines | map('regex_replace', ld_passwd_regex, ld_passwd_yaml) | map('from_yaml') | list }}"
      vars:
        ld_passwd_regex: >-
          ^(?P<id>[^:]*):(?P<password>[^:]*):(?P<uid>[^:]*):(?P<gid>[^:]*):(?P<gecos>[^:]*):(?P<dir>[^:]*):(?P<shell>[^:]*)
        ld_passwd_yaml: |
          id: >-4
              \g<id>
          password: >-4
              \g<password>
          uid: \g<uid>
          gid: \g<gid>
          gecos: >-4
              \g<gecos>
          dir: >-4
              \g<dir>
          shell: >-4
              \g<shell>

- name: 5.6.2 | Ensure system accounts are secured
  when:
    - rhel9cis_rule_5_6_2_enabled
  become: true
  block:
    - name: 5.6.2 | Ensure system accounts are secured | Set nologin shell
      loop: "{{ _rhel9cis_passwd }}"
      when:
        - item.id != "halt"
        - item.id != "shutdown"
        - item.id != "sync"
        - item.id != "root"
        - item.id != "nfsnobody"
        - item.id != "pipewire"
        - item.uid < 1000
        - item.shell != "/bin/false"
        - item.shell != "/sbin/nologin"
      ansible.builtin.user:
        name: "{{ item.id }}"
        shell: /usr/sbin/nologin
      loop_control:
        label: "{{ item.id }}"

    - name: 5.6.2 | Ensure system accounts are secured | Lock password
      loop: "{{ _rhel9cis_passwd }}"
      when:
        - item.id != "halt"
        - item.id != "shutdown"
        - item.id != "sync"
        - item.id != "root"
        - item.id != "nfsnobody"
        - item.id != "pipewire"
        - item.id != "pulse"
        - item.id != "gnome-initial-setup"
        - item.id != "avahi"
        - item.uid < 1000
      ansible.builtin.user:
        name: "{{ item.id }}"
        password: "*"
        password_lock: true
      loop_control:
        label: "{{ item.id }}"

- name: 5.6.3 | Ensure default user shell timeout is 900 seconds or less
  when:
    - rhel9cis_rule_5_6_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/profile.d/timeout.sh
    create: true
    line: 'TMOUT={{ rhel9cis_shell_timeout }}'
    owner: root
    group: root
    mode: '0755'

- name: 5.6.4 | Ensure default group for the root account is GID 0
  when:
    - rhel9cis_rule_5_6_4_enabled
  become: true
  block:
    - name: 5.6.4 | Ensure default group for the root account is GID 0 | Check GID
      ansible.builtin.shell: "awk -F: '$1==\"root\"{print $1\":\"$4}' /etc/passwd"
      changed_when: false
      register: _rhel9cis_root_group

    - name: 5.6.4 | Ensure default group for the root account is GID 0 | Change
      when:
        - _rhel9cis_root_group.stdout != 'root:0'
      ansible.builtin.command: usermod -g 0 root
      changed_when: true

- name: 5.6.5 | Ensure default user umask is 027 or more restrictive
  when:
    - rhel9cis_rule_5_6_5_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/profile.d/umask.sh
    create: true
    line: 'umask 0027'
    owner: root
    group: root
    mode: '0755'

- name: 5.6.6 | Ensure root password is set
  when:
    - rhel9cis_rule_5_6_6_enabled
  ansible.builtin.include_tasks: ../add-warning.yml
  vars:
    _rhel9cis_warning_rule: '5.6.6'
    _rhel9cis_warning_description: The root password will not be set by this role. Please set it manually.
