---
- name: 6.2.1 | Ensure accounts in /etc/passwd use shadowed passwords
  when:
    - rhel9cis_rule_6_2_1_enabled
  become: true
  ansible.builtin.replace:
    path: /etc/passwd
    regexp: '^(\S+)(?::[^:]*):(\d+):(\d+):([^:]*):([^:]*):([^:]*)$'
    replace: '\1:x:\2:\3:\4:\5:\6'

- name: 6.2.2 | Ensure /etc/shadow password fields are not empty
  when:
    - rhel9cis_rule_6_2_2_enabled
  become: true
  block:
    - name: 6.2.2 | Ensure /etc/shadow password fields are not empty | Get list of empty password users
      ansible.builtin.shell: |
        cat /etc/shadow | awk -F: '($2 == \"\" ) { print $1; }'
      changed_when: false
      failed_when: false
      register: _rhel9cis_empty_password_users
      tags:
        - always
        - skip_ansible_lint

    - name: 6.2.2 | Ensure /etc/shadow password fields are not empty | Lock empty password users
      loop: "{{ _rhel9cis_empty_password_users.stdout_lines }}"
      ansible.builtin.user:
        name: "{{ item }}"
        password: "!"
        password_lock: true

- name: 6.2.3 | Ensure all groups in /etc/passwd exist in /etc/group
  when:
    - rhel9cis_rule_6_2_3_enabled
  block:
    - name: 6.2.3 | Ensure all groups in /etc/passwd exist in /etc/group | Get list of users with missing groups
      become: true
      ansible.builtin.shell: |
        pwck -r | grep 'no group' | awk '{ gsub("[:\47]",""); print $2}'
      changed_when: false
      failed_when: false
      register: _rhel9cis_missing_group_users
      tags:
        - always
        - skip_ansible_lint

    - name: 6.2.3 | Ensure all groups in /etc/passwd exist in /etc/group | Add warning
      when:
        - _rhel9cis_missing_group_users.stdout_lines | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '6.2.3'
        _rhel9cis_warning_description: |
          The following users have a group assigned that does not exist on the system:
          
          {{ _rhel9cis_missing_group_users.stdout_lines | join("\n") }}

- name: 6.2.4 | Ensure no duplicate UIDs exist
  when:
    - rhel9cis_rule_6_2_4_enabled
  block:
    - name: 6.2.4 | Ensure no duplicate UIDs exist | Get list of duplicate UIDs
      become: true
      ansible.builtin.shell: |
        pwck -r | awk -F: '{if ($3 in uid) print $1 ; else uid[$3]}' /etc/passwd
      changed_when: false
      failed_when: false
      register: _rhel9cis_duplicate_uids
      tags:
        - always
        - skip_ansible_lint

    - name: 6.2.4 | Ensure no duplicate UIDs exist | Add warning
      when:
        - _rhel9cis_duplicate_uids.stdout_lines | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '6.2.4'
        _rhel9cis_warning_description: |
          The following UIDs have duplicate users:
          
          {{ _rhel9cis_duplicate_uids.stdout_lines | join("\n") }}

- name: 6.2.5 | Ensure no duplicate GIDs exist
  when:
    - rhel9cis_rule_6_2_5_enabled
  block:
    - name: 6.2.5 | Ensure no duplicate GIDs exist | Get list of duplicate GIDs
      become: true
      ansible.builtin.shell: |
        pwck -r | awk -F: '{if ($3 in gid) print $1 ; else gid[$3]}' /etc/group
      changed_when: false
      failed_when: false
      register: _rhel9cis_duplicate_gids
      tags:
        - always
        - skip_ansible_lint

    - name: 6.2.5 | Ensure no duplicate GIDs exist | Add warning
      when:
        - _rhel9cis_duplicate_gids.stdout_lines | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '6.2.5'
        _rhel9cis_warning_description: |
          The following GIDs have duplicate groups:
          
          {{ _rhel9cis_duplicate_gids.stdout_lines | join("\n") }}

- name: 6.2.6 | Ensure no duplicate user names exist
  when:
    - rhel9cis_rule_6_2_6_enabled
  block:
    - name: 6.2.6 | Ensure no duplicate user names exist | Get list of duplicate user names
      become: true
      ansible.builtin.shell: |
        pwck -r | awk -F: '{if ($1 in users) print $1 ; else users[$1]}' /etc/passwd
      changed_when: false
      failed_when: false
      register: _rhel9cis_duplicate_user_names
      tags:
        - always
        - skip_ansible_lint

    - name: 6.2.6 | Ensure no duplicate user names exist | Add warning
      when:
        - _rhel9cis_duplicate_user_names.stdout_lines | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '6.2.6'
        _rhel9cis_warning_description: |
          The following users have duplicate names:
          
          {{ _rhel9cis_duplicate_user_names.stdout_lines | join("\n") }}

- name: 6.2.7 | Ensure no duplicate group names exist
  when:
    - rhel9cis_rule_6_2_7_enabled
  block:
    - name: 6.2.7 | Ensure no duplicate group names exist | Get list of duplicate group names
      become: true
      ansible.builtin.shell: |
        getent passwd | cut -d: -f1 | sort -n | uniq -d
      changed_when: false
      failed_when: false
      register: _rhel9cis_duplicate_group_names
      tags:
        - always
        - skip_ansible_lint

    - name: 6.2.7 | Ensure no duplicate group names exist | Add warning
      when:
        - _rhel9cis_duplicate_group_names.stdout_lines | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '6.2.7'
        _rhel9cis_warning_description: |
          The following groups have duplicate names:
          
          {{ _rhel9cis_duplicate_group_names.stdout_lines | join("\n") }}

- name: 6.2.8 | Ensure root PATH integrity
  when:
    - rhel9cis_rule_6_2_8_enabled
  ansible.builtin.include_tasks: ../add-warning.yml
  vars:
    _rhel9cis_warning_rule: '6.2.8'
    _rhel9cis_warning_description: This cannot be fully automated. Please ensure the root path integrity is as required.

- name: 6.2.9 | Ensure root is the only UID 0 account
  when:
    - rhel9cis_rule_6_2_9_enabled
  block:
    - name: 6.2.9 | Ensure root is the only UID 0 account | Get list of non-root UID 0 users
      become: true
      ansible.builtin.shell: |
        cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") { print $1 }'
      changed_when: false
      failed_when: false
      register: _rhel9cis_non_root_uid_0_users
      tags:
        - always
        - skip_ansible_lint

    - name: 6.2.9 | Ensure root is the only UID 0 account | Add warning
      when:
        - _rhel9cis_non_root_uid_0_users.stdout_lines | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '6.2.9'
        _rhel9cis_warning_description: |
          The following non-root users have UID 0:
          
          {{ _rhel9cis_non_root_uid_0_users.stdout_lines | join("\n") }}

- name: 6.2.10 | Ensure local interactive user home directories are configured
  when:
    - rhel9cis_rule_6_2_10_enabled
  block:
    - name: 6.2.10 | Ensure local interactive user home directories are configured | Add warning
      loop: "{{ _rhel9cis_passwd }}"
      when:
        - user.uid >= 1000
        - user.uid <= 60000
        - user.dir is not defined or user.dir == ''
      ansible.builtin.set_fact:
        _rhel9cis_no_home_users: "{{ _rhel9cis_no_home_users | default([]) + [user.id] }}"
      loop_control:
        loop_var: user

    - name: 6.2.10 | Ensure local interactive user home directories are configured | Add warning
      when:
        - _rhel9cis_no_home_users | default([]) | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '6.2.10'
        _rhel9cis_warning_description: |
          The following users do not have a home directory.

          {{ _rhel9cis_no_home_users }}

          Please remediate this appropriately.

- name: |
    6.2.10 | Ensure local interactive user home directories are configured
    6.2.11 | Ensure local interactive users own their home directories
    6.2.12 | Ensure local interactive user home directories are mode 750 or more restrictive
  when:
    - rhel9cis_rule_6_2_10_enabled or
      rhel9cis_rule_6_2_11_enabled or
      rhel9cis_rule_6_2_12_enabled
  block:
    - name: |
        6.2.10 | Ensure local interactive user home directories are configured
        6.2.11 | Ensure local interactive users own their home directories
        6.2.12 | Ensure local interactive user home directories are mode 750 or more restrictive
      loop: "{{ _rhel9cis_passwd }}"
      when:
        - user.uid >= 1000
        - user.uid <= 60000
        - user.dir is defined
        - user.dir != ''
      become: true
      ansible.builtin.file:
        path: "{{ user.dir }}"
        state: directory
        owner: "{{ user.id }}"
        group: "{{ user.id }}"
        mode: '0750'
      loop_control:
        loop_var: user

- name: 6.2.13 | Ensure no local interactive user has .netrc files
  when:
    - rhel9cis_rule_6_2_13_enabled
  block:
    - name: 6.2.13 | Ensure no local interactive user has .netrc files
      loop: "{{ _rhel9cis_passwd }}"
      when:
        - user.uid >= 1000
        - user.uid <= 60000
        - user.dir is defined
        - user.dir != ''
      become: true
      ansible.builtin.file:
        path: "{{ user.dir }}/.netrc"
        state: absent
      loop_control:
        loop_var: user

- name: 6.2.14 | Ensure no local interactive user has .forward files
  when:
    - rhel9cis_rule_6_2_14_enabled
  block:
    - name: 6.2.14 | Ensure no local interactive user has .forward files
      loop: "{{ _rhel9cis_passwd }}"
      when:
        - user.uid >= 1000
        - user.uid <= 60000
        - user.dir is defined
        - user.dir != ''
      become: true
      ansible.builtin.file:
        path: "{{ user.dir }}/.forward"
        state: absent
      loop_control:
        loop_var: user

- name: 6.2.15 | Ensure no local interactive user has .rhosts files
  when:
    - rhel9cis_rule_6_2_15_enabled
  block:
    - name: 6.2.15 | Ensure no local interactive user has .rhosts files
      loop: "{{ _rhel9cis_passwd }}"
      when:
        - user.uid >= 1000
        - user.uid <= 60000
        - user.dir is defined
        - user.dir != ''
      become: true
      ansible.builtin.file:
        path: "{{ user.dir }}/.rhosts"
        state: absent
      loop_control:
        loop_var: user

- name: 6.2.16 | Ensure local interactive user dot files are not group or world writable
  loop: "{{ _rhel9cis_passwd }}"
  when:
    - rhel9cis_rule_6_2_16_enabled
    - user.uid >= 1000
    - user.uid <= 60000
    - user.dir is defined
    - user.dir != ''
  ansible.builtin.include_tasks: manage-dotfiles.yml
  loop_control:
    loop_var: user
