---
- name: 6.2.1.1 | Ensure journald service is enabled and active
  when:
    - rhel9cis_rule_6_2_1_1_enabled
  become: true
  ansible.builtin.systemd_service:
    name: systemd-journald.service
    enabled: true
    state: started
    masked: false

- name: 6.2.1.2 | Ensure journald log file access
  when:
    - rhel9cis_rule_6_2_1_2_enabled
  become: true
  block:
    - name: 6.2.1.2 | Ensure journald log file access | Check /etc/tmpfiles.d/systemd.conf
      ansible.builtin.stat:
        path: /etc/tmpfiles.d/systemd.conf
      register: _rhel9cis_systemd_conf

    - name: 6.2.1.2 | Ensure journald log file access | /usr/lib/tmpfiles.d/systemd.conf
      ansible.builtin.file:
        dest: /usr/lib/tmpfiles.d/systemd.conf
        owner: root
        group: root
        mode: '0640'
        state: file

    - name: 6.2.1.2 | Ensure journald log file access | /etc/tmpfiles.d/systemd.conf
      when:
        - _rhel9cis_systemd_conf.stat.exists
      ansible.builtin.file:
        dest: /etc/tmpfiles.d/systemd.conf
        owner: root
        group: root
        mode: '0640'
        state: file

- name: 6.2.1.3 | Ensure journald log file rotation is configured
  loop:
    - regexp: '^#?\s?SystemMaxUse='
      line: 'SystemMaxUse={{ rhel9cis_journald_systemmaxuse }}'
    - regexp: '^#?\s?SystemKeepFree='
      line: 'SystemKeepFree={{ rhel9cis_journald_systemkeepfree }}'
    - regexp: '^#?\s?RuntimeMaxUse='
      line: 'RuntimeMaxUse={{ rhel9cis_journald_runtimemaxuse }}'
    - regexp: '^#?\s?RuntimeKeepFree='
      line: 'RuntimeKeepFree={{ rhel9cis_journald_runtimekeepfree }}'
    - regexp: '^#?\s?MaxFileSec='
      line: 'MaxFileSec={{ rhel9cis_journald_maxfilesec }}'
  when:
    - rhel9cis_rule_6_2_1_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  notify:
    - _rhel9cis_restart_systemd-journald

- name: 6.2.1.4 | Ensure only one logging system is in use
  when:
    - rhel9cis_rule_6_2_1_4_enabled
  become: true
  block:
    - name: 6.2.1.4 | Ensure only one logging system is in use | rsyslog
      when:
        - rhel9cis_syslog == 'rsyslog'
      ansible.builtin.systemd_service:
        name: rsyslog.service
        state: started
        enabled: true
        masked: false

    - name: 6.2.1.4 | Ensure only one logging system is in use | journald
      when:
        - rhel9cis_syslog == 'journald'
      ansible.builtin.systemd_service:
        name: rsyslog.service
        state: stopped
        enabled: false
        masked: false


- name: 6.2.2.1.1 | Ensure systemd-journal-remote is installed
  when:
    - rhel9cis_rule_6_2_2_1_1_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.dnf:
    name:
      - systemd-journal-remote
    state: present

- name: 6.2.2.1.2 | Ensure systemd-journal-upload authentication is configured
  loop:
    - regexp: '^#?\s?URL='
      line: 'URL={{ rhel9cis_remote_log_server }}'
    - regexp: '^#?\s?ServerKeyFile='
      line: 'ServerKeyFile={{ rhel9cis_journal_server_key_file }}'
    - regexp: '^#?\s?ServerCertificateFile='
      line: 'ServerCertificateFile={{ rhel9cis_journal_server_cert_file }}'
    - regexp: '^#?\s?TrustedCertificateFile='
      line: 'TrustedCertificateFile={{ rhel9cis_journal_server_trusted_cert_file }}'
  when:
    - rhel9cis_rule_6_2_2_1_2_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journal-upload.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  notify:
    - _rhel9cis_restart_systemd-journal-upload

- name: 6.2.2.1.3 | Ensure systemd-journal-upload is enabled and active
  when:
    - rhel9cis_rule_6_2_2_1_3_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.systemd_service:
    name: systemd-journal-upload.service
    enabled: true
    state: started

- name: 6.2.2.1.4 | Ensure systemd-journal-remote service is not in use
  when:
    - rhel9cis_rule_6_2_2_1_4_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  block:
    - name: 6.2.2.1.4 | Ensure systemd-journal-remote service is not in use | systemd-journal-remote.service
      ansible.builtin.systemd_service:
        name: systemd-journal-remote.service
        enabled: false
        state: stopped

    - name: 6.2.2.1.4 | Ensure systemd-journal-remote service is not in use | systemd-journal-remote.socket
      ansible.builtin.systemd_service:
        name: systemd-journal-remote.socket
        enabled: false
        state: stopped

- name: 6.2.2.2 | Ensure journald is not configured to send logs to rsyslog
  when:
    - rhel9cis_rule_6_2_2_2_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/journald.conf
    regexp: '^#?\s?ForwardToSyslog='
    replace: 'ForwardToSyslog=no'
  notify:
    - _rhel9cis_restart_systemd-journald

- name: 6.2.2.3 | Ensure journald Compress is configured
  when:
    - rhel9cis_rule_6_2_2_3_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?\s?Compress='
    line: 'Compress=yes'
  notify:
    - _rhel9cis_restart_systemd-journald

- name: 6.2.2.4 | Ensure journald Storage is configured
  when:
    - rhel9cis_rule_6_2_2_4_enabled
    - rhel9cis_syslog == 'journald'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?\s?Storage='
    line: 'Storage=persistent'
  notify:
    - _rhel9cis_restart_systemd-journald

- name: 6.2.3.1 | Ensure rsyslog is installed
  when:
    - rhel9cis_rule_6_2_3_1_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.dnf:
    name:
      - rsyslog
    state: present

- name: 6.2.3.2 | Ensure rsyslog service is enabled and active
  when:
    - rhel9cis_rule_6_2_3_2_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.systemd_service:
    name: rsyslog.service
    enabled: true

- name: 6.2.3.3 | Ensure journald is configured to send logs to rsyslog
  when:
    - rhel9cis_rule_6_2_3_3_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?\s?ForwardToSyslog='
    line: 'ForwardToSyslog=yes'
    state: present
  notify:
    - _rhel9cis_restart_systemd-journald

- name: 6.2.3.4 | Ensure rsyslog default file permissions are configured
  when:
    - rhel9cis_rule_6_2_3_4_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^#?\s?\$FileCreateMode'
    line: '$FileCreateMode 0640'
    owner: root
    group: root
    mode: '0644'
  notify:
    - _rhel9cis_restart_rsyslog

- name: 6.2.3.5 | Ensure logging is configured
  when:
    - rhel9cis_rule_6_2_3_5_enabled
  ansible.builtin.include_tasks: ../add-warning.yml
  vars:
    _rhel9cis_warning_rule: '6.2.3.5'
    _rhel9cis_warning_description: This cannot be automated.  Please ensure the logging is configured as required.

- name: 6.2.3.6 | Ensure rsyslog is configured to send logs to a remote log host
  when:
    - rhel9cis_rule_6_2_3_6_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.blockinfile:
    path: /etc/rsyslog.conf
    state: present
    block: |
      *.* @@{{ rhel9cis_remote_log_server }}
    insertafter: EOF
  notify:
    - _rhel9cis_restart_rsyslog

- name: 6.2.3.7 | Ensure rsyslog is not configured to receive logs from a remote client
  loop:
    - '^(\$ModLoad imtcp)'
    - '^(\$InputTCPServerRun)'
    - '^(module\(load="imtcp"\))'
    - '^(input\(type="imtcp")'
  when:
    - rhel9cis_rule_6_2_3_7_enabled
    - rhel9cis_syslog == 'rsyslog'
  become: true
  ansible.builtin.replace:
    path: /etc/rsyslog.conf
    regexp: '({{ item }})'
    replace: '#\1'
  notify:
    - _rhel9cis_restart_rsyslog

- name: 6.2.3.8 | Ensure rsyslog logrotate is configured
  when:
    - rhel9cis_rule_6_2_3_8_enabled
    - rhel9cis_syslog == 'rsyslog'
  block:
    - name: 6.2.3.8 | Ensure rsyslog logrotate is configured | Get /etc/logrotate.d/* files
      become: true
      ansible.builtin.find:
        paths: 
          - /etc/logrotate.d
        file_type: file
        recurse: true
      register: _rhel9cis_logrotate_d

    - name: 6.2.3.8 | Ensure rsyslog logrotate is configured | /etc/logrotate.conf
      become: true
      ansible.builtin.replace:
        path: /etc/logrotate.conf
        regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
        replace: "\\1{{ rhel9cis_logrotate_frequency }}"
    
    - name: 6.2.3.8 | Ensure rsyslog logrotate is configured | /etc/logrotate.d/*
      loop: "{{ _rhel9cis_logrotate_d.files }}"
      become: true
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
        replace: "\\1{{ rhel9cis_logrotate_frequency }}"
      loop_control:
        label: "{{ item.path }}"

    - name: 6.2.3.8 | Ensure rsyslog logrotate is configured | Add warning
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '6.2.3.8'
        _rhel9cis_warning_description: "This cannot be fully automated. Please ensure logrotate is configured as required for all log types."

- name: 6.2.4.1 | Ensure all logfiles have appropriate access configured
  when:
    - rhel9cis_rule_6_2_4_1_enabled
  become: true
  block:
    - name: 6.2.4.1 | Ensure all logfiles have appropriate access configured | Get list of log files
      ansible.builtin.find:
        paths: 
          - /var/log
        file_type: file
        recurse: true
      register: _rhel9cis_log_files

    - name: 6.2.4.1 | Ensure all logfiles have appropriate access configured | Set permissions
      loop: "{{ _rhel9cis_log_files.files }}"
      when:
        - item.path != '/var/log/btmp'
        - item.path != '/var/log/utmp'
        - item.path != '/var/log/wtmp'
        - item.path != '/var/log/lastlog'
        - item.path != '/var/log/chrony/measurements.log'
        - item.path != '/var/log/chrony/tracking.log'
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: 'u=rw,g-wx,o-rwx'
      loop_control:
        label: "{{ item.path }}"
      tags:
        - always
        - molecule-idempotence-notest
