---
- name: 6.3.1.1 | Ensure audit is installed
  when:
    - rhel9cis_rule_6_3_1_1_enabled
    - rhel9cis_rule_6_3_1_1_force or _rhel9cis_level2
  become: true
  ansible.builtin.dnf:
    name:
      - audit
    state: present

- name: 6.3.1.2 | Ensure auditing for processes that start prior to auditd is enabled
  when:
    - rhel9cis_rule_6_3_1_2_enabled
    - rhel9cis_rule_6_3_1_2_force or _rhel9cis_level2
  become: true
  block:
    - name: 6.3.1.2 | Ensure auditing for processes that start prior to auditd is enabled | Get GRUB_CMDLINE_LINUX # noqa risky-shell-pipe
      check_mode: false
      ansible.builtin.shell: |
        grep 'GRUB_CMDLINE_LINUX=' /etc/default/grub | sed 's/.$//'
      changed_when: false
      failed_when: false
      register: _rhel9cis_grub_cmdline_linux

    - name: 6.3.1.2 | Ensure auditing for processes that start prior to auditd is enabled | Replace existing setting
      when:
        - "'audit=' in _rhel9cis_grub_cmdline_linux.stdout"
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: 'audit=\d'
        replace: 'audit=1'
      notify:
        - _rhel9cis_grub2-mkconfig

    - name: 6.3.1.2 | Ensure auditing for processes that start prior to auditd is enabled | Add audit setting if missing
      when:
        - "'audit=' not in _rhel9cis_grub_cmdline_linux.stdout"
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: '{{ _rhel9cis_grub_cmdline_linux.stdout }} audit=1"'
      notify:
        - _rhel9cis_grub2-mkconfig

- name: 6.3.1.3 | Ensure audit_backlog_limit is sufficient
  when:
    - rhel9cis_rule_6_3_1_3_enabled
    - rhel9cis_rule_6_3_1_3_force or _rhel9cis_level2
  block:
    - name: 6.3.1.3 | Ensure audit_backlog_limit is sufficient | Get GRUB_CMDLINE_LINUX # noqa risky-shell-pipe
      become: true
      check_mode: false
      ansible.builtin.shell: |
        grep 'GRUB_CMDLINE_LINUX=' /etc/default/grub | sed 's/.$//'
      changed_when: false
      failed_when: false
      register: _rhel9cis_grub_cmdline_linux

    - name: 6.3.1.3 | Ensure audit_backlog_limit is sufficient | Replace existing setting
      when:
        - "'audit_backlog_limit=' in _rhel9cis_grub_cmdline_linux.stdout"
      become: true
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: 'audit_backlog_limit=\d+'
        replace: 'audit_backlog_limit={{ rhel9cis_audit_backlog_limit }}'
      notify:
        - _rhel9cis_grub2-mkconfig

    - name: 6.3.1.3 | Ensure audit_backlog_limit is sufficient | Add audit setting if missing
      when:
        - "'audit_backlog_limit=' not in _rhel9cis_grub_cmdline_linux.stdout"
      become: true
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: '{{ _rhel9cis_grub_cmdline_linux.stdout }} audit_backlog_limit={{ rhel9cis_audit_backlog_limit }}"'
      notify:
        - _rhel9cis_grub2-mkconfig

- name: 6.3.1.4 | Ensure auditd service is enabled
  when:
    - rhel9cis_rule_6_3_1_4_enabled
    - rhel9cis_rule_6_3_1_4_force or _rhel9cis_level2
  become: true
  ansible.builtin.systemd_service:
    name: auditd.service
    enabled: true
  notify:
    - _rhel9cis_reboot

- name: 6.3.2.1 | Ensure audit log storage size is configured
  when:
    - rhel9cis_rule_6_3_2_1_enabled
    - rhel9cis_rule_6_3_2_1_force or _rhel9cis_level2
  become: true
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^#?\s?max_log_file\s?='
    line: "max_log_file = {{ rhel9cis_auditd_max_log_file }}"
  notify:
    - _rhel9cis_reboot

- name: 6.3.2.2 | Ensure audit logs are not automatically deleted
  when:
    - rhel9cis_rule_6_3_2_2_enabled
    - rhel9cis_rule_6_3_2_2_force or _rhel9cis_level2
  become: true
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^#?\s?max_log_file_action\s?='
    line: "max_log_file_action = keep_logs"
  notify:
    - _rhel9cis_reboot

- name: 6.3.2.3 | Ensure system is disabled when audit logs are full
  loop:
    - name: disk_full_action
      regexp: '^#?\s?disk_full_action\s?='
      line: "disk_full_action = {{ rhel9cis_auditd_disk_full_action }}"
    - name: disk_error_action
      regexp: '^#?\s?disk_error_action\s?='
      line: "disk_error_action = {{ rhel9cis_auditd_disk_error_action }}"
  when:
    - rhel9cis_rule_6_3_2_3_enabled
    - rhel9cis_rule_6_3_2_3_force or _rhel9cis_level2
  become: true
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify:
    - _rhel9cis_reboot
  loop_control:
    label: "{{ item.name }}"

- name: 6.3.3.6 | Ensure use of privileged commands are collected # noqa risky-shell-pipe
  when:
    - rhel9cis_rule_6_3_3_6_enabled
    - rhel9cis_rule_6_3_3_6_force or _rhel9cis_level2
  become: true
  ansible.builtin.shell: |
    for i in  $(df | grep '^/dev' | awk '{ print $NF }'); do find $i -xdev -type f -perm /6000 2>/dev/null; done
  changed_when: false
  failed_when: false
  register: _rhel9cis_privileged_processes

- name: |
    6.3.3.1 | Ensure changes to system administration scope (sudoers) is collected
    6.3.3.2 | Ensure actions as another user are always logged
    6.3.3.3 | Ensure events that modify the sudo log file are collected
    6.3.3.4 | Ensure events that modify date and time information are collected
    6.3.3.5 | Ensure events that modify the system's network environment are collected
    6.3.3.6 | Ensure use of privileged commands are collected
    6.3.3.7 | Ensure unsuccessful file access attempts are collected
    6.3.3.8 | Ensure events that modify user/group information are collected
    6.3.3.9 | Ensure discretionary access control permission modification events are collected
    6.3.3.10 | Ensure successful file system mounts are collected
    6.3.3.11 | Ensure session initiation information is collected
    6.3.3.12 | Ensure login and logout events are collected
    6.3.3.13 | Ensure file deletion events by users are collected
    6.3.3.14 | Ensure events that modify the system's Mandatory Access Controls are collected
    6.3.3.15 | Ensure successful and unsuccessful attempts to use the chcon command are recorded
    6.3.3.16 | Ensure successful and unsuccessful attempts to use the setfacl command are recorded
    6.3.3.17 | Ensure successful and unsuccessful attempts to use the chacl command are recorded
    6.3.3.18 | Ensure successful and unsuccessful attempts to use the usermod command are recorded
    6.3.3.19 | Ensure kernel module loading unloading and modification is collected
    6.3.3.20 | Ensure the audit configuration is immutable
  when:
    - (rhel9cis_rule_6_3_3_1_enabled and
      (rhel9cis_rule_6_3_3_1_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_2_enabled and
      (rhel9cis_rule_6_3_3_2_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_3_enabled and
      (rhel9cis_rule_6_3_3_3_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_4_enabled and
      (rhel9cis_rule_6_3_3_4_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_5_enabled and
      (rhel9cis_rule_6_3_3_5_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_6_enabled and
      (rhel9cis_rule_6_3_3_6_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_7_enabled and
      (rhel9cis_rule_6_3_3_7_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_8_enabled and
      (rhel9cis_rule_6_3_3_8_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_9_enabled and
      (rhel9cis_rule_6_3_3_9_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_10_enabled and
      (rhel9cis_rule_6_3_3_10_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_11_enabled and
      (rhel9cis_rule_6_3_3_11_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_12_enabled and
      (rhel9cis_rule_6_3_3_12_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_13_enabled and
      (rhel9cis_rule_6_3_3_13_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_14_enabled and
      (rhel9cis_rule_6_3_3_14_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_15_enabled and
      (rhel9cis_rule_6_3_3_15_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_16_enabled and
      (rhel9cis_rule_6_3_3_16_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_17_enabled and
      (rhel9cis_rule_6_3_3_17_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_18_enabled and
      (rhel9cis_rule_6_3_3_18_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_19_enabled and
      (rhel9cis_rule_6_3_3_19_force or _rhel9cis_level2)) or
      (rhel9cis_rule_6_3_3_20_enabled and
      (rhel9cis_rule_6_3_3_20_force or _rhel9cis_level2))
  become: true
  ansible.builtin.template:
    src: 99-auditd.rules.j2
    dest: /etc/audit/rules.d/99-audit.rules
    owner: root
    group: root
    mode: '0600'
  notify:
    - _rhel9cis_auditd_rules_reload

- name: 6.3.3.21 | Ensure the running and on disk configuration is the same
  when:
    - rhel9cis_rule_6_3_3_21_enabled
    - rhel9cis_rule_6_3_3_21_force or _rhel9cis_level2
  become: true
  ansible.builtin.command: augenrules --check
  changed_when: "not 'No change' in _rhel9cis_augenrules_check.stdout"
  notify:
    - _rhel9cis_auditd_rules_reload
  register: _rhel9cis_augenrules_check

- name: 6.3.4.1 | Ensure the audit log directory is 0750 or more restrictive
  when:
    - rhel9cis_rule_6_3_4_1_enabled
    - rhel9cis_rule_6_3_4_1_force or _rhel9cis_level2
  become: true
  ansible.builtin.file:
    path: /var/log/audit
    mode: u=rwx,g-w,o-rwx

- name: 6.3.4.2 | Ensure audit log files are mode 0640 or less permissive
  when:
    - rhel9cis_rule_6_3_4_2_enabled
    - rhel9cis_rule_6_3_4_2_force or _rhel9cis_level2
  become: true
  block:
    - name: 6.3.4.2 | Ensure audit log files are mode 0640 or less permissive | Get /var/log/audit/* files
      ansible.builtin.find:
        paths:
          - /var/log/audit
        file_type: file
        recurse: true
      register: _rhel9cis_audit_log_files

    - name: 6.3.4.2 | Ensure audit log files are mode 0640 or less permissive | Set permission
      loop: "{{ _rhel9cis_audit_log_files.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: 'u=rw,g-wx,o-rwx'
      loop_control:
        label: "{{ item.path }}"
      tags:
        - always
        - molecule-idempotence-notest

- name: 6.3.4.3 | Ensure only authorized users own audit log files
  when:
    - rhel9cis_rule_6_3_4_3_enabled
    - rhel9cis_rule_6_3_4_3_force or _rhel9cis_level2
  become: true
  block:
    - name: 6.3.4.3 | Ensure only authorized users own audit log files | Get /var/log/audit/* files
      ansible.builtin.find:
        paths:
          - /var/log/audit
        file_type: file
        recurse: true
      register: _rhel9cis_audit_log_files

    - name: 6.3.4.3 | Ensure only authorized users own audit log files | Set permission
      loop: "{{ _rhel9cis_audit_log_files.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: root
      loop_control:
        label: "{{ item.path }}"

- name: 6.3.4.4 | Ensure only authorized groups are assigned ownership of audit log files
  when:
    - rhel9cis_rule_6_3_4_4_enabled
    - rhel9cis_rule_6_3_4_4_force or _rhel9cis_level2
  become: true
  block:
    - name: 6.3.4.4 | Ensure only authorized groups are assigned ownership of audit log files | Get /var/log/audit/* files
      ansible.builtin.find:
        paths:
          - /var/log/audit
        file_type: file
        recurse: true
      register: _rhel9cis_audit_log_files

    - name: 6.3.4.4 | Ensure only authorized groups are assigned ownership of audit log files | Set permission
      loop: "{{ _rhel9cis_audit_log_files.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        group: root
      loop_control:
        label: "{{ item.path }}"

- name: 6.3.4.5 | Ensure audit configuration files are 640 or more restrictive
  when:
    - rhel9cis_rule_6_3_4_5_enabled
    - rhel9cis_rule_6_3_4_5_force or _rhel9cis_level2
  become: true
  block:
    - name: 6.3.4.5 | Ensure audit configuration files are 640 or more restrictive | Get /etc/audit/* files
      ansible.builtin.find:
        paths:
          - /etc/audit
        file_type: file
        recurse: true
      register: _rhel9cis_audit_conf_files
    
    - name: 6.3.4.5 | Ensure audit configuration files are 640 or more restrictive | Set permissions
      loop: "{{ _rhel9cis_audit_conf_files.files }}"
      when:
        - item.path != '/etc/audit/rules.d/99-audit.rules'
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: 'u=rw,g-wx,o-rwx'
      loop_control:
        label: "{{ item.path }}"

- name: 6.3.4.6 | Ensure audit configuration files are owned by root
  when:
    - rhel9cis_rule_6_3_4_6_enabled
    - rhel9cis_rule_6_3_4_6_force or _rhel9cis_level2
  become: true
  block:
    - name: 6.3.4.6 | Ensure audit configuration files are owned by root | Get /etc/audit/* files
      ansible.builtin.find:
        paths:
          - /etc/audit
        file_type: file
        recurse: true
      register: _rhel9cis_audit_conf_files
    
    - name: 6.3.4.6 | Ensure audit configuration files are owned by root | Set permissions
      loop: "{{ _rhel9cis_audit_conf_files.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: root
      loop_control:
        label: "{{ item.path }}"

- name: 6.3.4.7 | Ensure audit configuration files belong to group root
  when:
    - rhel9cis_rule_6_3_4_7_enabled
    - rhel9cis_rule_6_3_4_7_force or _rhel9cis_level2
  become: true
  block:
    - name: 6.3.4.7 | Ensure audit configuration files belong to group root | Get /etc/audit/* files
      ansible.builtin.find:
        paths:
          - /etc/audit
        file_type: file
        recurse: true
      register: _rhel9cis_audit_conf_files
    
    - name: 6.3.4.7 | Ensure audit configuration files belong to group root | Set permissions
      loop: "{{ _rhel9cis_audit_conf_files.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        group: 'root'
      loop_control:
        label: "{{ item.path }}"

- name: 6.3.4.8 | Ensure audit tools are 755 or more restrictive
  loop:
    - /sbin/auditctl
    - /sbin/aureport
    - /sbin/ausearch
    - /sbin/autrace
    - /sbin/auditd
    - /sbin/augenrules
  when:
    - rhel9cis_rule_6_3_4_8_enabled
    - rhel9cis_rule_6_3_4_8_force or _rhel9cis_level2
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    mode: 'u=rwx,g-w,o-w'

- name: 6.3.4.9 | Ensure audit tools are owned by root
  loop:
    - /sbin/auditctl
    - /sbin/aureport
    - /sbin/ausearch
    - /sbin/autrace
    - /sbin/auditd
    - /sbin/augenrules
  when:
    - rhel9cis_rule_6_3_4_9_enabled
    - rhel9cis_rule_6_3_4_9_force or _rhel9cis_level2
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root

- name: 6.3.4.10 | Ensure audit tools belong to group root
  loop:
    - /sbin/auditctl
    - /sbin/aureport
    - /sbin/ausearch
    - /sbin/autrace
    - /sbin/auditd
    - /sbin/augenrules
  when:
    - rhel9cis_rule_6_3_4_10_enabled
    - rhel9cis_rule_6_3_4_10_force or _rhel9cis_level2
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    group: root
