---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: l1server
    box: jtarpley/rocky9_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel9_
    groups:
      - subjects
      - level1
      - servers
  - name: l2server
    box: jtarpley/rocky9_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel9_
    groups:
      - subjects
      - level2
      - servers
  - name: l1workstation
    box: jtarpley/rocky9_ws_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel9_
    groups:
      - subjects
      - level1
      - workstations
  - name: l2workstation
    box: jtarpley/rocky9_ws_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel9_
    groups:
      - subjects
      - level2
      - workstations
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        ansible_become_password: vagrant
        rhel9cis_bootloader_password: password
        rhel9cis_skip_reboot: false
        rhel9cis_remote_log_server: loghost.test.loc
        rhel9cis_afs_needed: false
        rhel9cis_ceph_needed: false
        rhel9cis_cifs_needed: false
        rhel9cis_exfat_needed: false
        rhel9cis_ext_needed: false
        rhel9cis_fscache_needed: false
        rhel9cis_gfs2_needed: false
        rhel9cis_nfs_common_needed: false
        rhel9cis_nfsd_needed: false
        rhel9cis_smbfs_common_needed: false
      level1:
        rhel9cis_level: 1
      level2:
        rhel9cis_level: 2
      servers:
        rhel9cis_machine_type: server
      workstations:
        rhel9cis_machine_type: workstation
verifier:
  name: ansible
