---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: server
    box: jtarpley/rocky9_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel9_
    groups:
      - subjects
  - name: workstation
    box: jtarpley/rocky9_ws_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel9_
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        ansible_become_password: vagrant
        rhel9cis_bootloader_password: password
        rhel9cis_skip_reboot: false
        rhel9cis_remote_log_server: loghost.test.loc
    host_vars:
      server:
        rhel9cis_machine_type: server
      workstation:
        rhel9cis_machine_type: workstation
verifier:
  name: ansible
