---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: rhel9
  description: This role applies the CIS Benchmark hardening steps on RHEL9-based machines.  It is based on the CIS Benchmark for RHEL 9, v2.0.0.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: EL
      versions:
        - '9'

collections:
  - ansible.posix
  - community.general

dependencies: []
