---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: server
    box: jtarpley/rocky8_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel8_
    groups:
      - subjects
  - name: workstation
    box: jtarpley/rocky8_ws_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel8_
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        ansible_become_password: vagrant
        rhel8cis_bootloader_password: password
        rhel8cis_skip_reboot: false
    host_vars:
      server:
        rhel8cis_machine_type: server
      workstation:
        rhel8cis_machine_type: workstation
verifier:
  name: ansible
