---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: l1server
    box: jtarpley/rocky8_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel8_
    groups:
      - subjects
      - level1
      - servers
  - name: l2server
    box: jtarpley/rocky8_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel8_
    groups:
      - subjects
      - level2
      - servers
  - name: l1workstation
    box: jtarpley/rocky8_ws_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel8_
    groups:
      - subjects
      - level1
      - workstations
  - name: l2workstation
    box: jtarpley/rocky8_ws_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_rhel8_
    groups:
      - subjects
      - level2
      - workstations
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        ansible_become_password: vagrant
        rhel8cis_bootloader_password: password
        rhel8cis_skip_reboot: false
      level1:
        rhel8cis_level: 1
      level2:
        rhel8cis_level: 2
      servers:
        rhel8cis_machine_type: server
      workstations:
        rhel8cis_machine_type: workstation
verifier:
  name: ansible
