---
- name: "18.9.24.1 | L1 | Ensure 'Enumeration policy for external devices incompatible with Kernel DMA Protection' is set to 'Enabled: Block All'"
  when:
    - w2019cis_rule_18_9_24_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Kernel DMA Protection
    name: DeviceEnumerationPolicy
    data: 0
    type: dword
