---
- name: "18.9.27.1 | L2 | Ensure 'Disallow copying of user input methods to the system account for sign-in' is set to 'Enabled'"
  when:
    - w2019cis_rule_18_9_27_1_enabled
    - w2019cis_rule_18_9_27_1_force or _w2019cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Control Panel\International
    name: BlockUserInputMethodsForSignIn
    data: 1
    type: dword
