---
- name: "18.9.7.2 | L1 | Ensure 'Prevent device metadata retrieval from the Internet' is set to 'Enabled'"
  when:
    - w2019cis_rule_18_9_7_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Device Metadata
    name: PreventDeviceMetadataFromNetwork
    data: 1
    type: dword
