---
- name: "18.9.26.1 | NG | Ensure 'Configures LSASS to run as a protected process' is set to 'Enabled: Enabled with UEFI Lock'"
  when:
    - w2019cis_rule_18_9_26_1_enabled
    - w2019cis_rule_18_9_26_1_force or _w2019cis_ngws
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Kernel DMA Protection
    name: DeviceEnumerationPolicy
    data: 0
    type: dword
