---
- name: "18.9.36.1 | L1 | Ensure 'Enable RPC Endpoint Mapper Client Authentication' is set to 'Enabled' | MS only"
  when:
    - w2019cis_rule_18_9_36_1_enabled
    - _w2019cis_standalone_or_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Rpc
    name: EnableAuthEpResolution
    data: 1
    type: dword
  notify:
    - _w2019cis_reboot_windows

- name: "18.9.36.2 | L2 | Ensure 'Restrict Unauthenticated RPC clients' is set to 'Enabled: Authenticated' | MS only"
  when:
    - w2019cis_rule_18_9_36_2_enabled
    - _w2019cis_standalone_or_member_server
    - w2019cis_rule_18_9_36_2_force or _w2019cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Rpc
    name: RestrictRemoteClients
    data: 1
    type: dword
  notify:
    - _w2019cis_reboot_windows
