---
- name: "17.3.1 | L1 | Ensure 'Audit PNP Activity' is set to include 'Success'"
  when:
    - w2022cis_rule_17_3_1_enabled
  block:
    - name: "17.3.1 | L1 | Ensure 'Audit PNP Activity' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9248-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_3_1_audit

    - name: "17.3.1 | L1 | Ensure 'Audit PNP Activity' is set to include 'Success'"
      when:
        - "'Success' not in _w2022cis_rule_17_3_1_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9248-69ae-11d9-bed3-505054503030}" /success:enable

- name: "17.3.2 | L1 | Ensure 'Audit Process Creation' is set to include 'Success'"
  when:
    - w2022cis_rule_17_3_2_enabled
  block:
    - name: "17.3.2 | L1 | Ensure 'Audit Process Creation' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce922b-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_3_2_audit

    - name: "17.3.2 | L1 | Ensure 'Audit Process Creation' is set to include 'Success'"
      when:
        - "'Success' not in _w2022cis_rule_17_3_2_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce922b-69ae-11d9-bed3-505054503030}" /success:enable
