---
- name: "17.5.1 | L1 | Ensure 'Audit Account Lockout' is set to include 'Failure'"
  when:
    - w2022cis_rule_17_5_1_enabled
  block:
    - name: "17.5.1 | L1 | Ensure 'Audit Account Lockout' is set to include 'Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9217-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_1_audit

    - name: "17.5.1 | L1 | Ensure 'Audit Account Lockout' is set to include 'Failure'"
      when:
        - "'Failure' not in _w2022cis_rule_17_5_1_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9217-69ae-11d9-bed3-505054503030}" /failure:enable

- name: "17.5.2 | L1 | Ensure 'Audit Group Membership' is set to include 'Success'"
  when:
    - w2022cis_rule_17_5_2_enabled
  block:
    - name: "17.5.2 | L1 | Ensure 'Audit Group Membership' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9249-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_2_audit

    - name: "17.5.2 | L1 | Ensure 'Audit Group Membership' is set to include 'Success'"
      when:
        - "'Success' not in _w2022cis_rule_17_5_2_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9249-69ae-11d9-bed3-505054503030}" /success:enable

- name: "17.5.3 | L1 | Ensure 'Audit Logoff' is set to include 'Success'"
  when:
    - w2022cis_rule_17_5_3_enabled
  block:
    - name: "17.5.3 | L1 | Ensure 'Audit Logoff' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9216-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_3_audit

    - name: "17.5.3 | L1 | Ensure 'Audit Logoff' is set to include 'Success'"
      when:
        - "'Success' not in _w2022cis_rule_17_5_3_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9216-69ae-11d9-bed3-505054503030}" /success:enable

- name: "17.5.4 | L1 | Ensure 'Audit Logon' is set to 'Success and Failure'"
  when:
    - w2022cis_rule_17_5_4_enabled
  block:
    - name: "17.5.4 | L1 | Ensure 'Audit Logon' is set to 'Success and Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9215-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_4_audit

    - name: "17.5.4 | L1 | Ensure 'Audit Logon' is set to 'Success and Failure' | Success"
      when:
        - "'Success' not in _w2022cis_rule_17_5_4_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9215-69ae-11d9-bed3-505054503030}" /success:enable

    - name: "17.5.4 | L1 | Ensure 'Audit Logon' is set to 'Success and Failure' | Failure"
      when:
        - "'Failure' not in _w2022cis_rule_17_5_4_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9215-69ae-11d9-bed3-505054503030}" /failure:enable

- name: "17.5.5 | L1 | Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure'"
  when:
    - w2022cis_rule_17_5_5_enabled
  block:
    - name: "17.5.5 | L1 | Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce921c-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_5_audit

    - name: "17.5.5 | L1 | Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure' | Success"
      when:
        - "'Success' not in _w2022cis_rule_17_5_5_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce921c-69ae-11d9-bed3-505054503030}" /success:enable

    - name: "17.5.5 | L1 | Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure' | Failure"
      when:
        - "'Failure' not in _w2022cis_rule_17_5_5_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce921c-69ae-11d9-bed3-505054503030}" /failure:enable

- name: "17.5.6 | L1 | Ensure 'Audit Special Logon' is set to include 'Success'"
  when:
    - w2022cis_rule_17_5_6_enabled
  block:
    - name: "17.5.6 | L1 | Ensure 'Audit Special Logon' is set to include 'Success'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce921b-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_5_6_audit

    - name: "17.5.6 | L1 | Ensure 'Audit Special Logon' is set to include 'Success'"
      when:
        - "'Success' not in _w2022cis_rule_17_5_6_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce921b-69ae-11d9-bed3-505054503030}" /success:enable
