---
- name: "17.6.1 | L1 | Ensure 'Audit Detailed File Share' is set to include 'Failure'"
  when:
    - w2022cis_rule_17_6_1_enabled
  block:
    - name: "17.6.1 | L1 | Ensure 'Audit Detailed File Share' is set to include 'Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9244-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_6_1_audit

    - name: "17.6.1 | L1 | Ensure 'Audit Detailed File Share' is set to include 'Failure'"
      when:
        - "'Failure' not in _w2022cis_rule_17_6_1_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9244-69ae-11d9-bed3-505054503030}" /failure:enable

- name: "17.6.2 | L1 | Ensure 'Audit File Share' is set to 'Success and Failure'"
  when:
    - w2022cis_rule_17_6_2_enabled
  block:
    - name: "17.6.2 | L1 | Ensure 'Audit File Share' is set to 'Success and Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9224-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_6_2_audit

    - name: "17.6.2 | L1 | Ensure 'Audit File Share' is set to 'Success and Failure' | Success"
      when:
        - "'Success' not in _w2022cis_rule_17_6_2_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9224-69ae-11d9-bed3-505054503030}" /success:enable

    - name: "17.6.2 | L1 | Ensure 'Audit File Share' is set to 'Success and Failure' | Failure"
      when:
        - "'Failure' not in _w2022cis_rule_17_6_2_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9224-69ae-11d9-bed3-505054503030}" /failure:enable

- name: "17.6.3 | L1 | Ensure 'Audit Other Object Access Events' is set to 'Success and Failure'"
  when:
    - w2022cis_rule_17_6_3_enabled
  block:
    - name: "17.6.3 | L1 | Ensure 'Audit Other Object Access Events' is set to 'Success and Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9227-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_6_3_audit

    - name: "17.6.3 | L1 | Ensure 'Audit Other Object Access Events' is set to 'Success and Failure'"
      when:
        - "'Success' not in _w2022cis_rule_17_6_3_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9227-69ae-11d9-bed3-505054503030}" /success:enable

    - name: "17.6.3 | L1 | Ensure 'Audit Other Object Access Events' is set to 'Success and Failure'"
      when:
        - "'Failure' not in _w2022cis_rule_17_6_3_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9227-69ae-11d9-bed3-505054503030}" /failure:enable

- name: "17.6.4 | L1 | Ensure 'Audit Removable Storage' is set to 'Success and Failure'"
  when:
    - w2022cis_rule_17_6_4_enabled
  block:
    - name: "17.6.4 | L1 | Ensure 'Audit Removable Storage' is set to 'Success and Failure'"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9245-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      register: _w2022cis_rule_17_6_4_audit

    - name: "17.6.4 | L1 | Ensure 'Audit Removable Storage' is set to 'Success and Failure' | Success"
      when:
        - "'Success' not in _w2022cis_rule_17_6_4_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9245-69ae-11d9-bed3-505054503030}" /success:enable

    - name: "17.6.4 | L1 | Ensure 'Audit Removable Storage' is set to 'Success and Failure' | Failure"
      when:
        - "'Failure' not in _w2022cis_rule_17_6_4_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9245-69ae-11d9-bed3-505054503030}" /failure:enable
