---
- name: 1.5.1 | Ensure core dump storage is disabled
  when:
    - rhel9cis_rule_1_5_1_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: '^#?Storage='
    line: 'Storage=none'

- name: 1.5.2 | Ensure core dump backtraces are disabled
  when:
    - rhel9cis_rule_1_5_2_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: '^#?ProcessSizeMax='
    line: 'ProcessSizeMax=0'

- name: 1.5.3 | Ensure address space layout randomization (ASLR) is enabled
  when:
    - rhel9cis_rule_1_5_3_enabled
  become: true
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: '2'
    state: present
    sysctl_set: true
