---
- name: 1.6.1.1 | Ensure SELinux is installed
  when:
    - rhel9cis_rule_1_6_1_1_enabled
  become: true
  ansible.builtin.dnf:
    name:
      - libselinux
    state: present

- name: 1.6.1.2 | Ensure SELinux is not disabled in bootloader configuration
  when:
    - rhel9cis_rule_1_6_1_2_enabled
  become: true
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: '(selinux|enforcing)\s*=\s*0\s*'
    replace: ''
  notify:
    - _rhel9cis_grub2-mkconfig

- name: |
    1.6.1.3 | Ensure SELinux policy is configured
    1.6.1.4 | Ensure the SELinux mode is not disabled
    1.6.1.5 | Ensure the SELinux state is enforcing
  when:
    - rhel9cis_rule_1_6_1_3_enabled or
      rhel9cis_rule_1_6_1_4_enabled or
      (rhel9cis_rule_1_6_1_5_enabled and
      (_rhel9cis_level2 or rhel9cis_rule_1_6_1_5_force))
  become: true
  ansible.posix.selinux:
    conf: /etc/selinux/config
    policy: "{{ rhel9cis_selinux_policy }}"
    state: "{{ rhel9cis_selinux_mode }}"

- name: 1.6.1.6 | Ensure no unconfined services exist
  when:
    - rhel9cis_rule_1_6_1_6_enabled
  block:
    - name: 1.6.1.6 | Ensure no unconfined services exist | Get list of unconfined services
      become: true
      ansible.builtin.shell: |
        ps -eZ | grep unconfined_service_t | egrep -vw "tr|ps|egrep|bash|awk" | tr ':' ' ' | awk '{ print $NF }'
      changed_when: false
      register: _rhel9cis_unconfined_services
      tags:
        - always
        - skip_ansible_lint

    - name: 1.6.1.6 | Ensure no unconfined services exist | Generate warning
      when:
        - _rhel9cis_unconfined_services.stdout | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel9cis_warning_rule: '1.6.1.6'
        _rhel9cis_warning_description: | 
          The following unconfined services are running:
          
          {{ _rhel9cis_unconfined_services.stdout_lines | join("\n") }}

- name: 1.6.1.7 | Ensure SETroubleshoot is not installed
  when:
    - rhel9cis_rule_1_6_1_7_enabled
    - _rhel9cis_server
  become: true
  ansible.builtin.dnf:
    name:
      - setroubleshoot
    state: absent

- name: 1.6.1.8 | Ensure the MCS Translation Service (mcstrans) is not installed
  when:
    - rhel9cis_rule_1_6_1_8_enabled
  become: true
  ansible.builtin.dnf:
    name:
      - mcstrans
    state: absent
