---
- name: 1.6.x | Get system wide crypto policy
  when:
    - rhel9cis_rule_1_6_1_enabled or
      rhel9cis_rule_1_6_3_enabled or
      rhel9cis_rule_1_6_4_enabled or
      rhel9cis_rule_1_6_5_enabled or
      rhel9cis_rule_1_6_6_enabled or
      rhel9cis_rule_1_6_7_enabled
  become: true
  ansible.builtin.command: update-crypto-policies --show
  changed_when: false
  register: _rhel9cis_crypto_policy

- name: 1.6.2 | Ensure system wide crypto policy is not set in sshd configuration
  when:
    - rhel9cis_rule_1_6_2_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/sshd
    regexp: '^#?CRYPTO_POLICY'
    state: absent
  notify:
    - _rhel9cis_restart_sshd

- name: 1.6.3 | Ensure system wide crypto policy disables sha1 hash and signature support
  when:
    - rhel9cis_rule_1_6_3_enabled
  become: true
  ansible.builtin.copy:
    content: |
      hash = -SHA1
      sign = -*-SHA1
      sha1_in_certs = 0
    dest: /etc/crypto-policies/policies/modules/NO-SHA1.pmod
    owner: root
    group: root
    mode: '0644'

- name: 1.6.4 | Ensure system wide crypto policy disables macs less than 128 bits
  when:
    - rhel9cis_rule_1_6_4_enabled
  become: true
  ansible.builtin.copy:
    content: mac = -*-64*
    dest: /etc/crypto-policies/policies/modules/NO-WEAKMAC.pmod
    owner: root
    group: root
    mode: '0644'

- name: 1.6.5 | Ensure system wide crypto policy disables cbc for ssh
  when:
    - rhel9cis_rule_1_6_5_enabled
  become: true
  ansible.builtin.copy:
    content: cipher@SSH = -*-CBC
    dest: /etc/crypto-policies/policies/modules/NO-SSHCBC.pmod
    owner: root
    group: root
    mode: '0644'

- name: 1.6.6 | Ensure system wide crypto policy disables chacha20-poly1305 for ssh
  when:
    - rhel9cis_rule_1_6_6_enabled
  become: true
  ansible.builtin.copy:
    content: cipher@SSH = -CHACHA20-POLY1305
    dest: /etc/crypto-policies/policies/modules/NO-SSHCHACHA20.pmod
    owner: root
    group: root
    mode: '0644'

- name: 1.6.7 | Ensure system wide crypto policy disables EtM for ssh
  when:
    - rhel9cis_rule_1_6_7_enabled
  become: true
  ansible.builtin.copy:
    content: etm@SSH = DISABLE_ETM
    dest: /etc/crypto-policies/policies/modules/NO-SSHETM.pmod
    owner: root
    group: root
    mode: '0644'

- name: |
    1.6.1 | Ensure system wide crypto policy is not set to legacy
    1.6.3 | Ensure system wide crypto policy disables sha1 hash and signature support
    1.6.4 | Ensure system wide crypto policy disables macs less than 128 bits
    1.6.5 | Ensure system wide crypto policy disables cbc for ssh
    1.6.6 | Ensure system wide crypto policy disables chacha20-poly1305 for ssh
    1.6.7 | Ensure system wide crypto policy disables EtM for ssh
  when:
    - rhel9cis_rule_1_6_1_enabled or
      rhel9cis_rule_1_6_3_enabled or
      rhel9cis_rule_1_6_4_enabled or
      rhel9cis_rule_1_6_5_enabled or
      rhel9cis_rule_1_6_6_enabled or
      rhel9cis_rule_1_6_7_enabled
    - _rhel9cis_expected_crypto_policy != _rhel9cis_crypto_policy.stdout
  become: true
  ansible.builtin.command: "update-crypto-policies --set {{ _rhel9cis_expected_crypto_policy }}"
  changed_when: true
  notify:
    - _rhel9cis_reboot
