---
- name: 1.8.1 | Ensure GNOME Display Manager is removed
  when:
    - _rhel9cis_server
    - rhel9cis_rule_1_8_1_enabled
    - _rhel9cis_level2 or rhel9cis_rule_1_8_1_force
  become: true
  ansible.builtin.dnf:
    name:
      - gdm
    state: absent

# 1.8.2-10 not implemented yet
