---
- name: Execute the 1.1.x tasks
  ansible.builtin.import_tasks: 1.1/main.yml

- name: Execute the 1.2.x tasks
  ansible.builtin.import_tasks: 1.2/main.yml

- name: Execute the 1.3.x tasks
  ansible.builtin.import_tasks: 1.3.x.yml

- name: Execute the 1.4.x tasks
  ansible.builtin.import_tasks: 1.4.x.yml

- name: Execute the 1.5.x tasks
  ansible.builtin.import_tasks: 1.5.x.yml

- name: Execute the 1.6.x tasks
  ansible.builtin.import_tasks: 1.6.x.yml

- name: Execute the 1.7.x tasks
  ansible.builtin.import_tasks: 1.7.x.yml

- name: Execute the 1.8.x tasks
  ansible.builtin.import_tasks: 1.8.x.yml

- name: 1.9 | Ensure updates, patches, and additional security software are installed
  when:
    - rhel9cis_rule_1_9_enabled
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
    update_only: true
  notify:
    - _rhel9cis_reboot

- name: 1.10 | Ensure system wide crypto policy is not set to legacy
  become: true
  ansible.builtin.command: update-crypto-policies --show
  changed_when: false
  register: _rhel9cis_crypto_policy

- name: 1.10 | Ensure system wide crypto policy is not set to legacy
  when:
    - _rhel9cis_expected_crypto_policy != _rhel9cis_crypto_policy.stdout
  become: true
  ansible.builtin.command: "update-crypto-policies --set {{ _rhel9cis_expected_crypto_policy }}"
  changed_when: true
  notify:
    - _rhel9cis_reboot
