---
- name: 3.1.1 | Ensure IPv6 status is identified
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6    
  when:
    - rhel9cis_rule_3_1_1_enabled
    - not rhel9cis_ipv6_needed
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true

- name: 3.1.2 | Ensure wireless interfaces are disabled
  when:
    - rhel9cis_rule_3_1_2_enabled
    - _rhel9cis_server
  become: true
  block:
    - name: 3.1.2 | Ensure wireless interfaces are disabled | Check if wifi is enabled
      ansible.builtin.command: nmcli radio wifi
      changed_when: false
      failed_when: false
      register: _rhel9cis_wifi_status

    - name: 3.1.2 | Ensure wireless interfaces are disabled | Disable wifi
      when:
        - _rhel9cis_wifi_status.stdout.find('enabled') != -1
      ansible.builtin.command: nmcli radio all off
      changed_when: true
      failed_when: false

- name: 3.1.3 | Ensure TIPC is disabled
  when:
    - rhel9cis_rule_3_1_3_enabled
    - _rhel9cis_level2 or rhel9cis_rule_3_1_3_force
  become: true
  block:
    - name: 3.1.3 | Ensure TIPC is disabled | Prevent modprobe install
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/tipc.conf
        regexp: "^(#)?install tipc"
        line: install tipc /bin/false
        create: true
        owner: root
        group: root
        mode: '0600'

    - name: 3.1.3 | Ensure TIPC is disabled | Add modprobe blacklist
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/tipc.conf
        regexp: "^(#)?blacklist tipc(\\s|$)"
        line: blacklist tipc
        create: true
        owner: root
        group: root
        mode: '0600'
    
    - name: 3.1.3 | Ensure TIPC is disabled | Disable module
      community.general.modprobe:
        name: tipc
        state: absent
