---
- name: 3.1.1 | Ensure IPv6 status is identified
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6    
  when:
    - rhel9cis_rule_3_1_1_enabled
    - not rhel9cis_ipv6_needed
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true

- name: 3.1.2 | Ensure wireless interfaces are disabled
  when:
    - rhel9cis_rule_3_1_2_enabled
    - _rhel9cis_server
  become: true
  block:
    - name: 3.1.2 | Ensure wireless interfaces are disabled | Check if wifi is enabled
      ansible.builtin.command: nmcli radio wifi
      changed_when: false
      failed_when: false
      register: _rhel9cis_wifi_status

    - name: 3.1.2 | Ensure wireless interfaces are disabled | Disable wifi
      when:
        - _rhel9cis_wifi_status.stdout.find('enabled') != -1
      ansible.builtin.command: nmcli radio all off
      changed_when: true
      failed_when: false

- name: 3.1.3 | Ensure bluetooth services are not in use
  when:
    - rhel9cis_rule_3_1_3_enabled
    - rhel9cis_rule_3_1_3_force or _rhel9cis_server or _rhel9cis_level2
  become: true
  block:
    - name: 3.1.3 | Ensure bluetooth services are not in use | bluez package
      when:
        - not _rhel9cis_bluez_package_needed
      ansible.builtin.dnf:
        name:
          - bluez
        state: absent

    - name: 3.1.3 | Ensure bluetooth services are not in use | bluetooth.service
      ansible.builtin.systemd_service:
        name: bluetooth.service
        state: stopped
        enabled: false
        masked: true
      register: _rhel9cis_bluetooth_service
      failed_when:
        - _rhel9cis_bluetooth_service is failed
        - ("Could not find the requested service" not in _rhel9cis_bluetooth_service.msg)
