---
- name: "2.3.4.1 | L1 | Ensure 'Devices: Prevent users from installing printer drivers' is set to 'Enabled'"
  when:
    - w2022cis_rule_2_3_4_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\System\Currentcontrolset\Control\Print\Providers\Lanman Print Services\Servers
    name: AddPrinterDrivers
    data: 1
    type: dword
