---
- name: 1.2.x | Get /etc/yum.repos.d/ contents
  become: true
  ansible.builtin.find:
    paths: /etc/yum.repos.d
    file_type: file
    recurse: true
    patterns:
      - '*.repo'
  register: _rhel9cis_yum_repos

- name: 1.2.1 | Ensure GPG keys are configured
  loop: "{{ _rhel9cis_yum_repos.files }}"
  when:
    - rhel9cis_rule_1_2_1_enabled
  ansible.builtin.include_tasks: check-file-gpgkey.yml
  vars:
    _rhel9cis_gpgkey_file: "{{ item.path }}"
  loop_control:
    label: "{{ item.path }}"

- name: 1.2.2 | Ensure gpgcheck is globally activated
  when:
    - rhel9cis_rule_1_2_2_enabled
  become: true
  block:
    - name: 1.2.2 | Ensure gpgcheck is globally activated | /etc/dnf/dnf.conf
      ansible.builtin.replace:
        path: /etc/dnf/dnf.conf
        regexp: '^gpgcheck=0'
        replace: gpgcheck=1

    - name: '1.2.2 | Ensure gpgcheck is globally activated | /etc/yum.repos.d/*'
      loop: "{{ _rhel9cis_yum_repos.files }}"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^gpgcheck=0'
        replace: gpgcheck=1
      loop_control:
        label: "{{ item.path }}"

- name: 1.2.3 | Ensure package manager repositories are configured
  when:
    - rhel9cis_rule_1_2_3_enabled
  ansible.builtin.include_tasks: ../../add-warning.yml
  vars:
    _rhel9cis_warning_rule: '1.2.3'
    _rhel9cis_warning_description: This cannot be automated. Please ensure the repositories are configured as required.

- name: 1.2.4 | Ensure repo_gpgcheck is globally activated
  when:
    - rhel9cis_rule_1_2_4_enabled
    - _rhel9cis_level2 or rhel9cis_rule_1_2_4_force
  become: true
  block:
    - name: 1.2.4 | Ensure repo_gpgcheck is globally activated | /etc/dnf/dnf.conf
      ansible.builtin.replace:
        path: /etc/dnf/dnf.conf
        regexp: '^repo_gpgcheck=0'
        replace: repo_gpgcheck=1

    - name: '1.2.4 | Ensure repo_gpgcheck is globally activated | /etc/yum.repos.d/*'
      loop: "{{ _rhel9cis_yum_repos.files }}"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^repo_gpgcheck=0'
        replace: repo_gpgcheck=1
      loop_control:
        label: "{{ item.path }}"
