---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: windows2022
  description: This role applies the CIS Benchmark hardening steps on Windows Server 2022 machines. It is based on the CIS Benchmark for Windows Server 2022, v3.0.0.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Windows
      versions:
        - '2022'

collections:
  - ansible.windows
  - chocolatey.chocolatey
  - community.windows

dependencies: []
