---
name: Generate Role Docs - windows2025 role
'on':
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs-windows2025.yml
      - roles/windows2025/.aar_doc.yml
      - roles/windows2025/meta/argument_specs.yml
      - roles/windows2025/meta/main.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-windows2025.yml
      - roles/windows2025/.aar_doc.yml
      - roles/windows2025/meta/argument_specs.yml
      - roles/windows2025/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.cis'
jobs:
  docs:
    name: Generate windows2025 role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.cis'
      role_name: 'windows2025'
