---
name: Generate Role Docs - rhel8 role
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-rhel8.yml
      - roles/rhel8/.aar_doc.yml
      - roles/rhel8/meta/argument_specs.yml
      - roles/rhel8/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.cis'
jobs:
  docs:
    name: Generate rhel8 role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.cis'
      role_name: 'rhel8'
