---
name: Generate Role Docs - rhel9 role
'on':
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs-rhel9.yml
      - roles/rhel9/.aar_doc.yml
      - roles/rhel9/meta/argument_specs.yml
      - roles/rhel9/meta/main.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-rhel9.yml
      - roles/rhel9/.aar_doc.yml
      - roles/rhel9/meta/argument_specs.yml
      - roles/rhel9/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.cis'
jobs:
  docs:
    name: Generate rhel9 role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.cis'
      role_name: 'rhel9'
