---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/rhel9/.aar_doc.yml
      - roles/rhel9/README.md
      - roles/rhel9/meta/argument_specs.yml
      - roles/rhel9/meta/main.yml
      - roles/rhel8/.aar_doc.yml
      - roles/rhel8/README.md
      - roles/rhel8/meta/argument_specs.yml
      - roles/rhel8/meta/main.yml
      - roles/windows2025/.aar_doc.yml
      - roles/windows2025/README.md
      - roles/windows2025/meta/argument_specs.yml
      - roles/windows2025/meta/main.yml
      - roles/windows2022/.aar_doc.yml
      - roles/windows2022/README.md
      - roles/windows2022/meta/argument_specs.yml
      - roles/windows2022/meta/main.yml
      - roles/windows2019/.aar_doc.yml
      - roles/windows2019/README.md
      - roles/windows2019/meta/argument_specs.yml
      - roles/windows2019/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.cis'
jobs:
  docs_rhel9:
    name: Generate rhel9 role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.cis'
      role_name: 'rhel9'
  docs_rhel8:
    name: Generate rhel8 role documentation
    permissions:
      contents: write
    needs: docs_rhel9
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.cis'
      role_name: 'rhel8'
  docs_windows2025:
    name: Generate windows2025 role documentation
    permissions:
      contents: write
    needs: docs_rhel8
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.cis'
      role_name: 'windows2025'
  docs_windows2022:
    name: Generate windows2022 role documentation
    permissions:
      contents: write
    needs: docs_windows2025
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.cis'
      role_name: 'windows2022'
  docs_windows2019:
    name: Generate windows2019 role documentation
    permissions:
      contents: write
    needs: docs_windows2022
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.cis'
      role_name: 'windows2019'
