---
name: Molecule - rhel8 role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/rhel8/**
      - '!roles/rhel8/.aar_doc.yml'
      - '!roles/rhel8/README.md'
      - '!roles/rhel8/meta/argument_specs.yml'
      - '!roles/rhel8/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/rhel8/**
      - '!roles/rhel8/.aar_doc.yml'
      - '!roles/rhel8/README.md'
      - '!roles/rhel8/meta/argument_specs.yml'
      - '!roles/rhel8/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.cis'
jobs:
  molecule:
    name: Run Molecule tests
    runs-on:
      - self-hosted
      - linux
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.cis'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          cd ./roles/rhel8
          molecule test
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
